<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>eb21e82f-51a0-4d12-a90a-6c3005013cd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(28) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu2']/ul[11]/li[4]/ul/li[28]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>343fd97a-4090-42d2-8d95-30f8718dc993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/ExternalTransitBorrowLeaderboard.page?init=1</value>
      <webElementGuid>8bf4f36a-b188-4047-8165-a2d140e436ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>跨館預約/調閱館藏借閱排行榜</value>
      <webElementGuid>6d348586-0155-421a-95c4-e8d673cbb3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2&quot;)/ul[@class=&quot;sub_nav_ul&quot;]/li[@class=&quot;current&quot;]/ul[@class=&quot;ssub_nav_ul&quot;]/li[28]/a[1]</value>
      <webElementGuid>f4aa23c0-5a75-4be6-ad7a-f58ee152e064</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2']/ul[11]/li[4]/ul/li[28]/a</value>
      <webElementGuid>cdde0ab9-bb8c-40b4-a1f8-c466099ea2d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'跨館預約/調閱館藏借閱排行榜')]</value>
      <webElementGuid>2ea71ec2-539d-4cb1-acd4-0588896a2848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='館藏流通量統計'])[1]/following::a[1]</value>
      <webElementGuid>b5deeb21-f227-4433-9c67-83d1d79ef0f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='大專院校圖書館讀者身份借閱清單及統計報表'])[1]/following::a[2]</value>
      <webElementGuid>4ef154b5-10b3-49cd-8b73-4ace55e734cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='罰款收款人數/次數統計'])[1]/preceding::a[1]</value>
      <webElementGuid>94d67444-5bb2-4920-8d74-5407920b1b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='跨館預約/調閱使用量統計'])[1]/preceding::a[2]</value>
      <webElementGuid>3abc93d9-b673-4309-8a94-cd391b29e553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='跨館預約/調閱館藏借閱排行榜']/parent::*</value>
      <webElementGuid>1ec7d9b7-4ca5-4497-b1b1-6a61b5a3c204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/ExternalTransitBorrowLeaderboard.page?init=1')]</value>
      <webElementGuid>1abf4713-d1c8-4303-b5b9-e61745ab8306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[28]/a</value>
      <webElementGuid>6a12fa24-93f2-4813-80ee-e1d9c47e3932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/ExternalTransitBorrowLeaderboard.page?init=1' and (text() = '跨館預約/調閱館藏借閱排行榜' or . = '跨館預約/調閱館藏借閱排行榜')]</value>
      <webElementGuid>8c544e1a-7f1f-4ce7-a847-36d5aa92a743</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
