<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3_4_5_6_7_8_9_10</name>
   <tag></tag>
   <elementGuidId>835aef40-f373-4c17-95ba-c77a2ca80bd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='DirectLink_4'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>b > #DirectLink_4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c2f864c8-e70f-4a00-9ac6-5abbdc6bc010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_4</value>
      <webElementGuid>557f0ce9-43cc-4a45-a176-cbf4190da72a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttons</value>
      <webElementGuid>bf94c220-f5a7-447e-9383-67482d80ed4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/circulation/inventory/InventoryMaintain,$DirectLink_4.sdirect?sp=l981</value>
      <webElementGuid>f31101d7-2628-4e17-9517-d1e66519e5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>盤點比對後明細</value>
      <webElementGuid>7e1d46ed-6ac7-4860-9dd0-61a86f7c8a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;If_2&quot;)/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[4]/td[1]/b[1]/a[@id=&quot;DirectLink_4&quot;]</value>
      <webElementGuid>a464e1e8-9b36-4828-ab6e-0f796e04e357</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='DirectLink_4'])[2]</value>
      <webElementGuid>d9ac2896-5e3d-4ee9-83a0-1cb364ecd9f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='If_2']/table/tbody/tr/td/table/tbody/tr[4]/td/b/a</value>
      <webElementGuid>c683bb4e-21e1-4bfe-a25e-87170bc84fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'盤點比對後明細')]</value>
      <webElementGuid>08793e42-7c5b-4859-bc29-9b14308fca22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RUN'])[1]/following::a[1]</value>
      <webElementGuid>a4bd81ba-17ff-498d-9c06-f34b8ae9f69f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='前次作業:'])[1]/following::a[1]</value>
      <webElementGuid>9509b395-6793-44da-9640-a565faa1800c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='條碼號'])[2]/preceding::a[1]</value>
      <webElementGuid>acb4eae3-512c-4aed-b716-323fef0a36d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='館藏狀態'])[1]/preceding::a[1]</value>
      <webElementGuid>042d0c7e-7e7a-4238-b656-d0f07589269d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='盤點比對後明細']/parent::*</value>
      <webElementGuid>e3e7d6e6-e338-4753-b01c-f5bd16d5c449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/circulation/inventory/InventoryMaintain,$DirectLink_4.sdirect?sp=l981')]</value>
      <webElementGuid>a7b83ae8-a642-45fb-a700-6af2bbd032a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b/a</value>
      <webElementGuid>30dd1142-6507-4b8d-9f93-2005ee335154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_4' and @href = '/inspireapp/circulation/inventory/InventoryMaintain,$DirectLink_4.sdirect?sp=l981' and (text() = '盤點比對後明細' or . = '盤點比對後明細')]</value>
      <webElementGuid>4e51bc6a-cb34-4991-9ee6-78e03fc6cea3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
