<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>824574ef-b6a0-4113-8c72-63a3ca37f70f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu2']/ul[10]/li[6]/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'DirectLink_0' and @title = '登出' and @href = '/inspireapp/NewBookEdit,$Border.$DirectLink_0.sdirect' and (text() = '登 出' or . = '登 出')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>86dbab16-3eaa-403f-bece-b857090b9789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/SpecialItemMaintain.page?init=1</value>
      <webElementGuid>ab059651-950d-4d0d-ad83-c5449a3ba9a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>特別書籍維護</value>
      <webElementGuid>49fb0607-76ac-4311-8d1c-718233b441ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2&quot;)/ul[@class=&quot;sub_nav_ul&quot;]/li[@class=&quot;current&quot;]/ul[@class=&quot;ssub_nav_ul&quot;]/li[4]/a[1]</value>
      <webElementGuid>16b826c1-bb05-401b-b89c-42de07bac97a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2']/ul[10]/li[6]/ul/li[4]/a</value>
      <webElementGuid>bab25873-9096-4385-8385-6309cba0634d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'特別書籍維護')]</value>
      <webElementGuid>9ba25b41-1422-41c3-9bd6-8fc35110299e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='主題維護'])[1]/following::a[1]</value>
      <webElementGuid>9b79bb25-3290-4dba-ba77-a671e6db51a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='意見回覆維護'])[1]/following::a[2]</value>
      <webElementGuid>d097cc35-0d36-4184-88b5-bf504c342924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='心得分享'])[1]/preceding::a[1]</value>
      <webElementGuid>0394f3c8-35c3-4529-9d9a-442636158038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='東區互惠審核'])[1]/preceding::a[2]</value>
      <webElementGuid>fbf25450-c76e-4077-bbee-c5ce7b00b4c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='特別書籍維護']/parent::*</value>
      <webElementGuid>ea32e82e-9af2-4253-9b39-5404cbd25ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/SpecialItemMaintain.page?init=1')]</value>
      <webElementGuid>c146d759-294c-49d5-8a66-3ae2ce7a3334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li[4]/a</value>
      <webElementGuid>354c7414-d7a6-4dba-bf6d-b5cbbf39c016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/SpecialItemMaintain.page?init=1' and (text() = '特別書籍維護' or . = '特別書籍維護')]</value>
      <webElementGuid>d86a08fc-adc5-4cdc-8d55-0198d21628a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
