<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_e-resources -</name>
   <tag></tag>
   <elementGuidId>f41f923a-35f1-4b61-8e36-a24d3282f225</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'e-resources - 電子資源' or . = 'e-resources - 電子資源')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='swindow.dlocations56']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1ee74195-97aa-484d-8bfe-a4af07db78e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swindow.dlocations56</value>
      <webElementGuid>faf1a890-5fd3-4bee-8332-0a84746ac3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>node</value>
      <webElementGuid>db18cbaf-1e8b-4d15-a747-666ec1484568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:window.dlocations.selectElement('e-resources - \u96FB\u5B50\u8CC7\u6E90', 3, true)</value>
      <webElementGuid>11924c22-be78-4244-b7f9-1b7fb5fe1738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript: window.dlocations.s(56);</value>
      <webElementGuid>3908c23d-aa08-41a5-9239-546a44c83112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>e-resources - 電子資源</value>
      <webElementGuid>b7e9a3c4-fb46-4bfd-9c48-68e515d81546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swindow.dlocations56&quot;)</value>
      <webElementGuid>d8c5bf0a-9392-483b-a9b8-1ce2b78bf3e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='swindow.dlocations56']</value>
      <webElementGuid>f43fadb1-0dd8-43c7-9433-1e58a3a3776b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dwindow.dlocations1']/div[20]/a</value>
      <webElementGuid>6b39a6cd-a025-443b-83c5-7680a7cb0ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'e-resources - 電子資源')]</value>
      <webElementGuid>267b20a7-a03b-44ae-ae1c-dc7544e3d5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ONLN - 台中總館線上資料'])[1]/following::a[1]</value>
      <webElementGuid>4840c111-38bf-4e64-bc80-e11083d901b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='new item 7 - new item 7'])[1]/following::a[2]</value>
      <webElementGuid>85c0c68f-e707-49bc-ae05-c7c6b2ea4975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EB-P - EB-P'])[1]/preceding::a[1]</value>
      <webElementGuid>7e9f0cf1-ec04-40bc-ac92-af083a6fe3c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='elect - elect'])[1]/preceding::a[2]</value>
      <webElementGuid>f3ed79cf-3cb6-4b95-af09-d4e84a6393a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='e-resources - 電子資源']/parent::*</value>
      <webElementGuid>e060ffed-3519-4c9d-a5bf-695bda6bbbee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:window.dlocations.selectElement('e-resources - \u96FB\u5B50\u8CC7\u6E90', 3, true)&quot;)]</value>
      <webElementGuid>73806c06-7600-4f2a-be61-d23fc19998f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/a</value>
      <webElementGuid>1edec329-1d9b-4bd2-a7cf-efc764532ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'swindow.dlocations56' and @href = concat(&quot;javascript:window.dlocations.selectElement(&quot; , &quot;'&quot; , &quot;e-resources - \u96FB\u5B50\u8CC7\u6E90&quot; , &quot;'&quot; , &quot;, 3, true)&quot;) and (text() = 'e-resources - 電子資源' or . = 'e-resources - 電子資源')]</value>
      <webElementGuid>6d3d3b53-48e9-4841-b536-8d4686d0b9c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
