<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b__1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>2d3c2245-ea3d-47f2-bef7-4a419d12a95d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='viewPatronDetailsComponent']/tbody/tr/td[3]/table/tbody/tr/td[3]/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>6a5fd3ad-88d2-4f5a-b269-d15404ccaea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>賠款總計:</value>
      <webElementGuid>e59b0f07-7100-461f-ab0d-d387de50d792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;viewPatronDetailsComponent&quot;)/tbody[1]/tr[1]/td[3]/table[@class=&quot;table4&quot;]/tbody[1]/tr[1]/td[@class=&quot;table4_left&quot;]/b[1]</value>
      <webElementGuid>28bff74c-8bfa-422b-bbae-d8800e41e540</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='viewPatronDetailsComponent']/tbody/tr/td[3]/table/tbody/tr/td[3]/b</value>
      <webElementGuid>a58f0b87-97d0-4fcb-b63b-059f355125f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='本館借閱量:'])[1]/following::b[1]</value>
      <webElementGuid>fea95869-9447-4b1b-9751-6959a184c257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A11234'])[1]/following::b[2]</value>
      <webElementGuid>09673c82-599d-4744-bbcf-54946f80a885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='已借閱冊數:'])[1]/preceding::b[1]</value>
      <webElementGuid>393a04a4-3582-4fd8-a31a-f52f58938a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='逾期罰款:'])[1]/preceding::b[2]</value>
      <webElementGuid>60c6f04e-a4e5-4b30-ad9e-410b444b5acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='賠款總計:']/parent::*</value>
      <webElementGuid>f91ec744-d522-4983-832a-2460e558b8ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/b</value>
      <webElementGuid>5db2f168-ca5e-43ef-992b-abc1af669e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = '賠款總計:' or . = '賠款總計:')]</value>
      <webElementGuid>9ccaa58e-889a-46fc-afb1-e7de2f6bdae4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
