<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CC20240319</name>
   <tag></tag>
   <elementGuidId>2c33ea81-358c-4f59-81d0-32ab533b21fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b4b221b2-f000-46bc-a5ef-2e903aeb74b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_4</value>
      <webElementGuid>69dc3c1e-bf93-4bae-8e5b-e5ee50f41393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return createPopEdit(this.href);</value>
      <webElementGuid>e91f56cf-4763-4dc8-a02f-51335cc6d172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/MaintainSingle,crsMaintainSingle.$DirectLink_1.sdirect?sp=l1661</value>
      <webElementGuid>aad0757a-069e-40db-ae6b-a7b4fbfad6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        		CC20240319
        	</value>
      <webElementGuid>2defcfe0-9ab3-4f87-ab0f-71a403611233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_4&quot;)</value>
      <webElementGuid>a42f65ad-3b94-40b3-b8ee-6c756844121b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_4']</value>
      <webElementGuid>4cd1eb73-fd0e-414d-9e8b-bd138a9ece49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='For_4']/td[6]/a</value>
      <webElementGuid>1a2217a0-fb06-4967-a895-4a43d9bb7f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CC20240319')]</value>
      <webElementGuid>273655b2-5f10-4028-9dd3-05370deba5f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[1]/following::a[3]</value>
      <webElementGuid>c72cecad-b1c0-4646-b35e-dfbe68fc9138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='館藏地'])[2]/following::a[3]</value>
      <webElementGuid>3ef70868-2fb0-410c-9650-35fb49183dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='講桌'])[2]/preceding::a[1]</value>
      <webElementGuid>db6ca315-a496-49d6-a506-d31a6895961a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='測試設備123'])[1]/preceding::a[1]</value>
      <webElementGuid>47f758a1-8283-4cbd-bac3-aa4456adda20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CC20240319']/parent::*</value>
      <webElementGuid>efa92a06-0597-4546-ac48-f46ee5fc5185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/MaintainSingle,crsMaintainSingle.$DirectLink_1.sdirect?sp=l1661')]</value>
      <webElementGuid>d3386bba-3a0c-451b-9470-ba60f1ce13cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
      <webElementGuid>751c3cd8-a32f-4627-bdf4-c48f443ff0fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_4' and @href = '/inspireapp/MaintainSingle,crsMaintainSingle.$DirectLink_1.sdirect?sp=l1661' and (text() = '
        		CC20240319
        	' or . = '
        		CC20240319
        	')]</value>
      <webElementGuid>ae5bfed3-faa2-4db9-b54d-d6556ad42c56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
