<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__RadioGroup</name>
   <tag></tag>
   <elementGuidId>b6929725-f44f-436d-b574-dfc935dcb04b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RadioGroup0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#RadioGroup0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c7e00ce-b496-4c9a-be94-bff8904fcc60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>54e668ea-033c-46b7-a3a8-1eb828689f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RadioGroup</value>
      <webElementGuid>1559aa59-9e46-4752-88a3-a3f7fa7356a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RadioGroup0</value>
      <webElementGuid>34965859-e8b5-462d-86dc-e7d8bf9f400b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>492ce9c2-c2f1-4eb1-9066-32cac815e13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>tapestry.byId('RadioGroup').onChange(0);</value>
      <webElementGuid>a13bc7d8-29ce-4342-ba56-59644e1214fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RadioGroup0&quot;)</value>
      <webElementGuid>9b6e834b-e53d-4a41-944c-7f4130c461b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RadioGroup0']</value>
      <webElementGuid>de924274-f225-49dc-8705-e03f9bb7b291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='RadioGroup']/tbody/tr[2]/td/div/table/tbody/tr/td/input</value>
      <webElementGuid>8fe4d0fa-dfcb-41cc-9bb1-b0ec2ffc613c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td/input</value>
      <webElementGuid>71d080e8-4105-419c-8213-a111677d12c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'RadioGroup' and @id = 'RadioGroup0']</value>
      <webElementGuid>f5b27d21-9e2b-4623-92cd-4b6fa9cce17e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
