<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td__1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>7c6000f6-874d-4b5b-aef5-18e62d933d32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='If_54']/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#If_54 > td.limit_title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>baecf911-35da-48bc-98df-86b3f1c90b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>limit_title</value>
      <webElementGuid>623bcc9a-f576-48b4-9955-49b94b10f97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>館藏狀態:</value>
      <webElementGuid>7c7cf85e-b634-4e85-9f48-0f835eda256d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;If_54&quot;)/td[@class=&quot;limit_title&quot;]</value>
      <webElementGuid>75290470-84fe-4bf0-a11a-001167134bff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='If_54']/td</value>
      <webElementGuid>9b7af982-85c4-415a-abe5-1d8d057ae8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='館藏使用類型:'])[1]/following::td[2]</value>
      <webElementGuid>800e3956-8d81-4b17-9e61-7e98183a851e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='讀者身份類別:'])[1]/following::td[4]</value>
      <webElementGuid>b4f584e8-5bdb-46ea-ade5-95e90696d9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='館藏流通類別:'])[1]/preceding::td[2]</value>
      <webElementGuid>b398137e-5352-44f0-9261-40c1e7b11f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='瀏覽條件:'])[1]/preceding::td[4]</value>
      <webElementGuid>36b86783-1831-45b8-8d98-f8dd3ca07572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='館藏狀態:']/parent::*</value>
      <webElementGuid>a4fa5734-e09a-409e-89df-2c741b379d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td</value>
      <webElementGuid>958287db-9c44-4b99-9d3d-273662f1a39d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '館藏狀態:' or . = '館藏狀態:')]</value>
      <webElementGuid>51704e73-a4af-4c9a-8ff6-05116d9f67f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
