<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>5cd401cc-c569-4e78-9828-b5eeb3805434</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Insert_9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='Insert_9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b7599cff-13b5-4a6b-9d91-bf41dcdc421d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blueTitle</value>
      <webElementGuid>2da8e20f-e952-493d-a1de-2fe1745d526c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Insert_9</value>
      <webElementGuid>2cee8f84-24b8-480a-b01a-bb9fbe2e11bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>限制條件</value>
      <webElementGuid>4d7daefc-b58a-4de5-8166-924797691d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Insert_9&quot;)</value>
      <webElementGuid>2de040f7-7ecb-4d15-9536-a92fb78d039f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='Insert_9']</value>
      <webElementGuid>1a7ffddf-49d4-43de-9d71-93da1780cc79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='If_34']/tbody/tr/td/span</value>
      <webElementGuid>83213a5f-495f-43b4-96e8-d9c21562719b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='限制條件'])[1]/following::span[2]</value>
      <webElementGuid>4bb64369-12eb-467a-be5f-893346b8ffe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='查詢條件'])[1]/following::span[10]</value>
      <webElementGuid>41cfb212-37c6-4701-a13c-dabe206aced2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='交易狀態類型:'])[1]/preceding::span[1]</value>
      <webElementGuid>a2f4e7da-c8ac-49fa-bb64-495be2427413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='交易紀錄類型:'])[1]/preceding::span[1]</value>
      <webElementGuid>41d8881a-7d54-4cb3-9544-74242e12a4f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span</value>
      <webElementGuid>7906f638-d964-4e74-b6a0-b51469d38e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'Insert_9' and (text() = '限制條件' or . = '限制條件')]</value>
      <webElementGuid>5f41a4be-7847-4936-9d2e-c0d46aa91ae9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
