<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td__1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>865e2d7a-ce6a-4889-a199-0d19b92aa55d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(7) > td.limit_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='If_34']/tbody/tr[7]/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>effad371-47fe-43cf-91bb-9e491a09af42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>limit_title</value>
      <webElementGuid>eb3ed1c5-ef13-46e3-8fc6-f483b814b7a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>資料類型:</value>
      <webElementGuid>706cbdf3-c5f2-46c4-a2cf-41acaab9eba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;If_34&quot;)/tbody[1]/tr[7]/td[@class=&quot;limit_title&quot;]</value>
      <webElementGuid>40516985-d218-465b-9e57-5d15d4aa1448</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='If_34']/tbody/tr[7]/td</value>
      <webElementGuid>ed02b0f6-06f8-4641-9a53-43ff4ed09974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='館藏地:'])[1]/following::td[2]</value>
      <webElementGuid>b3baa63c-0e56-499b-941c-a520558e64cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='館藏狀態:'])[1]/following::td[4]</value>
      <webElementGuid>7c8a52e3-925e-4164-b1e2-935a38d4e9b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='單位所系:'])[1]/preceding::td[2]</value>
      <webElementGuid>454033da-8e48-4a21-8c55-ef1265a357ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='單位所系'])[2]/preceding::td[4]</value>
      <webElementGuid>8787d073-6f4e-46fe-8cdb-62011ccde725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='資料類型:']/parent::*</value>
      <webElementGuid>2ad60306-d8ea-4004-a3ca-2e12e09e5629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td</value>
      <webElementGuid>5104c602-b00e-4800-aef7-2e25a686456d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '資料類型:' or . = '資料類型:')]</value>
      <webElementGuid>b7aa3646-7312-4a65-8902-d223a133d37a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
