<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(15trunk)_Submit</name>
   <tag></tag>
   <elementGuidId>c77a2643-96fa-4389-991a-4421abbec886</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>694bbd61-e34e-42a5-80c2-dec3e6c3d18e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>501ddeea-f935-4864-b949-9f2fade86b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>7988a0ba-4aa2-4c9c-b9bc-452a68833699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>ff827d6b-bf57-48e8-8e74-2bc8190bbcc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>login(dojo.byId('logon'))</value>
      <webElementGuid>ccf0fa0a-78a6-4bdf-8164-db1b9938fd1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>登入</value>
      <webElementGuid>09ef3d9a-4c5b-4fc6-9587-2d19db032e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login_btn</value>
      <webElementGuid>04f3d749-9abc-4838-bb67-10071570f685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Submit&quot;)</value>
      <webElementGuid>e2e1aeda-22b7-4d3b-8e9a-aaea26922892</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Submit']</value>
      <webElementGuid>49ee8047-7bbd-4fb0-a4eb-b07bd8ff6763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='logon']/table/tbody/tr[3]/td/button/input</value>
      <webElementGuid>b489b877-3703-4559-8e32-c35995893396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/input</value>
      <webElementGuid>c931f57d-68c4-4689-b293-1dc629f1b775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'Submit' and @id = 'Submit']</value>
      <webElementGuid>9b343b06-c83f-4bc1-8cb5-dc39a75a9853</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
