<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>feb2f19b-a3dc-4253-acce-b8b4d793430a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu2']/ul[12]/li[3]/ul/li[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.current > ul.ssub_nav_ul > li:nth-of-type(7) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e387a357-42ec-48f8-8eed-818afda5f6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/DelayList.page?init=1</value>
      <webElementGuid>dde94bd5-cd8e-413e-af9d-a01e1699c1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>借閱逾期清單</value>
      <webElementGuid>72adbcc4-ed05-4a5a-b980-31ce7a0f6765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2&quot;)/ul[@class=&quot;sub_nav_ul&quot;]/li[@class=&quot;current&quot;]/ul[@class=&quot;ssub_nav_ul&quot;]/li[7]/a[1]</value>
      <webElementGuid>6e8422ab-ee93-4cf7-ad08-4f39a6d18356</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2']/ul[12]/li[3]/ul/li[7]/a</value>
      <webElementGuid>c67a1fc6-3fce-4b7c-b0e2-b414133b81af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'借閱逾期清單')]</value>
      <webElementGuid>d7e435f4-33b3-4921-8d75-9962f080ff34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='讀者欠款清單'])[1]/following::a[1]</value>
      <webElementGuid>a80df23b-cc32-4cd3-8cfa-4a0d88cae0c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='新書清單'])[1]/following::a[2]</value>
      <webElementGuid>1783eb23-580d-4942-8358-ceeab165ac8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='罰款收款清單'])[1]/preceding::a[1]</value>
      <webElementGuid>03c8c8a0-60ad-4515-bc84-c54042e02a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='預約撤架清單'])[1]/preceding::a[2]</value>
      <webElementGuid>7341efd9-6b6a-4473-8431-78a94959d4f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='借閱逾期清單']/parent::*</value>
      <webElementGuid>4b617c97-ea8d-4a28-8194-e73dbceaa515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/DelayList.page?init=1')]</value>
      <webElementGuid>93d0f7e2-9121-4610-9a8a-0cc79a929e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[12]/li[3]/ul/li[7]/a</value>
      <webElementGuid>0aeb9ee8-5300-4c5e-ad2c-29092de3622d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/DelayList.page?init=1' and (text() = '借閱逾期清單' or . = '借閱逾期清單')]</value>
      <webElementGuid>3fa26170-da72-4f7e-89cf-425591a1779f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
