<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>d4ae2e19-12a3-4047-8535-b1d984c3c9a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_0_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_0_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>074218d8-7750-486e-8f18-a02d24c9985d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_0_0</value>
      <webElementGuid>a152e5df-3290-444b-9e61-8a4190efec0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>butonsub</value>
      <webElementGuid>c18a949f-adbc-463b-883f-413f112e4326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/IdentityLoanListStatistics,ReportsStatus.$DirectLink_0.sdirect?updateParts=ReportStatus</value>
      <webElementGuid>deef2dd5-0ea4-440d-ab9a-c21aca372321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return tapestry.linkOnClick(this.href,'DirectLink_0_0', false)</value>
      <webElementGuid>4dddb483-4d28-4b6b-81ee-f1f67b001e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
										關閉 
								</value>
      <webElementGuid>73df234c-1992-40e5-984e-660646133f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_0_0&quot;)</value>
      <webElementGuid>205d3688-7c56-4b56-9cd1-fa720242d3e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_0_0']</value>
      <webElementGuid>62603e66-c2b6-4473-a5e4-63ddeeca87f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='If_7']/div/table/tbody/tr/td/table/tbody/tr/td[2]/a</value>
      <webElementGuid>ef02258f-5b8a-4f41-92a7-53a378afbbd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'關閉')]</value>
      <webElementGuid>49138d39-a01e-4712-aaf1-ebfe6532b46f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='報表狀態'])[2]/following::a[2]</value>
      <webElementGuid>814093df-555f-4c82-a5e3-34217b68e25b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='執行時間'])[1]/preceding::a[1]</value>
      <webElementGuid>9d8d3118-5fe5-4458-b07a-d613425b01a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/IdentityLoanListStatistics,ReportsStatus.$DirectLink_0.sdirect?updateParts=ReportStatus')]</value>
      <webElementGuid>f0fbfdd5-f37c-4ad6-a534-babebe202140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td[2]/a</value>
      <webElementGuid>63cc9678-eb68-412b-945d-0d1dd58ed78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_0_0' and @href = '/inspireapp/IdentityLoanListStatistics,ReportsStatus.$DirectLink_0.sdirect?updateParts=ReportStatus' and (text() = ' 
										關閉 
								' or . = ' 
										關閉 
								')]</value>
      <webElementGuid>90bd99fd-c14c-4de0-a7df-4cf45a07c7c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
