<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>d15bc7e6-a72f-4c69-ac19-3361b9f47895</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jumpPage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='jumpPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d124b1e6-53a6-4207-ba09-8265923aea42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jumpPage</value>
      <webElementGuid>bfc92667-22e0-4839-a188-9691cb93e4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/BookLabelsReport,jumpPage.sdirect?sp=2&amp;updateParts=results&amp;updateParts=nrResults</value>
      <webElementGuid>a1734d80-b35e-41d1-a369-530f534d0de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return tapestry.linkOnClick(this.href,'jumpPage', false)</value>
      <webElementGuid>073dcee6-1c12-4f80-b2a5-6a00a3f97cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>12b872a9-185f-4710-b69a-3dcd946519e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jumpPage&quot;)</value>
      <webElementGuid>42b05e9d-8685-4739-ab60-9bc9dd09689d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='jumpPage']</value>
      <webElementGuid>4a41d26b-6d66-4c3f-af1b-50364c3b9b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='For_1']/li/a</value>
      <webElementGuid>c6041d4f-d4a8-4577-ab46-12f3d7d50fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'2')])[10]</value>
      <webElementGuid>388257aa-5be7-4fcd-89a9-b34f8389197d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='若輸出結果為空白,請縮小字體或減少輸出欄位'])[1]/following::a[5]</value>
      <webElementGuid>76cd9146-f260-4188-9479-575ce2eb7176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='序號'])[1]/preceding::a[6]</value>
      <webElementGuid>5e58edb6-10b9-4681-a6ee-ded0242e6a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='條碼號'])[2]/preceding::a[6]</value>
      <webElementGuid>15c40fb9-5b03-4335-bce5-b90b3a25a345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2']/parent::*</value>
      <webElementGuid>60ec4ffd-3912-4dcf-9e50-fb3d019f8ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/BookLabelsReport,jumpPage.sdirect?sp=2&amp;updateParts=results&amp;updateParts=nrResults')]</value>
      <webElementGuid>2a5b4778-cf7b-4cb3-84da-d2d846387920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/li/a</value>
      <webElementGuid>766c0813-c994-4896-b50a-eaf142ed4910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'jumpPage' and @href = '/inspireapp/BookLabelsReport,jumpPage.sdirect?sp=2&amp;updateParts=results&amp;updateParts=nrResults' and (text() = '2' or . = '2')]</value>
      <webElementGuid>992c5d61-4a6d-4d03-804e-3eb2da80282c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
