<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>ed47f744-8d8e-47b8-a474-2d4f26389da5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.current > ul.ssub_nav_ul > li:nth-of-type(7) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu2']/ul[11]/li[4]/ul/li[7]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d6aaff1f-c560-4210-b307-c71f6158652a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/PatronLoanCrossReport.page?init=1</value>
      <webElementGuid>2708a85c-f467-4019-bf30-758d55c5d35e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>讀者借閱交叉分析</value>
      <webElementGuid>74227d02-2885-43e4-b9fa-bbf625fdc85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2&quot;)/ul[@class=&quot;sub_nav_ul&quot;]/li[@class=&quot;current&quot;]/ul[@class=&quot;ssub_nav_ul&quot;]/li[7]/a[1]</value>
      <webElementGuid>f8b56dd9-0ac3-402f-afe6-d75870d555d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2']/ul[11]/li[4]/ul/li[7]/a</value>
      <webElementGuid>3c86f3e5-103a-479d-82bf-368f9cc91781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'讀者借閱交叉分析')]</value>
      <webElementGuid>43ec0434-5e98-4b3a-9ecb-0d921e35f1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='利用概況統計(日報表)'])[1]/following::a[1]</value>
      <webElementGuid>f81d6ecc-5fdd-448f-94de-b82a2400df1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='流通人次冊數統計'])[1]/following::a[2]</value>
      <webElementGuid>55105bab-036d-4eb6-9130-941e696e354b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='各館特藏預約統計報表'])[1]/preceding::a[1]</value>
      <webElementGuid>fb98055a-3e4b-49a6-9fee-630a83dc90e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='館內使用統計'])[1]/preceding::a[2]</value>
      <webElementGuid>b6388504-621a-4b21-9867-9802f526860b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='讀者借閱交叉分析']/parent::*</value>
      <webElementGuid>b1898d10-60b2-48b5-a3f5-84b8e1cc0b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/PatronLoanCrossReport.page?init=1')]</value>
      <webElementGuid>288a2ec0-cb30-4343-b3ec-79e38204076e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[7]/a</value>
      <webElementGuid>d450ae30-cdda-465a-8655-99ac560deced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/PatronLoanCrossReport.page?init=1' and (text() = '讀者借閱交叉分析' or . = '讀者借閱交叉分析')]</value>
      <webElementGuid>1f4e96c9-db4d-45de-a4e4-07258e143d22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
