<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__field3</name>
   <tag></tag>
   <elementGuidId>db8be264-a11b-490d-8d78-0b279ee1af03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4d51555-b765-474b-a965-cafda93f2607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4bfee413-6a5d-4947-91ca-fa9e308183b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>507725ef-8675-414a-b58f-e731df60b2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field3</value>
      <webElementGuid>6259f466-7269-442f-ba69-df51effec9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field3</value>
      <webElementGuid>a51072db-4cc6-40a2-92c6-05bf04dfae69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_mare</value>
      <webElementGuid>3ec18fc3-0efe-4d31-89d2-3babf29c7610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>VirtualKeyboard.attachInput(this); diacriticInsert(this);</value>
      <webElementGuid>86bf60d6-fcd3-49e6-986a-46986b1d532f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field3&quot;)</value>
      <webElementGuid>132773e6-35e4-463d-99d1-651c058cd160</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field3']</value>
      <webElementGuid>20c1420a-c6b7-457e-9253-880d1baa6386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='inputField3']/nobr/input</value>
      <webElementGuid>b19905d3-cf02-49e6-94f6-fe39fa95614b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]/span[2]/nobr/input</value>
      <webElementGuid>c4060669-6701-4363-b2fc-e591447e3c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field3' and @name = 'field3']</value>
      <webElementGuid>e30bb12f-6e18-45da-906b-2188b9d7eeb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
