<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_andornot_1_2</name>
   <tag></tag>
   <elementGuidId>2c36e3c0-9633-451d-9146-dcc9dec58c99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#boolean4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='boolean4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1d5d51bc-a535-4810-990c-6df38ac0e843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>boolean4</value>
      <webElementGuid>b904e662-8881-4665-b023-0ca290b9adcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boolean4</value>
      <webElementGuid>3d50258d-e60e-46c0-8740-ba6202b6bf95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
and
or
not
</value>
      <webElementGuid>9b0bc09d-bb93-45db-ab8a-8fb1fbab897e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boolean4&quot;)</value>
      <webElementGuid>62766e08-5fa2-4cfb-be7f-c74fdd1e35b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='boolean4']</value>
      <webElementGuid>4aa48e8b-cbfb-4227-a2cf-cc1c940ae473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='If_22']/select</value>
      <webElementGuid>aca71293-b714-40ed-bb44-93be0080b673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A100411899'])[1]/following::select[1]</value>
      <webElementGuid>0f368a30-4851-4feb-990c-e1379dc1ac56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A100404278'])[1]/following::select[1]</value>
      <webElementGuid>3e3c14ae-f5f7-4b94-8556-de8b3a007fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='限制條件'])[1]/preceding::select[3]</value>
      <webElementGuid>15dfa17a-c4eb-4bbf-bfd5-2233c98bd227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='限制條件'])[2]/preceding::select[3]</value>
      <webElementGuid>b005a19c-a9ed-4dd3-9b94-2b23f0c374d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[7]/select</value>
      <webElementGuid>6ebabee0-b9a5-4f8a-b488-a9e807d1f004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'boolean4' and @id = 'boolean4' and (text() = '
and
or
not
' or . = '
and
or
not
')]</value>
      <webElementGuid>48acb99f-1af4-4a71-9a6d-ff21de2788f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
