<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__1</name>
   <tag></tag>
   <elementGuidId>3f1a9dd7-d1cd-4f96-9631-7b733e5976a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sCriteria3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='sCriteria3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c6a2f001-29e7-454d-9a5b-056b961b8a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sCriteria3</value>
      <webElementGuid>7097dc6a-da48-412e-a079-263abfe62c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sCriteria3</value>
      <webElementGuid>0be1770c-215d-41e3-ab18-155cd3973301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
條碼號
正題名
系統識別號
起始日期
結束日期
完成日期
讀者姓名
讀者證號
</value>
      <webElementGuid>2c619171-a742-4a59-a0b6-64641cd45ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sCriteria3&quot;)</value>
      <webElementGuid>eae03338-2e01-4874-9ca0-481165893b58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='sCriteria3']</value>
      <webElementGuid>70106f95-8f1c-4ff1-b55c-59dae3a6c1fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='If_16']/select[2]</value>
      <webElementGuid>8e84316a-34ac-4bfe-9a3f-a5b5b495ce17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='楊世敏'])[1]/following::select[2]</value>
      <webElementGuid>c4c95e24-0d17-432d-8142-87565b902f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='楊世凡'])[1]/following::select[2]</value>
      <webElementGuid>72d6411a-1330-4a8b-89f5-b5e5e5a36b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='限制條件'])[1]/preceding::select[5]</value>
      <webElementGuid>fdb57c71-34f9-47ad-b3f5-1bccec95cd66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='限制條件'])[2]/preceding::select[5]</value>
      <webElementGuid>7936a425-fffc-40d3-bad4-af8dabc8b202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]/select[2]</value>
      <webElementGuid>bf458d22-c7d3-46bf-99eb-2a790dd7405d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'sCriteria3' and @id = 'sCriteria3' and (text() = '
條碼號
正題名
系統識別號
起始日期
結束日期
完成日期
讀者姓名
讀者證號
' or . = '
條碼號
正題名
系統識別號
起始日期
結束日期
完成日期
讀者姓名
讀者證號
')]</value>
      <webElementGuid>bbc9399a-4e61-4366-a44b-a1be42f441c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
