<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3</name>
   <tag></tag>
   <elementGuidId>6ef1a421-5cc4-4ea3-8b1a-4805daecb399</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='batchRequest']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#batchRequest</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4088d925-9585-490d-9269-5ca352be8966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/myaccount/Bookmarks,RequestDialog.requestDialogForm.sdirect?updateParts=RequestDialog</value>
      <webElementGuid>aabca78e-97cc-4e1e-ad18-28d6a3aa43cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>tapestry.form.submit('requestDialogForm', 'batchRequest',{async:true,json:false,url:this.href}); return false;</value>
      <webElementGuid>2d897f78-bd27-40e0-b29f-9b839329391f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>batchRequest</value>
      <webElementGuid>3a94feb6-f5a4-4212-9fbb-65b9b546aab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>0b760bd5-a75e-4a86-9b9b-e6e07fb8d7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>請購</value>
      <webElementGuid>45e5b3bd-6696-4359-9cfe-0100c3bd85ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;batchRequest&quot;)</value>
      <webElementGuid>9ce624df-78da-467b-adfc-50060bb05665</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='batchRequest']</value>
      <webElementGuid>204e5aa0-5d22-4c1f-ba4b-d318a600b733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='requestDialogForm']/fieldset/div[2]/table/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>83114bc6-5f5e-4aa9-9f1d-06d9deb50e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'請購')])[5]</value>
      <webElementGuid>8f924d2b-6e2d-43da-87d8-0a60457ab159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='關閉'])[1]/following::a[1]</value>
      <webElementGuid>7f181b89-11af-4c96-9fd0-6aa90ae5bdae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='請購數量'])[1]/following::a[2]</value>
      <webElementGuid>5038f284-93ed-4786-8289-fb5aab2ddda4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright© 2016 iNspire 4.4.0-SNAPSHOT by Claridy Solutions, Inc. All rights reserved.'])[1]/preceding::a[1]</value>
      <webElementGuid>02b45f98-5b85-4d4c-b860-daa081a4877b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/myaccount/Bookmarks,RequestDialog.requestDialogForm.sdirect?updateParts=RequestDialog')]</value>
      <webElementGuid>9a8c517f-9f5e-41b3-b94b-bc37e1dbf432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>1f25c36c-1b27-4320-b8aa-cf57cf2ef2eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/myaccount/Bookmarks,RequestDialog.requestDialogForm.sdirect?updateParts=RequestDialog' and @id = 'batchRequest' and (text() = '請購' or . = '請購')]</value>
      <webElementGuid>a4ae7c37-0c8f-4656-817c-a89b9c771b58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
