<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__formSubmitSearch</name>
   <tag></tag>
   <elementGuidId>693fa6b5-5e44-4a68-ba69-a63a5fa1b94e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formSubmitSearch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formSubmitSearch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99fc10ed-d310-4f3c-a8dd-9962051c647e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4bc8d171-2988-4fea-9855-f88b460cba87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formSubmitSearch</value>
      <webElementGuid>b62ff4a0-a2dc-46ee-becf-3753461b6d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formSubmitSearch</value>
      <webElementGuid>6ebf7cc5-45b8-485d-92c1-bf6d9d183121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>查詢</value>
      <webElementGuid>3abfcfe9-13ca-4af2-9e68-fdeb00a25d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttons buttons_work</value>
      <webElementGuid>aff3b416-c8d0-439d-9d42-49e621101ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSubmitSearch&quot;)</value>
      <webElementGuid>f61f4e0a-31f4-43cd-95b5-dfa7c3595020</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formSubmitSearch']</value>
      <webElementGuid>05497b9d-e2b3-46e9-979a-63c9100205d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HiddenSearch']/div/div[2]/p/input</value>
      <webElementGuid>795e60f5-cdc9-4941-b5d5-3a58a3cfcaa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>daefcaea-99f9-4655-bb6c-9e8ea545940f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'formSubmitSearch' and @id = 'formSubmitSearch']</value>
      <webElementGuid>e63ba06e-d50a-4c11-bcbd-96749f8b6fb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
