<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_(sec)_next</name>
   <tag></tag>
   <elementGuidId>f40925ad-8a23-4e53-9715-91fa8e5c6d0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='If_10']/ul/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ce0ac94d-58d5-4198-87c8-acba61b5e489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c81c7075-018a-4937-93de-8127c8eecce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>next</value>
      <webElementGuid>e5a042be-867a-4f10-8143-89ff9d39c5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;If_10&quot;)/ul[@class=&quot;nums l&quot;]/li[6]/a[@class=&quot;next&quot;]</value>
      <webElementGuid>6aa88e09-3166-4828-b735-b3ba1ab6bed5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='If_10']/ul/li[6]/a</value>
      <webElementGuid>059da848-c23a-43be-b6dd-673b65775706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[59]</value>
      <webElementGuid>279ef011-3bab-490a-aef3-dbfa18f89cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li[6]/a</value>
      <webElementGuid>f54150cd-e777-4231-91e3-86ffc2b69f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#']</value>
      <webElementGuid>3c53b59a-6d92-48fa-a0d9-0793f0824ec6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
