<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_1_2_3</name>
   <tag></tag>
   <elementGuidId>4965de89-b5ab-4a20-9bec-3b7a52aafe23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tree-options > ul > li:nth-of-type(3) > div > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tree-options-box']/div[2]/ul/li[3]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e46746df-28f0-4427-ae13-191d1154a034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tree-options-box&quot;)/div[@class=&quot;tree-options&quot;]/ul[1]/li[3]/div[1]/label[1]</value>
      <webElementGuid>3e059710-9e3d-45b4-8613-01d108eb4339</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tree-options-box']/div[2]/ul/li[3]/div/label</value>
      <webElementGuid>a8c019a3-8754-41d0-90d3-f4ebb7802f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jpn - 日文'])[1]/following::label[1]</value>
      <webElementGuid>15631411-5d1f-47ae-983e-bc5828740085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eng - 英文'])[1]/following::label[2]</value>
      <webElementGuid>e115cd44-29f2-438e-8fb2-d35c0ede9d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kor - 韓文'])[1]/preceding::label[1]</value>
      <webElementGuid>e19d45bc-80ea-46ed-85a8-456af697a398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fre - 法文'])[1]/preceding::label[2]</value>
      <webElementGuid>fcfd24f5-4d79-4e1e-9f84-5defcfc27bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]/div/label</value>
      <webElementGuid>5c3cf575-51df-4c0e-a4aa-92e1674b8f08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
