<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>baad1a1a-9ed2-432b-84fd-bdf0c0e2aa94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='jumpPage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jumpPage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9ae11f97-1a52-4633-809e-c15dc745e595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jumpPage</value>
      <webElementGuid>7daeb96e-b910-4cc0-ab38-a54ae25add82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/HoldClosedList,jumpPage.sdirect?sp=2&amp;updateParts=results&amp;updateParts=nrResults</value>
      <webElementGuid>2c82d147-cb92-4fd8-9a90-f0a147fbf04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return tapestry.linkOnClick(this.href,'jumpPage', false)</value>
      <webElementGuid>4aba085f-85c3-4ac5-91c3-206a2fc4df51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										2				         
									</value>
      <webElementGuid>384a9095-e2f4-46f1-8a80-bf0c0a99cced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jumpPage&quot;)</value>
      <webElementGuid>f59e4f4e-7aeb-4fee-99c2-b2c78909c324</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='jumpPage']</value>
      <webElementGuid>17851871-ffa5-4edf-99e3-a621bf2f0a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='For_13']/li/a</value>
      <webElementGuid>a426042e-12c0-4358-a049-b0acc5420299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2')]</value>
      <webElementGuid>a5ecad95-dae5-49f2-ab8e-936af4f91fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='交易結束日期'])[2]/following::a[5]</value>
      <webElementGuid>dc6a3323-034d-4bb5-b6da-ff85a1d17ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='序號'])[1]/preceding::a[6]</value>
      <webElementGuid>15218744-ec6e-4a9b-93a8-5f3b197cd05c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='預約待取序號'])[2]/preceding::a[6]</value>
      <webElementGuid>cad6bb8a-01c0-4d6c-add8-9d233e3f8ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2']/parent::*</value>
      <webElementGuid>bd3c1cd4-217a-4499-a120-9ebbdea6d5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/HoldClosedList,jumpPage.sdirect?sp=2&amp;updateParts=results&amp;updateParts=nrResults')]</value>
      <webElementGuid>9faa9f1e-491a-43ce-a756-f92795765dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/li/a</value>
      <webElementGuid>a5d223d4-ec71-472f-b2aa-901d01fab40d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'jumpPage' and @href = '/inspireapp/HoldClosedList,jumpPage.sdirect?sp=2&amp;updateParts=results&amp;updateParts=nrResults' and (text() = '
										2				         
									' or . = '
										2				         
									')]</value>
      <webElementGuid>e474cce0-83c2-40d0-991e-8ef6049f92d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
