<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__cardNumberField</name>
   <tag></tag>
   <elementGuidId>9111f124-299c-4262-a7fa-9757aa483699</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cardNumberField']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cardNumberField</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7af01fc8-418b-4db0-add3-1da6348540ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c5e0c206-f067-40bd-b325-0fcaf05aae2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardNumberField</value>
      <webElementGuid>97ad565a-b065-4fdf-89d0-d22e2ec0d979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardNumberField</value>
      <webElementGuid>31757466-7b86-4820-9078-d731db1f7428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>fda4cd00-865a-4a5f-97b9-4c081f964258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>OFF</value>
      <webElementGuid>f9615f7d-e720-4bd4-9292-9fe9018f1551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardNumberField&quot;)</value>
      <webElementGuid>8ada9a84-907e-419f-ac62-dfa7baa681a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cardNumberField']</value>
      <webElementGuid>60fa2cc9-c9ff-4dee-8102-db6f11d1d8b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>3234f396-e25f-4cf9-9503-92bcb4ee4981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>38a318b6-cb9f-4714-a49a-0cba533921e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'cardNumberField' and @id = 'cardNumberField']</value>
      <webElementGuid>a276b16d-2ebf-46a0-8506-9d7bc61a1ee2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
