<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>f19e30aa-684d-4f49-a7d1-ef2f693b9a8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.main_nav_ico17</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/ul/li[11]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9fc2374b-f3dd-4f1e-9f41-a1b5e0aeb405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>6b4502c9-54e9-4671-bb8c-ccab58381b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main_nav_ico17 </value>
      <webElementGuid>d91c5454-7b13-4e74-ab85-7bf3c0b766b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 統計 </value>
      <webElementGuid>ccc611de-b707-44fc-9037-3ad8da5d9f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/ul[1]/li[11]/a[@class=&quot;main_nav_ico17&quot;]</value>
      <webElementGuid>00dd41f6-50d1-409b-86ac-ccc50410d70a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/ul/li[11]/a</value>
      <webElementGuid>b2990ef0-3576-4f37-9f79-13a41c994536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'統計')]</value>
      <webElementGuid>94dc1d8e-406d-4a75-9d12-2b9936f334e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='管理'])[1]/following::a[1]</value>
      <webElementGuid>7bbb3fdf-783b-4141-ba9d-da3fb45547cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='學科服務'])[1]/following::a[2]</value>
      <webElementGuid>6278fe97-d1c3-4789-857f-49c07ad558bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='清單'])[1]/preceding::a[1]</value>
      <webElementGuid>19346796-7c3e-4803-a7eb-ccf070689963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portal'])[1]/preceding::a[2]</value>
      <webElementGuid>32beb68d-0793-40c8-b5bb-0515ab369898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='統計']/parent::*</value>
      <webElementGuid>1bf98a8e-9167-43b9-9c1d-2910f2691bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[13]</value>
      <webElementGuid>1245d590-e658-4dc0-bade-0c3dd6e0fd11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/a</value>
      <webElementGuid>fb477d63-d5ea-43ec-9197-a4d94dcabebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = ' 統計 ' or . = ' 統計 ')]</value>
      <webElementGuid>cbcb8c6e-5463-40bf-848a-5cebc1e89fcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
