<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__field4</name>
   <tag></tag>
   <elementGuidId>3f90ffb1-502d-42dc-a090-1cf3267c7f4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#field4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5929ce13-003e-4b3b-b125-1bcb7cc135a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a4fa4aac-4a81-45ec-8b14-8caea5532f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>84545f12-460f-4d08-8705-d52be9977124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field4</value>
      <webElementGuid>92d4542b-9be4-4e67-b036-7e5d0a45d229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field4</value>
      <webElementGuid>a504c97e-311d-41e5-9746-bd3fbd3f1aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_mare</value>
      <webElementGuid>f09df75c-34fc-449b-9e20-aeffb9f553fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>VirtualKeyboard.attachInput(this); diacriticInsert(this);</value>
      <webElementGuid>6375538c-bf38-4c3e-9bb4-478e326f64d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field4&quot;)</value>
      <webElementGuid>a766edce-c961-4fe2-9586-d276de825d9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field4']</value>
      <webElementGuid>0093551d-b1bc-4fe2-839a-b0ac46bd53af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='inputField4']/nobr/input</value>
      <webElementGuid>d206d692-92eb-45e8-b309-25a3b6955f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[6]/span[2]/nobr/input</value>
      <webElementGuid>6b0b7463-a069-4f81-b865-939f113e9b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field4' and @name = 'field4']</value>
      <webElementGuid>3729cc53-f509-4333-b083-2887b65d8e2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
