<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_()()</name>
   <tag></tag>
   <elementGuidId>30028705-9145-4304-be23-ed6db87c3f84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(21) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu2']/ul[11]/li[4]/ul/li[21]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eca5bd1c-993d-4998-90ae-d72852f4e5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/UnitLoan.page?init=1</value>
      <webElementGuid>c4f201f1-12d8-4358-910e-3af663d3eea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>單位(個人)保管圖書(非書)數量明細</value>
      <webElementGuid>39a3dcf7-ddc5-417b-9157-2dc7e37798c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2&quot;)/ul[@class=&quot;sub_nav_ul&quot;]/li[@class=&quot;current&quot;]/ul[@class=&quot;ssub_nav_ul&quot;]/li[21]/a[1]</value>
      <webElementGuid>774cd8e8-70f8-4d17-9635-2387d91be272</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2']/ul[11]/li[4]/ul/li[21]/a</value>
      <webElementGuid>a713dbad-4993-429c-89a7-889a70e67344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'單位(個人)保管圖書(非書)數量明細')]</value>
      <webElementGuid>c7dd8648-9550-415a-8e25-9b756a22ed04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='館員流通量統計'])[1]/following::a[1]</value>
      <webElementGuid>ecd1a133-8981-43ff-933d-739933b0cd33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='資料類型流通統計'])[1]/following::a[2]</value>
      <webElementGuid>bdd057fe-e2cc-45a9-addf-6270fc8b76ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='館際互借代還統計-本館館藏'])[1]/preceding::a[1]</value>
      <webElementGuid>fe7a2769-a397-4789-adbd-a757f5e7e71b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='館際互借代還統計-他館館藏'])[1]/preceding::a[2]</value>
      <webElementGuid>012ae658-ef1d-4a8a-989f-f67653fda6ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='單位(個人)保管圖書(非書)數量明細']/parent::*</value>
      <webElementGuid>c849d514-8b76-4279-9048-c6ee88388239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/UnitLoan.page?init=1')]</value>
      <webElementGuid>5b32b2f4-5425-468b-a728-0ad8153a8cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[21]/a</value>
      <webElementGuid>9e9b1e31-5594-4216-b669-357fbd15e499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/UnitLoan.page?init=1' and (text() = '單位(個人)保管圖書(非書)數量明細' or . = '單位(個人)保管圖書(非書)數量明細')]</value>
      <webElementGuid>57115460-11d0-415d-aad0-01b288a9b03d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
