<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_3</name>
   <tag></tag>
   <elementGuidId>0b6f4c5b-65e8-41c3-8ad7-fff2010ec8ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pageChanger_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pageChanger_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>51de9cae-1cad-4297-a49a-4040f7e9a388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pageChanger_0</value>
      <webElementGuid>f076dedd-ae76-4bf6-a5d0-a949ee92e1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/MaintainSingle,searchComponent.$search$PaginateComponent.pageChanger.sdirect?sp=3&amp;sp=10&amp;sp=7&amp;updateParts=results&amp;updateParts=nrResults&amp;updateParts=autoRefreshZone</value>
      <webElementGuid>b1247c13-6ea8-4200-873f-27fd733ef071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return tapestry.linkOnClick(this.href,'pageChanger_0', false)</value>
      <webElementGuid>f84950ce-a65d-4e2a-a16b-3e3f10332901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
									     3
									   </value>
      <webElementGuid>c0d6e5e6-383b-48c8-9cb2-3ca9ea02002c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageChanger_0&quot;)</value>
      <webElementGuid>3138c98e-8f04-4c5f-90c7-6d87c110b9d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pageChanger_0']</value>
      <webElementGuid>af0a8c94-8bd2-4ab8-9abe-dfa4134bceca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nrResults']/ul/li[5]/a[3]</value>
      <webElementGuid>e62c0fff-1d05-45ce-9fdf-d2540987f282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'3')])[2]</value>
      <webElementGuid>faebb953-e50f-4913-a1c7-71a1c6511901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='s'])[1]/following::a[5]</value>
      <webElementGuid>09787199-04e0-4a89-899a-01bad6ca3e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='筆'])[1]/following::a[5]</value>
      <webElementGuid>515ff93a-92c4-4d22-ba20-070eb815664e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='...'])[1]/preceding::a[3]</value>
      <webElementGuid>a3fe2ce5-4c06-4df6-8b4f-8ccc97ce6132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3']/parent::*</value>
      <webElementGuid>310cfe7e-f89b-494d-a34f-0c94795f39db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/MaintainSingle,searchComponent.$search$PaginateComponent.pageChanger.sdirect?sp=3&amp;sp=10&amp;sp=7&amp;updateParts=results&amp;updateParts=nrResults&amp;updateParts=autoRefreshZone')]</value>
      <webElementGuid>eac36d0b-bd11-49d4-baa3-d5a634857b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a[3]</value>
      <webElementGuid>76e92879-4279-4579-994f-cf5b516e846a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pageChanger_0' and @href = '/inspireapp/MaintainSingle,searchComponent.$search$PaginateComponent.pageChanger.sdirect?sp=3&amp;sp=10&amp;sp=7&amp;updateParts=results&amp;updateParts=nrResults&amp;updateParts=autoRefreshZone' and (text() = '
									     3
									   ' or . = '
									     3
									   ')]</value>
      <webElementGuid>3b3b0cf9-437f-4a9d-9ce7-c47d666f9c4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
