<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>6beca81e-6ae3-47b2-98dc-a8a2beda61c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7c8031f0-be33-4120-a258-7927b748e96a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_1</value>
      <webElementGuid>155bd28e-6122-43f6-a847-a8dae5113529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttons</value>
      <webElementGuid>43b4beb6-8299-4976-94b5-0c1d875a1460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/circulation/exttransit/TransitItemsToBeReceived,searchComponent.$DirectLink.sdirect?updateParts=results&amp;updateParts=nrResults&amp;updateParts=autoRefreshZone&amp;updateParts=inputField5</value>
      <webElementGuid>9cda8fef-bb72-4482-86c0-c8fdaf4f565a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return tapestry.linkOnClick(this.href,'DirectLink_1', false)</value>
      <webElementGuid>25f08723-b5d9-47e5-a14d-00db62c2097d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>清除</value>
      <webElementGuid>b330071b-2477-421f-9194-251d9b8a74c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_1&quot;)</value>
      <webElementGuid>e0d04065-d9d9-4ac0-8bf6-118aa40d19e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_1']</value>
      <webElementGuid>a4e49ec8-5164-4d6e-af46-fd8f7ea2f7c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='filters']/tbody/tr/td[4]/a</value>
      <webElementGuid>cc738b7a-c046-4934-8a74-82e1b32b5009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'清除')]</value>
      <webElementGuid>e8696ee2-d550-49b6-be3f-829748778577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='條碼號:'])[1]/following::a[1]</value>
      <webElementGuid>f4ceb0ee-9390-4ad1-8b1a-68d725f0ce27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='館藏流通類別:'])[1]/following::a[1]</value>
      <webElementGuid>ee9647f7-c36a-4a8c-84cc-cf5308f4576b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='排序條件:'])[1]/preceding::a[1]</value>
      <webElementGuid>87b3cd72-9780-492e-ac7a-8f24e1ed47bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='清除']/parent::*</value>
      <webElementGuid>7439c6ec-f015-4208-bfcd-109bc3501e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/circulation/exttransit/TransitItemsToBeReceived,searchComponent.$DirectLink.sdirect?updateParts=results&amp;updateParts=nrResults&amp;updateParts=autoRefreshZone&amp;updateParts=inputField5')]</value>
      <webElementGuid>ce2b259a-c43f-42d7-ba83-74052b2c03a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/a</value>
      <webElementGuid>e6ca6360-1adc-4cf7-b2e3-9f6db1daaa8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_1' and @href = '/inspireapp/circulation/exttransit/TransitItemsToBeReceived,searchComponent.$DirectLink.sdirect?updateParts=results&amp;updateParts=nrResults&amp;updateParts=autoRefreshZone&amp;updateParts=inputField5' and (text() = '清除' or . = '清除')]</value>
      <webElementGuid>58659190-3d69-469c-b6f2-b8e3fa03efaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
