<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__formSubmitSearch</name>
   <tag></tag>
   <elementGuidId>77648dad-fe28-4daa-8c2e-b927b9f545bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formSubmitSearch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formSubmitSearch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6871cb35-f5a3-4e79-a459-7e8b890ac494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7f75b07e-35d0-4fb5-99b0-7cc990069e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formSubmitSearch</value>
      <webElementGuid>8b16b88a-1916-478b-8731-cf07d1a304ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formSubmitSearch</value>
      <webElementGuid>da1f3830-f740-40c4-94fc-00a0c6c9ea71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>查詢</value>
      <webElementGuid>241496bd-2185-4e1e-83f6-49897d88f3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>b3cd05c1-1f41-4d21-89be-d2132fa82bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttons buttons_work</value>
      <webElementGuid>a479c446-e066-4d50-a12b-8db80a1591a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSubmitSearch&quot;)</value>
      <webElementGuid>13258387-13e6-44e5-a8f0-2c85f596df07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formSubmitSearch']</value>
      <webElementGuid>90274a2a-a78f-45cc-abd8-378f8ba750f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HiddenSearch']/div/div[2]/p/input</value>
      <webElementGuid>6994a644-45d8-40a0-bce9-db99b24952bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>a5518035-8d82-4c34-b8ae-0870bdf8c036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'formSubmitSearch' and @id = 'formSubmitSearch']</value>
      <webElementGuid>54a305c8-ab22-4f9a-b8ca-2d870561ccbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
