<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__sd3</name>
   <tag></tag>
   <elementGuidId>2d193f4f-ab43-43e7-b1c5-3082695e143b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sd3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sd3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a25b6f73-7e2d-4d07-9380-ab72129abd8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55628695-e164-4fe0-bb9e-c950bc67b79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sd3</value>
      <webElementGuid>7e41c776-7e43-4bf5-9121-d571011d97ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>yyyy/MM/dd</value>
      <webElementGuid>9b67261a-2995-4f64-a303-8716de2389b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sd3</value>
      <webElementGuid>bc64ff69-625a-4bc6-8bbd-0b742a16c35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>format</name>
      <type>Main</type>
      <value>java.text.SimpleDateFormat@f9e3bac0</value>
      <webElementGuid>93c9e11c-cc40-4dc0-b2c3-eb3449155591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>fe508923-cda7-4309-be41-8f8a4e8d2433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sd3&quot;)</value>
      <webElementGuid>ec1134e6-66af-448c-a7ab-b80313a7c68b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sd3']</value>
      <webElementGuid>f0461846-e38b-4bca-85bb-dfb845568bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='inputField3']/nobr/input</value>
      <webElementGuid>dd810ff7-5c18-4ef7-af07-b5be79ee0eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/span[2]/nobr/input</value>
      <webElementGuid>48af349f-f166-40c3-be43-f42cef8ccd12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'sd3' and @title = 'yyyy/MM/dd' and @id = 'sd3']</value>
      <webElementGuid>723eb209-f85f-426e-a541-aedb4457e213</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
