<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__RadioGroup_1_1</name>
   <tag></tag>
   <elementGuidId>6f983412-877a-4e51-b02a-21e8ca7193a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RadioGroup_11']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#RadioGroup_11</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95516ba8-f258-4fc0-acee-d73689514312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>17e86a56-5ab8-41fa-8d04-99965d9428d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RadioGroup_1</value>
      <webElementGuid>2c5da5a7-62c3-45fe-9a35-e78e10207593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RadioGroup_11</value>
      <webElementGuid>33c4cb2f-6cad-4992-b542-5843c6a6cf1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>7dd26b4f-bef2-4b2a-9db0-abdb04014b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>373a1c5c-55df-4c6d-ad39-b8e77bc196ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>tapestry.byId('RadioGroup_1').onChange(1);</value>
      <webElementGuid>2b8c2ec9-6cda-433d-8700-bc727fbebe99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RadioGroup_11&quot;)</value>
      <webElementGuid>467a5082-8c99-43dd-8e00-676cc656dabe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RadioGroup_11']</value>
      <webElementGuid>6a13759a-a639-4610-b29d-5398c3269ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='RadioGroup_1']/input[2]</value>
      <webElementGuid>f33c3fee-7a61-432a-b4b2-a3aac16a4bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/span/input[2]</value>
      <webElementGuid>7aa7b2c5-3016-4a4e-a236-a966114ab0ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'RadioGroup_1' and @id = 'RadioGroup_11' and @checked = 'checked']</value>
      <webElementGuid>c7796b4a-5163-4bed-a766-01d41359430e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
