<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option__1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>d3fb310e-b1c5-4525-ae78-82ac33bfa94b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//option[@value='2'])[27]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FieldMode_0 > option[value=&quot;2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>86008421-51a6-4ad3-ad2b-bab7e6af6db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1e1cb05f-11ae-4da5-8095-611f43bcdd2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>分類號</value>
      <webElementGuid>be36894c-e08b-4a61-9d85-89c297878619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FieldMode_0&quot;)/option[2]</value>
      <webElementGuid>4deb3cb8-8d45-4f5d-80b9-eb3173ed8cb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//option[@value='2'])[27]</value>
      <webElementGuid>0db08ff9-a13a-40d1-8aed-550578aec67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//select[@id='FieldMode_0']/option[2]</value>
      <webElementGuid>e7da198b-818a-4aab-a8fc-61c48e2e7554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='列印欄位'])[1]/following::option[11]</value>
      <webElementGuid>b6353873-6122-4b20-83e1-77920440e13f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='不印欄位'])[1]/following::option[11]</value>
      <webElementGuid>acca18f3-35d5-425c-af8c-cbc40c3703bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='複製'])[1]/preceding::option[6]</value>
      <webElementGuid>29b175d5-4fc4-4fa2-8f02-6e6f41739bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='修改/儲存'])[1]/preceding::option[6]</value>
      <webElementGuid>7fa9a92d-26e7-4f88-96af-9c4db27747f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr[2]/td[2]/select/option[2]</value>
      <webElementGuid>0cc8d031-013f-4834-a59e-8c3c72177099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//option[(text() = '分類號' or . = '分類號')]</value>
      <webElementGuid>2a3e43cd-db35-45ff-af74-1b4581f2813d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
