<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_</name>
   <tag></tag>
   <elementGuidId>f51c8639-8f45-4efc-805c-4f5dd7695792</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//font[@id='abcd']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#abcd > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>1154e08a-86a7-4813-a033-ae3ce1f229b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							儲存成功
						</value>
      <webElementGuid>b144050a-5d9e-4431-b995-4d19c054dd31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;abcd&quot;)/p[1]</value>
      <webElementGuid>d1cf1ef1-c02b-434b-be1c-052fe0a184af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//font[@id='abcd']/p</value>
      <webElementGuid>c8ed6d0e-ba4a-41a0-8bc1-e1579c01d8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='列印欄位'])[1]/following::p[4]</value>
      <webElementGuid>06fd70ab-fd22-498f-8a6e-69fccae973ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='不印欄位'])[1]/following::p[4]</value>
      <webElementGuid>7c11fb89-3438-4806-8ebb-b3f3d1c44c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='複製'])[1]/preceding::p[1]</value>
      <webElementGuid>51e0a3f6-9869-48e2-ab0b-b666d24088c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='修改/儲存'])[1]/preceding::p[1]</value>
      <webElementGuid>4df5d32f-0514-4e35-83e8-b5f4665cb447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='儲存成功']/parent::*</value>
      <webElementGuid>b567c3e4-ced9-4dbb-8b52-95f0b54c4e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/font/p</value>
      <webElementGuid>0e99380c-82b6-4c89-9022-194f221d6fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '
							儲存成功
						' or . = '
							儲存成功
						')]</value>
      <webElementGuid>9c12c524-dcb1-4698-a1df-de92537ad89a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
