<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_</name>
   <tag></tag>
   <elementGuidId>46563e34-b16e-4b01-903a-fa0e7de7cce1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='LbaleParameterFrom']/table/tbody/tr[5]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>25af304c-4561-4109-a6cc-0b3d3f20dc38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>直式橫式:</value>
      <webElementGuid>337293dd-bb19-42a5-8bb1-b87efda5ce63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LbaleParameterFrom&quot;)/table[1]/tbody[1]/tr[5]/td[1]</value>
      <webElementGuid>bb1df2ab-03f8-4a05-8f2a-046473c7bddf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='LbaleParameterFrom']/table/tbody/tr[5]/td</value>
      <webElementGuid>fb9512c2-ae60-47ef-9c59-0ab8d031430c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='樣式:'])[1]/following::td[2]</value>
      <webElementGuid>1d0f15bc-8403-4a99-9c36-b2ce0ce36d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='紙張大小:'])[1]/following::td[4]</value>
      <webElementGuid>f1d65914-05b3-4e49-be67-9e2951fff5fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='字型大小:'])[1]/preceding::td[2]</value>
      <webElementGuid>4853e609-ab94-406a-be24-3c90aee84911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='上邊界:'])[1]/preceding::td[4]</value>
      <webElementGuid>9989c053-957e-49d8-8bb2-7b93c5aa601c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='直式橫式:']/parent::*</value>
      <webElementGuid>8bdf21b8-3435-49c7-8e6d-ba85cecb1464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/form/table/tbody/tr[5]/td</value>
      <webElementGuid>bac73160-03dc-4b18-b4ee-c20f57dcd54b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '直式橫式:' or . = '直式橫式:')]</value>
      <webElementGuid>58c9a428-a040-49de-826b-8d17a2fee855</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
