<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td__1_2_3_4_5_6_7_8_9_10_11</name>
   <tag></tag>
   <elementGuidId>47e6588a-2664-43fd-ba92-d7fade258692</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='LbaleParameterFrom']/table/tbody/tr[4]/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>3d9ec897-a694-4487-93b5-b9fe8cb04285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>樣式:</value>
      <webElementGuid>d29d27e1-f7d3-4b2a-bdff-81be3cf7b6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LbaleParameterFrom&quot;)/table[1]/tbody[1]/tr[4]/td[3]</value>
      <webElementGuid>85db7c6e-5f95-4dcd-b646-d65ffb60e676</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='LbaleParameterFrom']/table/tbody/tr[4]/td[3]</value>
      <webElementGuid>ef444609-43fd-4e80-a1e0-a24cf75a30a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='紙張大小:'])[1]/following::td[2]</value>
      <webElementGuid>a02fe1e0-c789-4812-807d-0072cdfcc5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='字型:'])[1]/following::td[4]</value>
      <webElementGuid>7f9c41b0-9f83-421d-b002-495cf4ee3178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='直式橫式:'])[1]/preceding::td[2]</value>
      <webElementGuid>89bb769a-91a3-495b-ab0c-1fe10bda5741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='字型大小:'])[1]/preceding::td[4]</value>
      <webElementGuid>af5fb2c2-803b-49ef-b237-ae5ad754a39b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='樣式:']/parent::*</value>
      <webElementGuid>ca9a3ad8-cb79-4aa4-b042-acccb4b88682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/form/table/tbody/tr[4]/td[3]</value>
      <webElementGuid>8435f718-c4f7-4f82-95ad-e2412808bc65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '樣式:' or . = '樣式:')]</value>
      <webElementGuid>86872665-c3dc-4756-87a5-aa1f877fa1b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
