<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_()()()()_1</name>
   <tag></tag>
   <elementGuidId>e1113a22-5b5f-4213-aa3a-c46012e0fedf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comparator4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='comparator4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6ecc24a8-cec0-4090-b3fe-6fc0edbd4a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>comparator4</value>
      <webElementGuid>2671768b-16af-4ecd-9e07-53300dda4a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comparator4</value>
      <webElementGuid>b3ddf67d-b084-4813-8476-b8711d26e10c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
起始以
包含
等於(=)
大於(>=)
小於(&lt;=)
不等於(≠)
</value>
      <webElementGuid>abfcf023-91be-4942-a6e5-9ff6d748a4ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comparator4&quot;)</value>
      <webElementGuid>72503978-0653-40d7-a83c-1a121146a848</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='comparator4']</value>
      <webElementGuid>525c2438-2b81-4010-b470-7d770d3202e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='If_17']/select[3]</value>
      <webElementGuid>04df63e8-0ecc-4230-8bf6-363e53a57e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='鍾佩恩'])[1]/following::select[9]</value>
      <webElementGuid>3fcd1f38-2b33-4194-b311-cdb9532c9ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='鍾佩君'])[1]/following::select[9]</value>
      <webElementGuid>2cdefb29-91f1-48f0-944a-1774c1657473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='限制條件'])[1]/preceding::select[1]</value>
      <webElementGuid>4e2f1f33-8038-4b3f-a4fc-2488d390aed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='reset'])[1]/preceding::select[1]</value>
      <webElementGuid>92a70a44-7403-46c2-83b4-be5a45cb0c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[7]/select[3]</value>
      <webElementGuid>c06a1c60-b748-449d-9375-8947c37a7909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'comparator4' and @id = 'comparator4' and (text() = '
起始以
包含
等於(=)
大於(>=)
小於(&lt;=)
不等於(≠)
' or . = '
起始以
包含
等於(=)
大於(>=)
小於(&lt;=)
不等於(≠)
')]</value>
      <webElementGuid>2d4cf08d-b1c4-47e3-b47e-cc0ce0a388c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
