<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b__1</name>
   <tag></tag>
   <elementGuidId>661892b6-cd66-4654-aac5-e775ad3d460b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nobr > font > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='If_31']/nobr/font/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>0a1373c0-9d76-476b-b0ca-da1f03c2cdc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>瀏覽條件:</value>
      <webElementGuid>0769ecc0-fb4d-48ee-b0bb-7924970a872b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;If_31&quot;)/nobr[1]/font[1]/b[1]</value>
      <webElementGuid>49e8d86d-b068-43bf-a8dd-f744e923f054</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='If_31']/nobr/font/b</value>
      <webElementGuid>31ea71b2-7c04-443e-95f1-d300b5a816c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='查詢條件'])[1]/following::b[1]</value>
      <webElementGuid>a3bd3c9e-008b-4396-8275-f79fad175722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='排序條件 :'])[1]/preceding::b[2]</value>
      <webElementGuid>a085fa92-4ccb-47ba-8a34-89b7f45af49b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='瀏覽條件:']/parent::*</value>
      <webElementGuid>f1fdd023-9e59-4384-adf1-ae913668bcf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nobr/font/b</value>
      <webElementGuid>bb08f539-4c4e-43a3-af8a-d3b7b802025b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = '瀏覽條件:' or . = '瀏覽條件:')]</value>
      <webElementGuid>c544e291-f18d-4d66-bda1-26cc7d265a79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
