<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td__1_2</name>
   <tag></tag>
   <elementGuidId>efdce3ae-8850-45c8-91ba-880751b9fabe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='paginateList']/div[2]/table/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a86dbabf-301f-46d4-b94f-e8568b94e94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			顯示順序
			</value>
      <webElementGuid>135bfe27-f340-429e-9e49-aff824b02c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paginateList&quot;)/div[2]/table[@class=&quot;search_list&quot;]/tbody[1]/tr[@class=&quot;search_list_c&quot;]/td[3]</value>
      <webElementGuid>dcf95e28-0458-4518-946a-40f036fd9b8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paginateList']/div[2]/table/tbody/tr/td[3]</value>
      <webElementGuid>28f10b81-115c-4b10-9ffe-a4bb85514a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='值'])[1]/following::td[1]</value>
      <webElementGuid>7b97a94a-29cf-48b3-a47d-8902b17bcdb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='代碼'])[1]/following::td[2]</value>
      <webElementGuid>0e1b3d94-8f8f-422f-ad13-7818b09ce68f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='是否啟用'])[1]/preceding::td[1]</value>
      <webElementGuid>41b59690-52ec-4d5f-af82-d01409e71d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MaxCashTransferSuspendRights'])[1]/preceding::td[3]</value>
      <webElementGuid>25e914af-9f0d-487d-a5c7-6f51458b40f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='顯示順序']/parent::*</value>
      <webElementGuid>dc58423f-522e-4123-8f4a-8f3587482445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>2668206b-a247-4bad-866d-4983c38784e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
			顯示順序
			' or . = '
			顯示順序
			')]</value>
      <webElementGuid>838e16af-0d03-47c8-ad79-8c0c4a8d436a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
