<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>4a60a74a-ab2e-41f9-ac05-39fc41f3b793</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='LinkSubmit_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LinkSubmit_4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>99710902-e9ff-4b64-a479-39882bddd713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/circulation/pages/ForceMajor,searchForm.sdirect?updateParts=itemSearchResult</value>
      <webElementGuid>474e337f-6f28-4aae-ad92-c560486ee935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>tapestry.form.submit('searchForm', 'LinkSubmit_4',{async:true,json:false,url:this.href}); return false;</value>
      <webElementGuid>0fee8376-aa11-4484-96c4-f1925f277680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LinkSubmit_4</value>
      <webElementGuid>a21c2ab6-402b-4701-af81-a557442c9bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>butonsub</value>
      <webElementGuid>8b8d7cd4-5598-4778-916c-654daa0420b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      									查詢</value>
      <webElementGuid>3ededb4e-a7fb-488a-a207-381d6c69cf4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LinkSubmit_4&quot;)</value>
      <webElementGuid>51237e72-8d23-4782-9f24-1bc5fd734955</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='LinkSubmit_4']</value>
      <webElementGuid>cff13cc0-3c22-407a-a2c7-c48d2e091663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='itemSearchModelDiv']/table/tbody/tr[7]/td[2]/table/tbody/tr/td[2]/a</value>
      <webElementGuid>a673f66d-c795-4707-be2d-09126ea25f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'查詢')])[14]</value>
      <webElementGuid>2b35dd01-90f9-4bb7-9954-a5120fd1e198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::a[1]</value>
      <webElementGuid>d25c7784-c4a8-4c92-8238-f61cf3256c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::a[1]</value>
      <webElementGuid>ea3653e8-a210-4ebd-ac9f-d1dad3b9790f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='清除'])[1]/preceding::a[1]</value>
      <webElementGuid>dcf4a75b-e529-4cda-8163-41ea2aa1abcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/circulation/pages/ForceMajor,searchForm.sdirect?updateParts=itemSearchResult')]</value>
      <webElementGuid>bad85e9f-01c7-45ba-b19e-40412d6b9946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]/a</value>
      <webElementGuid>809f6956-d625-4603-a209-72c2d178c415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/circulation/pages/ForceMajor,searchForm.sdirect?updateParts=itemSearchResult' and @id = 'LinkSubmit_4' and (text() = '
      									查詢' or . = '
      									查詢')]</value>
      <webElementGuid>630f1df9-156d-412a-ae5e-728294eaa8a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
