<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3</name>
   <tag></tag>
   <elementGuidId>22bf99a3-4713-4adb-b56d-ba2c6477f43b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>464c1fd6-ad17-401b-b825-bb249a1810e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_2</value>
      <webElementGuid>d887139b-0731-4096-a099-b51cc0c25ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttons</value>
      <webElementGuid>79ad3a38-f5a5-4df4-a289-a47d749ffbf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return createPopEdit(this.href);</value>
      <webElementGuid>7afe90af-60e4-4695-8628-e48c1e3c01d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/MaintainSingle,searchComponent.$DirectLink_1.sdirect</value>
      <webElementGuid>1e440def-dd82-4f67-9797-6e94986c2a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
							新增 </value>
      <webElementGuid>893aa509-2e93-4185-aaca-cc1f79b52895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_2&quot;)</value>
      <webElementGuid>e1f29fe4-97b3-4b73-bb78-bcf564872806</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_2']</value>
      <webElementGuid>227362c4-198c-4465-9949-2d3f1549c5ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='Body']/div/div/div[2]/div[3]/div[2]/a</value>
      <webElementGuid>94dae652-f0d4-4aa3-88b6-9f10e1d1d440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'新增')])[2]</value>
      <webElementGuid>811ec1f7-92c8-4b1c-a6f3-801e975b18df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='瀏覽'])[1]/following::a[1]</value>
      <webElementGuid>4b951e38-9ff5-41af-b027-db4e6c3dfe8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='查詢'])[2]/following::a[2]</value>
      <webElementGuid>f8140301-12c3-4a8e-80ff-c4d618cd4ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='查詢條件'])[1]/preceding::a[3]</value>
      <webElementGuid>bb4704b4-1513-437f-947e-57eb9474f2e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='限制條件'])[1]/preceding::a[3]</value>
      <webElementGuid>9c2995e9-ab17-49f8-a0d6-493ec83a31fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/MaintainSingle,searchComponent.$DirectLink_1.sdirect')]</value>
      <webElementGuid>c578e2cf-8a09-4606-a903-523855508854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>28ba5c54-fa2e-4594-9816-c50f84a4c734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_2' and @href = '/inspireapp/MaintainSingle,searchComponent.$DirectLink_1.sdirect' and (text() = ' 
							新增 ' or . = ' 
							新增 ')]</value>
      <webElementGuid>32ab1469-f21b-4608-ae88-ee4b9198c84c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
