<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3_4</name>
   <tag></tag>
   <elementGuidId>cdcd242c-d3d7-4c62-813f-77ada0568d90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>50523691-c467-4bf3-bcc4-cdd71e91ac69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_2</value>
      <webElementGuid>596c598a-3898-4b7f-9bae-17772b2b030d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setstytle()</value>
      <webElementGuid>f51ae3c0-0eb6-4e38-91f9-e5f51e36b400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>butonsub</value>
      <webElementGuid>8c12509b-7741-4cfd-ad5d-be98d675cc3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/MonthlyItemIncrementStatsByClass,ReportsStatus.$DirectLink.sdirect?updateParts=ReportStatus</value>
      <webElementGuid>7129363b-3a66-4ddf-af59-de1b80c3c8af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 目前執行的報表</value>
      <webElementGuid>aea84a3b-150d-4c56-a4fc-aa6dde327e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_2&quot;)</value>
      <webElementGuid>37e44641-9901-4a47-a835-d3f905f355f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_2']</value>
      <webElementGuid>2444584c-7282-4f9c-a3ff-325ef2e9539f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='If_5']/div/table/tbody/tr/td/table/tbody/tr/td/a</value>
      <webElementGuid>62d51fb5-3c68-4f5f-8612-066d403acd1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'目前執行的報表')]</value>
      <webElementGuid>82204351-e5e9-4435-8ea8-d6b00f3aa9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='報表狀態'])[2]/following::a[1]</value>
      <webElementGuid>51bdba7c-0d67-4a7e-a614-434d79182077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='報表狀態'])[1]/following::a[1]</value>
      <webElementGuid>5090e04b-7494-49df-9d41-b5b569fd240e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/MonthlyItemIncrementStatsByClass,ReportsStatus.$DirectLink.sdirect?updateParts=ReportStatus')]</value>
      <webElementGuid>f08fb182-0c8f-4468-ac8f-94087ad9b93e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td/a</value>
      <webElementGuid>0e66ec15-e330-40fc-b79c-9fa8ae175782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_2' and @href = '/inspireapp/MonthlyItemIncrementStatsByClass,ReportsStatus.$DirectLink.sdirect?updateParts=ReportStatus' and (text() = ' 目前執行的報表' or . = ' 目前執行的報表')]</value>
      <webElementGuid>21dd50fd-465c-4a00-856f-3b4ec60dbacd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
