<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__formSubmitSearch</name>
   <tag></tag>
   <elementGuidId>69ed7e64-831a-4cb6-bae1-2aa969574656</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formSubmitSearch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formSubmitSearch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bdaba639-67ef-471d-81db-c72c356962df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d34d1468-ef79-4b4a-baa5-3ef8721b9917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formSubmitSearch</value>
      <webElementGuid>876e9325-0276-4131-9668-f48a7a395d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formSubmitSearch</value>
      <webElementGuid>d50f7e5e-cfc1-4ad6-be3d-7f8f7684e01d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>查詢</value>
      <webElementGuid>c59c6598-0752-4614-8739-af2371db5991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttons buttons_work</value>
      <webElementGuid>848ffb59-fc31-42d2-9a76-37bfdcefe1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSubmitSearch&quot;)</value>
      <webElementGuid>89b8a172-4994-4b96-97c4-7e43d6458c2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formSubmitSearch']</value>
      <webElementGuid>c2ec1114-012b-44e3-a3df-6b5d619bdea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HiddenSearch']/div/div[2]/p/input</value>
      <webElementGuid>28ec9d58-0c40-4cc5-8039-beba4f7c6c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>681ed4a3-03d2-45ed-b5cb-102e902e0653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'formSubmitSearch' and @id = 'formSubmitSearch']</value>
      <webElementGuid>e161e87b-f296-454b-b432-f710d4c30ddb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
