<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1</name>
   <tag></tag>
   <elementGuidId>f67268e9-0f82-4d1d-ac3f-def564430008</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu2']/ul/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.sub_nav_ul > li:nth-of-type(5) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cca8957a-e638-4640-9fcc-a81d56d86e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/myaccount/bookmarks?init=1</value>
      <webElementGuid>d6343349-b8ab-40da-99a2-45e390fe81a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>已儲存的記錄</value>
      <webElementGuid>5d31636e-5d06-4059-84cb-0d81cd2635ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2&quot;)/ul[@class=&quot;sub_nav_ul&quot;]/li[5]/a[1]</value>
      <webElementGuid>0578eeef-51c8-4b93-94c3-3b15ca48d413</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2']/ul/li[5]/a</value>
      <webElementGuid>090fd606-7285-4425-b19d-60cb0ea390aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'已儲存的記錄')]</value>
      <webElementGuid>cde39313-7626-4e86-814f-52f81e7f69df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='最近的查詢'])[1]/following::a[1]</value>
      <webElementGuid>c5e9211b-15bd-4e88-8d1f-a18ad2fdd893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FRBR查詢'])[1]/following::a[2]</value>
      <webElementGuid>07a90e12-9977-4dba-880e-1987e461a594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FRBR作品'])[1]/preceding::a[1]</value>
      <webElementGuid>4de89d15-c146-4be8-8ead-930a4e9e51fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='書目記錄維護'])[1]/preceding::a[3]</value>
      <webElementGuid>fe441c31-842a-4483-a02a-8bf275227f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='已儲存的記錄']/parent::*</value>
      <webElementGuid>f31cc7d6-18af-420f-aa69-cec424bee8f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/myaccount/bookmarks?init=1')]</value>
      <webElementGuid>4fbda56e-a2f1-4281-b890-3c03d3e6c9ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[5]/a</value>
      <webElementGuid>12bfb2a3-7460-4c99-9cc9-5992ebe879b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/myaccount/bookmarks?init=1' and (text() = '已儲存的記錄' or . = '已儲存的記錄')]</value>
      <webElementGuid>4c1d05dd-eaee-45b8-ac0b-ebe55fd0e90a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
