<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>c1f6886b-912f-4804-9e5b-7b09e9f13923</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'轉出')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LinkSubmit_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>51430eee-b1c1-4083-9d59-63612c147123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/myaccount/Bookmarks,bookmarkForm.sdirect?updateParts=exportDialog</value>
      <webElementGuid>05067b86-0aaa-49da-a9c2-9fbfe1836693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>tapestry.form.submit('bookmarkForm', 'LinkSubmit_0',{async:true,json:false,url:this.href}); return false;</value>
      <webElementGuid>5d412b70-ac6c-4d12-b63a-f85898b565e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LinkSubmit_0</value>
      <webElementGuid>a9eece72-4ce5-4ee9-b056-ad5a027e64ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>butonsub</value>
      <webElementGuid>861b6d3a-5915-4a09-878f-39aab06ba0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				 轉出 
			</value>
      <webElementGuid>94ba505f-8b80-49f3-8d53-977ff8d5f21c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LinkSubmit_0&quot;)</value>
      <webElementGuid>616d9613-748a-4169-bba5-fe2e81d959c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='LinkSubmit_0']</value>
      <webElementGuid>e39f56e3-cce1-46ec-badb-8524ee231c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='If_242']/a[4]</value>
      <webElementGuid>5c8805d9-e899-468f-8b2e-ae18372656fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'轉出')]</value>
      <webElementGuid>7e88df7f-018c-4a78-bd4e-362e75795707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='轉出'])[1]/preceding::a[1]</value>
      <webElementGuid>8746283a-5205-4713-be4a-dcb4d6523ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/myaccount/Bookmarks,bookmarkForm.sdirect?updateParts=exportDialog')]</value>
      <webElementGuid>97d9cfd4-d5a4-48b7-9d7d-2d6cc29aff50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>87bd5a74-437c-4c4f-940e-4ed200fb3a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/myaccount/Bookmarks,bookmarkForm.sdirect?updateParts=exportDialog' and @id = 'LinkSubmit_0' and (text() = '
				 轉出 
			' or . = '
				 轉出 
			')]</value>
      <webElementGuid>23148c28-438d-435b-9732-327c0fbbb3ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
