<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__elementName</name>
   <tag></tag>
   <elementGuidId>d5a7b13c-31ad-4ae0-867e-ea7f16e06ea3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#elementName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='elementName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc9915d5-3b88-4b3c-a148-5e64fa088aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>381dc078-cf75-4a04-9fa7-213b488f0552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>elementName</value>
      <webElementGuid>5ae4f1e7-3008-4362-b05f-ac67dd89f7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>elementName</value>
      <webElementGuid>0d84065f-122c-4f12-a026-3e16ff8d6598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return runScript(event);</value>
      <webElementGuid>80d9e5aa-ab32-4832-bf4d-4f90a1e5efd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>1755e4b2-6da7-4e63-b7a4-a31b9ed05c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementName&quot;)</value>
      <webElementGuid>f67d5727-d299-4ba7-bb8e-d56e0ded922b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='elementName']</value>
      <webElementGuid>0a37e452-7cb9-4b76-af1b-88dffd8c2232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='If_35']/td[2]/input</value>
      <webElementGuid>8e016cbc-743b-48d4-9c14-417a92032ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>4fa078b8-2e96-4181-a039-965a50a1ee7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'elementName' and @id = 'elementName']</value>
      <webElementGuid>8308a6da-c847-4640-99ff-ab26b44e34e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
