<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td__1_2_3</name>
   <tag></tag>
   <elementGuidId>2755100a-6ba4-483d-bdf8-14169fb9c9ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#If_35 > td.limit_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='If_35']/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>fca15cba-1f9e-47c2-a499-1e54059cf049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>limit_title</value>
      <webElementGuid>a5dfa872-6c88-47ee-9fe0-9d24eaf1dbd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>所系單位:</value>
      <webElementGuid>2a206b5a-f21f-4f03-a0fa-01ae4b193191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;If_35&quot;)/td[@class=&quot;limit_title&quot;]</value>
      <webElementGuid>930af47a-cc7d-48f6-95d8-ad062580d09d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='If_35']/td</value>
      <webElementGuid>85693c36-ac7e-4c80-a13b-e0b967e15185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='讀者其他館別:'])[1]/following::td[2]</value>
      <webElementGuid>589c84f0-767d-4403-b4f2-4207790f43fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='預設所屬圖書館:'])[1]/following::td[4]</value>
      <webElementGuid>44316be5-5668-4836-bf90-866839dafb5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='所系單位'])[1]/preceding::td[2]</value>
      <webElementGuid>8de55e6a-426e-425c-8ada-27a7208afb1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='_New Item'])[1]/preceding::td[2]</value>
      <webElementGuid>bd71d5b3-0f5e-4af5-b63a-90fc04db10a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='所系單位:']/parent::*</value>
      <webElementGuid>a4415b95-eec8-4870-b784-d6cfdc356d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td</value>
      <webElementGuid>df9b2214-ab79-4870-8630-d8e4949ee3d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '所系單位:' or . = '所系單位:')]</value>
      <webElementGuid>db27d140-58dc-4d24-979a-9d312c8c3e3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
