<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__Any_0_1</name>
   <tag></tag>
   <elementGuidId>86bee180-ba58-4c1c-85e6-b0c6d59d6c8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='Any_0_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Any_0_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>25151482-3129-490a-a0fc-c45378b6f0d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/inspireapp/images/ico_add.gif</value>
      <webElementGuid>62336b0f-8c28-4954-b0eb-430c0d680e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dafc2c19-4f14-43cb-b35e-1d0fae6d5484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Any_0_1</value>
      <webElementGuid>5f3d651a-47b5-4ef3-9edc-971f4b056b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Any_0_1&quot;)</value>
      <webElementGuid>f6cf3b26-9a0c-421b-9f0a-238ea022b914</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='Any_0_1']</value>
      <webElementGuid>505a990a-6a82-4b0c-8f8e-0b6538e7329c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='showTreeBtn1_0']/img</value>
      <webElementGuid>8a5fbb90-3567-4c63-9c7b-8c6b1400ccf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/span/a/img</value>
      <webElementGuid>8d1952bb-5111-4abb-ae25-0b6d23d1039b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/inspireapp/images/ico_add.gif' and @id = 'Any_0_1']</value>
      <webElementGuid>b03f49af-2774-45d9-b9ab-719a2873c7f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
