<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_andornot</name>
   <tag></tag>
   <elementGuidId>3040ab3e-e2cf-4a33-bfdc-17e4f7997807</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#boolean2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='boolean2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a92ae60a-758e-4adb-a5a8-82bc4f0d2671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>boolean2</value>
      <webElementGuid>c48a8cdb-8eb7-402d-8746-08b833e87af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boolean2</value>
      <webElementGuid>24cb7814-d05b-44d8-9258-768dd13d4527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
and
or
not
</value>
      <webElementGuid>d64c895b-4414-4f19-b38f-878979599a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boolean2&quot;)</value>
      <webElementGuid>c3e82056-a981-4760-82b5-f31578e3ca83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='boolean2']</value>
      <webElementGuid>aae80393-ef8f-4835-972f-bde7c44a8c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='If_15']/select</value>
      <webElementGuid>a554a006-e662-4881-a293-57964d60eb63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AV'])[1]/following::select[1]</value>
      <webElementGuid>1fb93c4b-3301-4b73-9714-b566105fc5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[1]/following::select[1]</value>
      <webElementGuid>32af53e9-1add-4161-8ff2-b58bc8a7eb83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='瀏覽條件:'])[1]/preceding::select[3]</value>
      <webElementGuid>7ede467e-be7a-4931-9286-70e8999ab7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/select</value>
      <webElementGuid>26405e1f-b9dd-4200-b2a2-0cabb4ebffe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'boolean2' and @id = 'boolean2' and (text() = '
and
or
not
' or . = '
and
or
not
')]</value>
      <webElementGuid>aa88182d-7237-419b-ac82-d18ae19a5453</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
