<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_102050100500</name>
   <tag></tag>
   <elementGuidId>4082a72f-cc7c-4dbe-97f1-49782831aab5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PropertySelection_5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PropertySelection_5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2378a594-6377-4c56-92a1-2f446e93498b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PropertySelection_5</value>
      <webElementGuid>5bb37e85-bddd-4617-a63a-0b6235866daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PropertySelection_5</value>
      <webElementGuid>804b9448-9f7e-4348-9139-c5040c6e91a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>num l</value>
      <webElementGuid>0fd515c4-eec9-4160-9c97-ec3976852d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>tapestry.form.submit('searchForm', 'changePagesize')</value>
      <webElementGuid>9eb51fbc-b3cf-462e-87cd-d4b8286912e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
10
20
50
100
500
</value>
      <webElementGuid>d00dc179-a991-47d2-bda7-c613cbed6f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PropertySelection_5&quot;)</value>
      <webElementGuid>9ef62084-ba22-40d9-983f-f5389b7b329c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PropertySelection_5']</value>
      <webElementGuid>cb1277e7-1973-445c-ae78-c1c4d130bb1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='patronSearchResult']/div/div/select</value>
      <webElementGuid>cdc873b4-5f8b-4c70-b0ea-127cd3c9814f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='排序條件:'])[1]/following::select[3]</value>
      <webElementGuid>19c1d2e7-47f8-41b7-bc1a-987b09c2fe3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='修改+發送通知'])[1]/following::select[3]</value>
      <webElementGuid>45f6ef91-540e-4d2b-bdf1-03764f3b6e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='筆'])[1]/preceding::select[1]</value>
      <webElementGuid>29559faa-8a68-48c2-971a-24f2b21b2ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/select</value>
      <webElementGuid>b50532a0-fdf3-414b-90f9-980336bc528e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'PropertySelection_5' and @id = 'PropertySelection_5' and (text() = '
10
20
50
100
500
' or . = '
10
20
50
100
500
')]</value>
      <webElementGuid>992a0013-3e1b-40e7-bc8c-3554eb8cd1f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
