<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_4</name>
   <tag></tag>
   <elementGuidId>39e002fd-ac2e-4894-ab91-694cdbc501d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='jumpPage_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jumpPage_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f2fe1700-51ec-4145-86b5-cb9e57e16e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jumpPage_1</value>
      <webElementGuid>e0d288b8-2784-4419-8a5b-232d582cee07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/SearchStatisticsReport,jumpPage.sdirect?sp=4&amp;updateParts=results&amp;updateParts=nrResults</value>
      <webElementGuid>e9404ef9-b1ca-4e8c-8796-fe87378fa086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return tapestry.linkOnClick(this.href,'jumpPage_1', false)</value>
      <webElementGuid>0bf064c7-3623-471c-8f8d-f831fed74fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>119a65ee-3591-4538-b1b4-b6dd01ecec57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jumpPage_1&quot;)</value>
      <webElementGuid>a886244b-c822-4f88-911d-4ac49058d342</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='jumpPage_1']</value>
      <webElementGuid>e219b172-7a18-4924-89e2-8c19166ddf35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='For_3']/li/a</value>
      <webElementGuid>d82e7130-daf7-4513-b874-5acf0401942b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'4')]</value>
      <webElementGuid>2fe19b3c-ae5d-4020-81e0-eb66e328e8ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='序號'])[1]/preceding::a[4]</value>
      <webElementGuid>4a387355-74a6-4e94-b146-3feb1664ed2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='檢索點'])[1]/preceding::a[4]</value>
      <webElementGuid>dcc6f699-330a-4cec-83a2-b3d827e6557b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='4']/parent::*</value>
      <webElementGuid>2b4e5f0b-e30e-4eca-9db9-84a90eaabd48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/SearchStatisticsReport,jumpPage.sdirect?sp=4&amp;updateParts=results&amp;updateParts=nrResults')]</value>
      <webElementGuid>55889f66-7b7a-458a-bc12-dbfa1a643225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/li/a</value>
      <webElementGuid>098f3a13-bc4f-4d1e-b7ea-ec691782239b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'jumpPage_1' and @href = '/inspireapp/SearchStatisticsReport,jumpPage.sdirect?sp=4&amp;updateParts=results&amp;updateParts=nrResults' and (text() = '4' or . = '4')]</value>
      <webElementGuid>14e6c32b-b67d-40fe-8515-be845a995e57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
