<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>8ade5c93-67b4-49f6-95f1-47c4c4132627</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu2']/ul[11]/li/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.current > ul.ssub_nav_ul > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0cd85b8d-8bc8-4328-a208-33c54e2ec1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/SearchStatisticsReport.page?init=1</value>
      <webElementGuid>fd10a078-a098-42eb-84b2-8fd7e1e3e680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>檢索點/檢索語統計報表</value>
      <webElementGuid>7bfe67ea-b2f6-4a01-ae6f-0f363ed51697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2&quot;)/ul[@class=&quot;sub_nav_ul&quot;]/li[@class=&quot;current&quot;]/ul[@class=&quot;ssub_nav_ul&quot;]/li[1]/a[1]</value>
      <webElementGuid>ea329f48-8281-4efa-a08e-4492bb5b1c31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2']/ul[11]/li/ul/li/a</value>
      <webElementGuid>c5e678fe-bb70-4c16-98b6-1185afeb555b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'檢索點/檢索語統計報表')]</value>
      <webElementGuid>9eec73a5-7646-4809-b036-ac21b7f1192b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='排程日誌'])[1]/following::a[2]</value>
      <webElementGuid>537a56ac-43ef-4f62-8abe-a664b557422a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='排程監控者'])[1]/following::a[3]</value>
      <webElementGuid>7b817af5-0008-4a7b-b666-3a886c335f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='不同時段使用次數統計'])[1]/preceding::a[1]</value>
      <webElementGuid>abd1b4bb-5c3f-4725-ac46-e979f820140d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='書目下載次數統計'])[1]/preceding::a[2]</value>
      <webElementGuid>4e207d62-ff72-434b-a9ad-4cbc7b5a636d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='檢索點/檢索語統計報表']/parent::*</value>
      <webElementGuid>701e78b5-c9de-4a88-93ed-5ec98a2da6f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/SearchStatisticsReport.page?init=1')]</value>
      <webElementGuid>55b40a8d-2455-46ac-9dd9-0ee23710f922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[11]/li/ul/li/a</value>
      <webElementGuid>a6ee7357-ef01-4502-a82f-5fb11be68c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/SearchStatisticsReport.page?init=1' and (text() = '檢索點/檢索語統計報表' or . = '檢索點/檢索語統計報表')]</value>
      <webElementGuid>40087501-009e-4b61-a051-d35a974d35a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
