<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>036fe1c0-9653-4232-ad8c-d5e7574be1a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>47929d46-65e0-4226-88e6-622169ea548e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_0</value>
      <webElementGuid>9f7879cf-a539-4059-b292-034a31b047a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico_5</value>
      <webElementGuid>0a766acc-8a2b-41be-b3c6-2beae7f61414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>登出</value>
      <webElementGuid>cfdf6930-3cb4-436e-95b9-e65e7b904bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/circulation/exttransit/TransitItemsToBeReceived,$Border.$DirectLink_0.sdirect</value>
      <webElementGuid>340a5a14-ab22-41c4-8c01-f9249a61ffcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>登 出</value>
      <webElementGuid>1fff1509-7c5e-4909-aeb9-fb91fffec493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_0&quot;)</value>
      <webElementGuid>78630e54-715b-4b6f-80c6-80da72e93448</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_0']</value>
      <webElementGuid>3b808551-b9a4-4461-90d8-c0c0d68b5b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='LanguageForm']/div[2]/div/ul/li[10]/a</value>
      <webElementGuid>24a70d7b-b9b6-469f-9439-66dc1ca7cf88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'登 出')]</value>
      <webElementGuid>6037ae43-b98d-4a9f-9a49-a7b03287f839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='繁體中文'])[2]/following::a[2]</value>
      <webElementGuid>e0ff04cd-dde8-478c-b483-1995723ae957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::a[3]</value>
      <webElementGuid>8c4717bd-aade-4673-bba1-82b36eded002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='神資圖書館(15trunk機)'])[1]/preceding::a[1]</value>
      <webElementGuid>0cd55c82-6c9d-447d-943b-d019f2d0f869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='查詢'])[1]/preceding::a[1]</value>
      <webElementGuid>7f1bfe9c-e89b-4c94-83d5-5198c31a98a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='登 出']/parent::*</value>
      <webElementGuid>f2b554cb-4a81-441b-bedc-60c764896b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/circulation/exttransit/TransitItemsToBeReceived,$Border.$DirectLink_0.sdirect')]</value>
      <webElementGuid>8bfd0f07-b9e7-408c-b67a-2837a4978c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a</value>
      <webElementGuid>1ca15cd7-bd4e-4dae-966f-e42bf0f5bf9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_0' and @title = '登出' and @href = '/inspireapp/circulation/exttransit/TransitItemsToBeReceived,$Border.$DirectLink_0.sdirect' and (text() = '登 出' or . = '登 出')]</value>
      <webElementGuid>edf77248-bd21-48e8-8104-e698cb87ab88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
