<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_DatePicker1</name>
   <tag></tag>
   <elementGuidId>57d83116-59ed-4cec-9f1a-50bdb6a0f5b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DatePicker1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DatePicker1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1dae865-967b-4680-ab2a-a1219f0567ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c45b553b-a230-47c3-8448-e4ab0f572c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DatePicker1</value>
      <webElementGuid>a6d75e6d-4a8b-4fc3-9a05-b5fdf58dcc8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2024/04/18</value>
      <webElementGuid>a8dc2886-cccb-4ee9-85f9-87ce8a6a7582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>yyyy/MM/dd</value>
      <webElementGuid>da6d7812-cfdf-44b6-9a2c-27ab81b7f544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DatePicker1</value>
      <webElementGuid>c21efcac-2c6d-4296-9dc3-44a7f2317805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DatePicker1&quot;)</value>
      <webElementGuid>ee3e6db4-9d3a-4c10-b145-eebeac30eb65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DatePicker1']</value>
      <webElementGuid>2843eed8-fefb-402c-b927-de515106aecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>f9cddfee-4f5f-41c6-8c98-cbe7b918f072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>0c188dcb-7500-4c2c-a85e-2a4909d740ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'DatePicker1' and @title = 'yyyy/MM/dd' and @id = 'DatePicker1']</value>
      <webElementGuid>c969c716-834b-4a3a-babc-c469ea4a90cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
