<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_A100411899_field4</name>
   <tag></tag>
   <elementGuidId>765babb0-62cb-43d4-8d14-cbe8e368fe60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aae4984a-3fcd-4ce3-82d9-fae8d9b7a5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3017c73-cd36-422d-9a7f-5f9ba1969a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>03bde020-9a5d-461e-9d80-5c65a77ed483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field4</value>
      <webElementGuid>38472535-6096-43be-a2c8-ddb22dedfd31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field4</value>
      <webElementGuid>14b58cc7-47dc-41c8-ab80-52a1061fa5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_mare</value>
      <webElementGuid>26f6df7e-2c40-4c65-bb27-17f36f3d0dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>setFocus(4); VirtualKeyboard.attachInput(this);</value>
      <webElementGuid>47b8f5c6-8bc4-4e27-843e-eb8431813330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field4&quot;)</value>
      <webElementGuid>56c7a187-98a9-4bdb-adf8-906a736e9660</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field4']</value>
      <webElementGuid>cc05f78f-c741-4c23-8ded-326ed1376f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='inputField4']/nobr/input</value>
      <webElementGuid>e8aceff2-5748-4cfe-979a-a3fda9f72b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[7]/span/nobr/input</value>
      <webElementGuid>4696bb22-8fb0-4d55-b8a9-88d815c355fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field4' and @name = 'field4']</value>
      <webElementGuid>2d77f4e6-f275-4d10-82bd-c9044ad527af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
