<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_andornot_1_2</name>
   <tag></tag>
   <elementGuidId>5bdd574a-10ef-4f48-aa88-d8bb254d2386</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#boolean4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='boolean4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ec0eef04-e2c2-4765-a658-7b03b09630f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>boolean4</value>
      <webElementGuid>0c68c14a-a8cf-47b1-97c0-e0bfa19248be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boolean4</value>
      <webElementGuid>67348df3-ee13-4c53-8193-8b1e7808e130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
and
or
not
</value>
      <webElementGuid>f6ee8076-aed4-4ca6-9d5a-5c83a4bd1a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boolean4&quot;)</value>
      <webElementGuid>c0c91247-0381-461b-ac88-8586666f4d9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='boolean4']</value>
      <webElementGuid>96035a77-8b7c-4291-99df-7410a8fc4854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='If_17']/select</value>
      <webElementGuid>264f2044-7641-46ab-8ef8-72d3e87822da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A100411899'])[1]/following::select[4]</value>
      <webElementGuid>b1b06b84-e8d2-4681-8ab7-0909070d78f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A100404278'])[1]/following::select[4]</value>
      <webElementGuid>4049abf3-7df6-43a5-9d2f-c5bbf171c1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='限制條件'])[1]/preceding::select[3]</value>
      <webElementGuid>f588d65a-506a-4009-b940-31148f5cb8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='reset'])[1]/preceding::select[3]</value>
      <webElementGuid>3fa17873-8d03-4d72-a16c-78294b0c7937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[7]/select</value>
      <webElementGuid>63f7ed30-051c-4db7-a48f-f1973bd55dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'boolean4' and @id = 'boolean4' and (text() = '
and
or
not
' or . = '
and
or
not
')]</value>
      <webElementGuid>487869c2-b62c-4701-991c-7301e287f979</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
