<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__1</name>
   <tag></tag>
   <elementGuidId>77c97851-329f-40ea-b3d8-bb3022975f6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sCriteria4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='sCriteria4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4e0f7726-fa78-4463-8669-75f80ff28637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sCriteria4</value>
      <webElementGuid>54820e21-d381-4417-b92b-ffc9cb82e520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sCriteria4</value>
      <webElementGuid>ec171bf6-800f-4c45-af43-a378f5fc03f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
教師姓名
教師證號
課程名稱
課程代碼
指定有效日期
指定建立日期
備註
條碼號
書刊名
作者
</value>
      <webElementGuid>45cc98d4-878d-4b0e-9ff3-bc5dc0373bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sCriteria4&quot;)</value>
      <webElementGuid>6b694c35-2ce7-405a-9479-8bf5cb976caa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='sCriteria4']</value>
      <webElementGuid>ae1bb2e8-5307-4859-9449-18ab6ce00eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='If_17']/select[2]</value>
      <webElementGuid>22229f7b-acfe-4904-ab60-38e781c6368d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A100411899'])[1]/following::select[5]</value>
      <webElementGuid>36e49e8e-403e-455a-b50c-23da5cbda29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A100404278'])[1]/following::select[5]</value>
      <webElementGuid>a56431d1-21e6-469c-9fa3-9db1b40f66e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='限制條件'])[1]/preceding::select[2]</value>
      <webElementGuid>991c3ab0-85d3-44c6-ad23-afeee25fdd91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='reset'])[1]/preceding::select[2]</value>
      <webElementGuid>b5d9589f-8a86-4d99-a40e-9e4475af280c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[7]/select[2]</value>
      <webElementGuid>d1a27674-1cb8-43ed-9ba1-ce2b30f024c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'sCriteria4' and @id = 'sCriteria4' and (text() = '
教師姓名
教師證號
課程名稱
課程代碼
指定有效日期
指定建立日期
備註
條碼號
書刊名
作者
' or . = '
教師姓名
教師證號
課程名稱
課程代碼
指定有效日期
指定建立日期
備註
條碼號
書刊名
作者
')]</value>
      <webElementGuid>3274d156-5950-46d8-b6e8-55be6e85f5e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
