<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(15trunk)_member_id</name>
   <tag></tag>
   <elementGuidId>e2e1d5db-dfd1-4471-8ee5-e2fcde07385a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#member_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='member_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94998aa9-50d3-4d35-b789-f82e90feca36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>099ebf2f-2fb8-4442-9ea8-9ae9f62539e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>member_id</value>
      <webElementGuid>1070d7bd-7c40-4ede-b55f-b34d1f8e5390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>member_id</value>
      <webElementGuid>11c6a271-156a-45dc-83d7-dd78d23add5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>3469664e-1968-45e7-a295-8f526fa4a14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.value='';</value>
      <webElementGuid>b1b25adb-b8c4-4a3e-923c-4200d9cd0823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>請輸入帳號</value>
      <webElementGuid>7e061bb6-d2a4-4f0a-b095-9c0f05514eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;member_id&quot;)</value>
      <webElementGuid>c5a62a8c-749b-4ae2-b6f0-ece0f39cc53a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='member_id']</value>
      <webElementGuid>2f5f895a-5d40-4274-86eb-cfdbed63e846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='logon']/table/tbody/tr/td/input</value>
      <webElementGuid>bbf985b8-6b9b-4468-bc78-9a46a2783dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>faa9e6d7-23b7-4d6f-a7eb-bf265d7a5f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'member_id' and @id = 'member_id' and @placeholder = '請輸入帳號']</value>
      <webElementGuid>25b0259d-5e0d-4e9e-84f5-b2587b299dbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
