<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__Any_0_1</name>
   <tag></tag>
   <elementGuidId>1a366c30-aa53-486a-83d8-e7250cd88082</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='Any_0_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Any_0_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1b77d59d-2fe7-4921-8ae5-d90211110536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/inspireapp/images/ico_add.gif</value>
      <webElementGuid>87816ee4-e165-4f9e-88d4-925e06a24830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3b09753f-0940-473c-b411-60205103074f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Any_0_1</value>
      <webElementGuid>f440d0da-3011-4752-8adf-37237776a9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Any_0_1&quot;)</value>
      <webElementGuid>280f9c4e-dd34-4847-8842-32c524896fa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='Any_0_1']</value>
      <webElementGuid>d9135d2d-17e4-4ac1-962e-6a9dc14f47e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='showTreeBtn1_0']/img</value>
      <webElementGuid>041c4317-22ef-4390-be0e-5d65951a3031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/span/a/img</value>
      <webElementGuid>88bee01a-058c-4e44-89db-91bb5d6e9d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/inspireapp/images/ico_add.gif' and @id = 'Any_0_1']</value>
      <webElementGuid>cd38d268-5330-4340-a9d7-e9e0276fdf3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
