<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3</name>
   <tag></tag>
   <elementGuidId>80f1d3b3-f860-4a2c-bf26-58d05b80bac7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>375ded43-b9f3-411b-8f31-be7949e27eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_2</value>
      <webElementGuid>ea1a2512-2553-4a0c-b688-75ec4450e053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setstytle()</value>
      <webElementGuid>087727fe-1daa-4e74-b445-d1d2d6155bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>butonsub</value>
      <webElementGuid>347f5d9b-697d-4d87-9a92-ab76a3a2b6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/LoanDeskStatisticByStaff,ReportsStatus.$DirectLink.sdirect?updateParts=ReportStatus</value>
      <webElementGuid>2de8196b-ce4f-4eac-810e-a941bdfbd9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 目前執行的報表</value>
      <webElementGuid>4d015027-d40a-4890-8127-f79badebc88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_2&quot;)</value>
      <webElementGuid>b8310bb5-76dd-42b4-bf70-668ead422b81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_2']</value>
      <webElementGuid>f5588a2c-9534-41a5-95fb-98adedb16364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='If_5']/div/table/tbody/tr/td/table/tbody/tr/td/a</value>
      <webElementGuid>69e3b977-bc52-44f4-ae49-9ed8a628c477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'目前執行的報表')]</value>
      <webElementGuid>a2131347-2bad-4fe5-953e-0b8bf43dcde0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='報表狀態'])[2]/following::a[1]</value>
      <webElementGuid>f8350c5f-1978-4f60-b619-b9d01d6faad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='報表狀態'])[1]/following::a[1]</value>
      <webElementGuid>f6ea0199-9953-40dc-8ecf-a04a9c61e2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/LoanDeskStatisticByStaff,ReportsStatus.$DirectLink.sdirect?updateParts=ReportStatus')]</value>
      <webElementGuid>57af8a2e-d247-4375-9e89-4c43dbbc44b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td/a</value>
      <webElementGuid>839e8bb8-1ec9-4e45-b91f-e90081f059ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_2' and @href = '/inspireapp/LoanDeskStatisticByStaff,ReportsStatus.$DirectLink.sdirect?updateParts=ReportStatus' and (text() = ' 目前執行的報表' or . = ' 目前執行的報表')]</value>
      <webElementGuid>4d0aae5c-98a6-4698-9c5d-ccd1bef0e495</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
