<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>b87230c9-a85e-46d5-8d97-172d8f3c16d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(29) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu2']/ul[11]/li[4]/ul/li[29]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1943ca0f-4782-4cbc-8100-4a9632af9a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/FineCollectedNumberStatistics.page?init=1</value>
      <webElementGuid>a780d313-56b9-4d1a-926a-0b9633533802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>罰款收款人數/次數統計</value>
      <webElementGuid>c5f53d75-8ed2-4e1a-952b-620bd5e2fcc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2&quot;)/ul[@class=&quot;sub_nav_ul&quot;]/li[@class=&quot;current&quot;]/ul[@class=&quot;ssub_nav_ul&quot;]/li[29]/a[1]</value>
      <webElementGuid>7ea6d4b8-bf4b-4f88-8420-cfd6f70c0f2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2']/ul[11]/li[4]/ul/li[29]/a</value>
      <webElementGuid>e15a60e9-5463-48ce-a0b5-f15bbb898880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'罰款收款人數/次數統計')]</value>
      <webElementGuid>f13d2552-deb5-40da-afb7-5f3018f11c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='跨館預約/調閱館藏借閱排行榜'])[1]/following::a[1]</value>
      <webElementGuid>96e00ce6-cbe9-4bcf-bc55-a09643209eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='館藏流通量統計'])[1]/following::a[2]</value>
      <webElementGuid>305091bf-548b-47a8-86e3-33f9444e0f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='跨館預約/調閱使用量統計'])[1]/preceding::a[1]</value>
      <webElementGuid>369e3c9e-124a-4b90-aa39-0c0946087a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='罰款收款統計'])[1]/preceding::a[2]</value>
      <webElementGuid>1e70aafa-7610-4b0a-a33b-c265fb8af650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='罰款收款人數/次數統計']/parent::*</value>
      <webElementGuid>eb4d4832-fe07-41fd-a6f8-0d61e04cc8c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/FineCollectedNumberStatistics.page?init=1')]</value>
      <webElementGuid>3311316f-0cbe-421a-9193-6c38a24b26e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[29]/a</value>
      <webElementGuid>bf905ebc-52a6-4e9a-8ed5-33050c447aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/FineCollectedNumberStatistics.page?init=1' and (text() = '罰款收款人數/次數統計' or . = '罰款收款人數/次數統計')]</value>
      <webElementGuid>cf764e84-e5ab-42e2-be4f-aeac6b1da10d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
