<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>8f1eee81-8ae6-4bb0-9fc5-b96fdcb029c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu2']/ul[11]/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ecda3076-7796-4651-a73e-0e087560466a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f85250bb-acf4-490f-bf71-5dff7684f031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>電子資源統計</value>
      <webElementGuid>c59d3cdb-d0d3-471b-b3f7-aa52645836c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2&quot;)/ul[@class=&quot;sub_nav_ul&quot;]/li[2]/a[1]</value>
      <webElementGuid>c0138f2d-cd2c-427e-81ea-ca98b116157e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2']/ul[11]/li[2]/a</value>
      <webElementGuid>9acabd46-5bc9-4087-9d2e-4aa5e17b5dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'電子資源統計')]</value>
      <webElementGuid>fc6404f8-6ecf-4c5a-8145-8c1c867a4066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='書目下載次數統計'])[1]/following::a[1]</value>
      <webElementGuid>a6d04bd2-40dd-4f85-bc5e-2a6bbcf955ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='不同時段使用次數統計'])[1]/following::a[2]</value>
      <webElementGuid>390eee4b-cacd-4f51-b409-ddd82e965809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='電子資源-館藏點閱次數統計'])[1]/preceding::a[1]</value>
      <webElementGuid>52c571cc-133f-484f-8fa5-f9aa87f081c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='電子資源-讀者點閱次數統計'])[1]/preceding::a[2]</value>
      <webElementGuid>d741e913-049b-4f45-b86d-441211e22978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='電子資源統計']/parent::*</value>
      <webElementGuid>b3f64158-2b05-492e-9a43-1837c5dc19bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[42]</value>
      <webElementGuid>852a1d0d-5c8e-4a8a-8eed-ab74ee31e710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[11]/li[2]/a</value>
      <webElementGuid>3f237325-718c-473b-9041-e805b02da27f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '電子資源統計' or . = '電子資源統計')]</value>
      <webElementGuid>d8a2a36b-da19-4fd2-b31f-6bb549ac604f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
