<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_DatePicker_2</name>
   <tag></tag>
   <elementGuidId>7ff355b2-b3b6-4a28-98dd-229f34e00371</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DatePicker_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DatePicker_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1090eff6-252a-49a0-9154-bfb5028deeac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ffe91948-f216-4308-b888-d512b30f18a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DatePicker_2</value>
      <webElementGuid>24c7568d-2e41-42fa-907e-3f96d3852ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>yyyy/MM/dd</value>
      <webElementGuid>749d4b13-726f-47c1-886e-8542edc92f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DatePicker_2</value>
      <webElementGuid>a1225607-9419-4adb-8970-f411d8bc514b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DatePicker_2&quot;)</value>
      <webElementGuid>e3521503-6c6c-4064-9054-5f3a757846f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DatePicker_2']</value>
      <webElementGuid>56427ff6-cadf-497e-8ab6-c4d00463d35f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showSearch']/table/tbody/tr[3]/td[2]/input[2]</value>
      <webElementGuid>12edbd00-bdff-4275-a354-560f078aa2b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input[2]</value>
      <webElementGuid>0e0bb8e0-2b35-40a1-b6cb-4b88696403fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'DatePicker_2' and @title = 'yyyy/MM/dd' and @id = 'DatePicker_2']</value>
      <webElementGuid>7b6a91c9-3787-44c1-a681-af066e048c60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
