<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_DatePicker</name>
   <tag></tag>
   <elementGuidId>d1be625e-b922-414f-8afa-edeb221300dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DatePicker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DatePicker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca2ff441-5acd-4123-ac40-32f86d8a0fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aba9fcf0-b6c9-477b-831d-514298aa77de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DatePicker</value>
      <webElementGuid>c1b588f2-cd48-43cc-97fa-e1537ec3155c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2024/03/16</value>
      <webElementGuid>f371b25a-614c-4fd3-be78-65e0d503d3ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>yyyy/MM/dd</value>
      <webElementGuid>a1d7c1ed-6a55-4884-b832-e41cf1bf6c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DatePicker</value>
      <webElementGuid>3f487a16-7ff4-4238-af5c-9efbc948300d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DatePicker&quot;)</value>
      <webElementGuid>310e43b2-26b9-4b90-a1bf-af4bcdedc04e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DatePicker']</value>
      <webElementGuid>b77b98a8-e6f1-419d-8cd2-ce572bd01bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showSearch']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>60660684-7f28-43ab-ab51-56f1c8cbb890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>da3b7c92-f50e-417d-96a4-9c802f2a4d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'DatePicker' and @title = 'yyyy/MM/dd' and @id = 'DatePicker']</value>
      <webElementGuid>bbf34544-02b7-4672-a3bd-7b763026fc46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
