<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(15trunk)_member_id</name>
   <tag></tag>
   <elementGuidId>5d66ade0-836a-43e7-8867-e9ae1430c099</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#member_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='member_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01b34467-763e-4817-ae7a-b5b4abb30145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81337238-9e1f-4f8d-84f5-0558a0efd615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>member_id</value>
      <webElementGuid>97b38a21-6bb2-413d-8d9a-fd3962c2a49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>member_id</value>
      <webElementGuid>56016736-fdec-4f4c-adcc-8fd5b2bbe81e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>37891467-09bf-4b56-a3f9-e2779408c8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.value='';</value>
      <webElementGuid>ca7478a3-7b5a-4224-a932-b045007f6135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>請輸入帳號</value>
      <webElementGuid>8cf60bfe-5859-4d73-9ec9-f862decb2ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;member_id&quot;)</value>
      <webElementGuid>43c8f6e1-d223-4ba3-92b4-2a3cb2453e82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='member_id']</value>
      <webElementGuid>c9b989c3-5493-458c-8a95-3a442adbb9bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='logon']/table/tbody/tr/td/input</value>
      <webElementGuid>75fc3e19-cc32-41b0-8c36-2817c46f9fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>6782c3b2-5ebb-4220-89ec-31a8ece3abdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'member_id' and @id = 'member_id' and @placeholder = '請輸入帳號']</value>
      <webElementGuid>fc938fd6-a3cf-4e9c-9a02-2eb2dab2d572</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
