<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(15trunk)_member_pwd</name>
   <tag></tag>
   <elementGuidId>b9ae46ae-dc35-46c2-b8e9-74103a21a17c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#member_pwd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='member_pwd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ca0f2eb-d751-47b5-9acb-b06250d1289f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>55eccc8e-793d-42bc-9196-53fd83ad2449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>member_pwd</value>
      <webElementGuid>0b0fe4aa-43f0-4333-b26c-f2644bdc4a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>member_pwd</value>
      <webElementGuid>6c21e82f-4479-4dff-8046-6c0bedff9325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>KeyPress(event)</value>
      <webElementGuid>71f93b28-af06-4850-adaf-2f063dcb61d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>請輸入密碼</value>
      <webElementGuid>8db9b286-c1c2-4679-8793-22ca756ecef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f215fbc4-303a-4491-8848-01279fbbabe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.value='';</value>
      <webElementGuid>16428082-3a6a-4afe-aa4f-a6e48af1c046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;member_pwd&quot;)</value>
      <webElementGuid>5d9ea53d-c610-4d31-8c25-991bc5d79c8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='member_pwd']</value>
      <webElementGuid>377c7cd2-d7b1-4ffa-b98c-0a4dabdf77e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='logon']/table/tbody/tr[2]/td/input</value>
      <webElementGuid>b34eceb8-8c04-430d-af0e-93b94c875342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>1f1b9729-aa7d-4c39-83a7-6663f1cd82da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'member_pwd' and @id = 'member_pwd' and @placeholder = '請輸入密碼']</value>
      <webElementGuid>8883b271-2965-44c9-b5dd-df2cc3eec5d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
