<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_3</name>
   <tag></tag>
   <elementGuidId>3f449ac2-0891-4ae0-ad73-3a660a9550a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pageChanger_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pageChanger_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>495e15d4-f92a-40bf-a44d-ce3dd7e452e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pageChanger_0</value>
      <webElementGuid>968191a7-c59f-43ca-a158-7ecb4b8faba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/NavigareCarduri,searchComponent.$search$PaginateComponent.pageChanger.sdirect?sp=3&amp;sp=X&amp;sp=465&amp;updateParts=results&amp;updateParts=nrResults&amp;updateParts=autoRefreshZone</value>
      <webElementGuid>c3ee8ce5-34f2-4be6-9fbb-7d3f2b0adb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return tapestry.linkOnClick(this.href,'pageChanger_0', false)</value>
      <webElementGuid>44c7f565-2808-4cea-96a0-f0c807f35ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
									     3
									   </value>
      <webElementGuid>60e325ed-b1d3-4c35-baf9-0850bdbe36cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageChanger_0&quot;)</value>
      <webElementGuid>b029a06d-ec02-447d-9876-f1c64f812a71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pageChanger_0']</value>
      <webElementGuid>a3a666ac-ddfd-4953-917f-96f944242bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nrResults']/ul/li[5]/a[3]</value>
      <webElementGuid>d98528af-5025-4142-92c8-90d98ef89b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'3')])[2]</value>
      <webElementGuid>29716059-da3b-4645-83e8-8f72d2e5a5ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='s'])[1]/following::a[5]</value>
      <webElementGuid>333cd68a-e430-4ba3-bc95-888e48b90563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='筆'])[1]/following::a[5]</value>
      <webElementGuid>7c8df1cb-0fe4-4b61-8c49-e5b99c7d9df7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='...'])[1]/preceding::a[3]</value>
      <webElementGuid>f769c4c8-9c5c-46ed-8a5a-8bc8019908ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3']/parent::*</value>
      <webElementGuid>80f6753d-3cca-459c-9c56-7725b55a9d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/NavigareCarduri,searchComponent.$search$PaginateComponent.pageChanger.sdirect?sp=3&amp;sp=X&amp;sp=465&amp;updateParts=results&amp;updateParts=nrResults&amp;updateParts=autoRefreshZone')]</value>
      <webElementGuid>7e515bf9-6af7-4bb4-9276-7dfb989e9c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a[3]</value>
      <webElementGuid>f3c95821-67a0-4868-b28f-b9235df07ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pageChanger_0' and @href = '/inspireapp/NavigareCarduri,searchComponent.$search$PaginateComponent.pageChanger.sdirect?sp=3&amp;sp=X&amp;sp=465&amp;updateParts=results&amp;updateParts=nrResults&amp;updateParts=autoRefreshZone' and (text() = '
									     3
									   ' or . = '
									     3
									   ')]</value>
      <webElementGuid>fd90d9c8-edce-4418-beeb-acc9d156c2a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
