<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__1</name>
   <tag></tag>
   <elementGuidId>126944c3-39cb-4d73-8cd4-b06247e271c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='sCriteria4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sCriteria4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b6407071-fb5b-460f-a90d-8a8c1ee196de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sCriteria4</value>
      <webElementGuid>71455380-56dd-46d0-a17d-e29ab55662c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sCriteria4</value>
      <webElementGuid>63f13f57-19e1-4e34-b080-b596e0aed695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
讀者姓名
身份證號
新增日期
檢查日期
證卡有效起始日期
證卡有效截止日期
讀者證號
建立的館員帳號
檢查者帳號
</value>
      <webElementGuid>f4d37e09-6c2d-4f8b-9978-be0e2b54c69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sCriteria4&quot;)</value>
      <webElementGuid>a82b6bc3-9288-4679-b383-413b8d6f56b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='sCriteria4']</value>
      <webElementGuid>4dd97d09-a4f4-446e-bb39-7d313b04a3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='If_17']/select[2]</value>
      <webElementGuid>1825517e-a273-4604-ab77-22a37de90ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='楊世敏'])[1]/following::select[8]</value>
      <webElementGuid>06dc481f-5cdf-44aa-99d7-f71fedcba7a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='楊世凡'])[1]/following::select[8]</value>
      <webElementGuid>e6aceaf1-f4f2-4f50-aaca-f5ec53df7153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='瀏覽條件:'])[1]/preceding::select[2]</value>
      <webElementGuid>ebb8fa58-6ec3-4419-a98d-b42be896f80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='起始以:'])[1]/preceding::select[3]</value>
      <webElementGuid>47f7f0e2-2502-48e1-9674-23666f1a2b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[6]/select[2]</value>
      <webElementGuid>c2675753-7222-4ab1-b545-50364dba3039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'sCriteria4' and @id = 'sCriteria4' and (text() = '
讀者姓名
身份證號
新增日期
檢查日期
證卡有效起始日期
證卡有效截止日期
讀者證號
建立的館員帳號
檢查者帳號
' or . = '
讀者姓名
身份證號
新增日期
檢查日期
證卡有效起始日期
證卡有效截止日期
讀者證號
建立的館員帳號
檢查者帳號
')]</value>
      <webElementGuid>a37f4049-83f5-4d23-b0d5-308b351ca85d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
