<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3_4</name>
   <tag></tag>
   <elementGuidId>2ad57ec0-bce9-4eb3-9d81-b1ad3cb3a096</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Any_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p > #Any_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>59e45d8f-21a7-423c-905f-3904b792a99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/myrestart.svc</value>
      <webElementGuid>39aa4969-38b8-4e6c-9bc4-bf1fee628ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Any_0</value>
      <webElementGuid>2180914e-ee1c-4707-8a5f-704f67f892ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            請重新登入系統!
          </value>
      <webElementGuid>e9a05a36-de8f-44b5-87d4-8c1a9ea41297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exception&quot;)/div[1]/div[@class=&quot;exceptionDialog&quot;]/div[1]/p[1]/a[@id=&quot;Any_0&quot;]</value>
      <webElementGuid>abf3fde7-c6a7-4dad-9d77-48afdbd26357</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='Any_0']</value>
      <webElementGuid>e08f94c5-3b23-43b2-8954-8254be9b2246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='exception']/div/div[2]/div/p/a</value>
      <webElementGuid>4b1f2758-5e03-4f1e-b4fb-319bf8a0eaa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'請重新登入系統!')]</value>
      <webElementGuid>32368176-7f64-4f90-942b-655d8c14cf21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='An exception has occurred!'])[1]/following::a[1]</value>
      <webElementGuid>674c8024-66b0-4837-a3e2-b72a39dc7ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::a[1]</value>
      <webElementGuid>f9a03ed2-376c-4ddd-a035-409b397253fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.apache.tapestry.BindingException'])[1]/preceding::a[2]</value>
      <webElementGuid>9760fa2c-c58c-43cc-b1fc-b6d7f387fd85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='binding:'])[1]/preceding::a[2]</value>
      <webElementGuid>18adceaf-8da1-4cb1-8420-599989aa8d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='請重新登入系統!']/parent::*</value>
      <webElementGuid>dc11f762-e0b1-40f5-b177-9f7c5871da4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/myrestart.svc')]</value>
      <webElementGuid>0659663e-49b4-40a6-b308-f93c04ae111f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>ba17b80c-a475-4aa4-8e58-31a8daa30a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/myrestart.svc' and @id = 'Any_0' and (text() = '
            請重新登入系統!
          ' or . = '
            請重新登入系統!
          ')]</value>
      <webElementGuid>c74e471f-9a1f-4b8e-965a-0f97dc47e26d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
