<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Number_Any_5_0</name>
   <tag></tag>
   <elementGuidId>5a9e5369-f049-4c46-b558-f2f4ee118514</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='Any_5_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Any_5_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1d4722e1-b834-45ae-a412-703ceda72db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/inspireapp/images/arrow_unchecked_13.png</value>
      <webElementGuid>aaed08f9-97f6-48d9-a3e7-ab38bb41ec42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>04624943-100a-4563-adac-b911ef1494bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Any_5_0</value>
      <webElementGuid>948b193e-44a6-4336-bb30-959534ff951b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Any_5_0&quot;)</value>
      <webElementGuid>0b65d7a8-ba02-4655-8505-6f8fb4d67c48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='Any_5_0']</value>
      <webElementGuid>e49647b9-e3fa-4c3b-8b17-9def702001f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_1_1']/img</value>
      <webElementGuid>62227742-1acf-4786-889e-cf40e4efc9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/a/img</value>
      <webElementGuid>1ddba268-9641-4623-b081-224b5992d91e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/inspireapp/images/arrow_unchecked_13.png' and @id = 'Any_5_0']</value>
      <webElementGuid>99ad388b-393c-4628-a9e7-51942c723a1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
