<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(15trunk)_member_pwd</name>
   <tag></tag>
   <elementGuidId>8942e380-13c5-4076-ac3d-2e27bb6d8204</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#member_pwd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='member_pwd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82319342-11ab-4cff-a242-40188d320d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2c1aa8f5-0231-4d23-b155-294a6887daa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>member_pwd</value>
      <webElementGuid>0b003f28-7cb5-4bc4-abd5-eee255a311e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>member_pwd</value>
      <webElementGuid>e5ff6ed4-bd9a-4f56-b24d-e6137ebb172d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>KeyPress(event)</value>
      <webElementGuid>90d895a0-ca16-471a-a3ed-7b35a7aa9bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>請輸入密碼</value>
      <webElementGuid>bf9e33a1-6190-41d1-ab7c-31e0b11867fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ef432f54-5a3b-4dcc-a760-0fbe63da5c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.value='';</value>
      <webElementGuid>730f92c9-c84a-4947-afe1-2bdf06845f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;member_pwd&quot;)</value>
      <webElementGuid>0751b41b-15d0-4ee7-9b8e-ed6d09bc04c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='member_pwd']</value>
      <webElementGuid>4328c656-fd03-4f3e-b618-07bb4eaf668c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='logon']/table/tbody/tr[2]/td/input</value>
      <webElementGuid>b9bd39db-3a16-4c84-92f4-0f73bb69031b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>6dd61fd2-23e3-4466-a7d8-55a23e8dd82b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'member_pwd' and @id = 'member_pwd' and @placeholder = '請輸入密碼']</value>
      <webElementGuid>abd38fdb-46c4-4d23-937b-4319a4e195cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
