<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__buttonSubmit</name>
   <tag></tag>
   <elementGuidId>b8b79a24-2936-4113-b425-66b9546d9f19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buttonSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='buttonSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a78c3fba-46d9-4e0e-a7bf-7b42749c5008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9b2926af-015b-47c8-a016-2fc452fbe16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>buttonSubmit</value>
      <webElementGuid>e02cfbfe-26f7-4df2-83f4-8aed4bd70ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonSubmit</value>
      <webElementGuid>d9e4b2f9-df1a-4406-b542-073e10780dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>查詢</value>
      <webElementGuid>61d64137-509b-4234-b657-041aa5e8d578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttons</value>
      <webElementGuid>3fa3cb36-303e-4c2d-94e3-99141e7ec15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonSubmit&quot;)</value>
      <webElementGuid>033615ee-6434-4cff-b378-5ed7a44a3d0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='buttonSubmit']</value>
      <webElementGuid>301c6fff-8b3c-4bf5-b010-797dd3343de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div[2]/table/tbody/tr[8]/td[4]/table/tbody/tr/td/input</value>
      <webElementGuid>5dd53e96-0f45-4bb1-9ba4-72a195b267b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[4]/table/tbody/tr/td/input</value>
      <webElementGuid>8cb44bf1-997c-46b8-9f68-c9dbe3bc2019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'buttonSubmit' and @id = 'buttonSubmit']</value>
      <webElementGuid>389a9958-e488-46a3-9bd5-b261e27e6b66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
