<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(15trunk)_member_pwd</name>
   <tag></tag>
   <elementGuidId>31cf9822-1a6b-45c0-8159-b12d7553c6ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#member_pwd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='member_pwd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>592d36b7-6501-4ad0-9baf-e4830aded80a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b40e01a9-f85e-46a5-bc12-ab547908de83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>member_pwd</value>
      <webElementGuid>5cf0eea3-a07d-4a12-94c9-318da5d6263b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>member_pwd</value>
      <webElementGuid>b3b92cd5-5d2f-4de6-95da-bb7d5fe60517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>KeyPress(event)</value>
      <webElementGuid>3d2f5bda-1989-4697-940a-88cc39ca84b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>請輸入密碼</value>
      <webElementGuid>47a1d413-695b-49cb-b8a2-d15acb76a8c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>24f3ea56-4c27-4539-b59c-922216bb175c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.value='';</value>
      <webElementGuid>040949e7-e384-475c-a6c3-5f36e649c12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;member_pwd&quot;)</value>
      <webElementGuid>679f4d92-d62c-4ae1-8492-288fec6a18c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='member_pwd']</value>
      <webElementGuid>cebded41-79fd-488a-9fc3-a0fb3d529e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='logon']/table/tbody/tr[2]/td/input</value>
      <webElementGuid>522b3712-6f2c-4feb-a11d-2a5c2dbb0da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>8d88d7be-d433-4f97-bf45-185abdf2b15e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'member_pwd' and @id = 'member_pwd' and @placeholder = '請輸入密碼']</value>
      <webElementGuid>ae975deb-9bb4-4674-9af8-5b742a03cf3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
