<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1</name>
   <tag></tag>
   <elementGuidId>4c50e62f-9ebb-4d18-a74c-d0a919ec78ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu2']/ul[11]/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1ca81768-35b5-41c8-a931-d1edd3162704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>85a15dbe-0a99-40ae-ab07-8db0705b78e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>期刊統計</value>
      <webElementGuid>ce58c4f4-0048-4e29-ae10-c87db8de915e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2&quot;)/ul[@class=&quot;sub_nav_ul&quot;]/li[6]/a[1]</value>
      <webElementGuid>0669d981-60b7-4f4e-b305-328034045247</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2']/ul[11]/li[6]/a</value>
      <webElementGuid>48049678-bc92-4d09-99ff-d455f2abc7c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'期刊統計')]</value>
      <webElementGuid>13c58c0f-e18f-47cd-95e8-089250e6919c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='書商績效統計'])[1]/following::a[1]</value>
      <webElementGuid>66680488-b1d0-4a52-8cb6-48f89d4dddb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='書商到書率'])[1]/following::a[2]</value>
      <webElementGuid>f6b3dde7-e554-4bd4-aecf-cf361e5d01f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='期刊到刊率統計報表'])[1]/preceding::a[1]</value>
      <webElementGuid>edbbac4f-90ca-4f01-b0f2-608fcf517986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='平均收刊日統計報表'])[1]/preceding::a[2]</value>
      <webElementGuid>00053a30-4b32-4a7d-98e8-fadb2d730967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='期刊統計']/parent::*</value>
      <webElementGuid>321efabc-7189-4c64-ac1f-3d5662341240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[46]</value>
      <webElementGuid>3cfd9546-7254-428e-b151-028f1e1480f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[11]/li[6]/a</value>
      <webElementGuid>6571e4bf-1a1f-413e-90f5-32ca1eed246d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '期刊統計' or . = '期刊統計')]</value>
      <webElementGuid>ade311b3-52a8-4125-a6c4-2ebcadf046a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
