<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__field2</name>
   <tag></tag>
   <elementGuidId>45e07b94-3cf6-45a9-a843-1144627cfe6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#field2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f9b2e1e-95d3-49e6-a446-216c8003a45e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e09f3d98-63a2-4610-beb0-2439977905fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f1b74c91-1ec8-491c-9a1f-05e191682606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field2</value>
      <webElementGuid>993a8d59-2f34-470c-9f68-672a15cc0aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field2</value>
      <webElementGuid>30bb65d1-1071-4406-9335-453c36e58052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_mare</value>
      <webElementGuid>962c69a1-283a-459f-860e-d2059b3ff2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>VirtualKeyboard.attachInput(this); diacriticInsert(this);</value>
      <webElementGuid>efca28fe-e5dd-4290-a0a7-55fca42301b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field2&quot;)</value>
      <webElementGuid>408d979d-aa38-4147-9cd7-5ad7d6219a90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field2']</value>
      <webElementGuid>83ae4114-e2a8-408c-845a-7d23690ff7e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='inputField2']/nobr/input</value>
      <webElementGuid>88f04d51-4020-4916-89f0-4d4340a0e9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/span[2]/nobr/input</value>
      <webElementGuid>b29f4e2c-8879-4ac5-b769-d9ba2c76099c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field2' and @name = 'field2']</value>
      <webElementGuid>2cacf634-f413-4494-9087-32ea531d6b71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
