<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>c77ec9bd-d1e5-4992-b0b5-ac10ab6e214b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.main_nav_ico17</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/ul/li[11]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>00a08212-1d9c-443c-99ee-8a70008e9162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>e923c367-1024-4730-a8b2-992b960a6b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main_nav_ico17 </value>
      <webElementGuid>fe02b230-ff69-4aa9-8688-39681a930734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 統計 </value>
      <webElementGuid>0a2a1cb1-3912-4519-8961-3d11595a27e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/ul[1]/li[11]/a[@class=&quot;main_nav_ico17&quot;]</value>
      <webElementGuid>90d5c7b7-67c3-410c-acd2-30c43c720122</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/ul/li[11]/a</value>
      <webElementGuid>ad96f23b-5029-4230-aa3f-a7c5a4101c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'統計')]</value>
      <webElementGuid>0bb0b915-d71d-4279-bf41-733b334beb66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='管理'])[1]/following::a[1]</value>
      <webElementGuid>e9f99073-6613-4ff9-ac26-d952c4fff609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='學科服務'])[1]/following::a[2]</value>
      <webElementGuid>2b44081b-de11-4c47-9af1-bb94c5583522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='清單'])[1]/preceding::a[1]</value>
      <webElementGuid>0ef3caac-de7c-43ae-92ef-84c0f03b87ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portal'])[1]/preceding::a[2]</value>
      <webElementGuid>d24f29d8-6405-4516-835f-7cae75a8fd71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='統計']/parent::*</value>
      <webElementGuid>16ce57e3-29b0-4f1b-9a97-c02b4cb0abc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[13]</value>
      <webElementGuid>a9336e12-b8d3-4341-9509-9113cd2ef0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/a</value>
      <webElementGuid>eae8c500-7359-4063-bfbd-c70a1f0dff2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = ' 統計 ' or . = ' 統計 ')]</value>
      <webElementGuid>b13a9548-45d2-430a-bf2b-5d2650c93948</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
