<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>e46195d5-d2e8-46f4-b300-e17210d814cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_0_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_0_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2a8961cd-788a-4d3c-bae3-f89cb68bf2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_0_0</value>
      <webElementGuid>4d1ba342-b0cc-409e-84db-3636a03d7d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>butonsub</value>
      <webElementGuid>26653c19-b2d2-4c2c-94ef-49514d02b89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/LocationExchangeTransferring,ReportsStatus.$DirectLink_0.sdirect?updateParts=ReportStatus</value>
      <webElementGuid>5bd63d32-3c18-4ec1-baa9-233e2e6c6578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return tapestry.linkOnClick(this.href,'DirectLink_0_0', false)</value>
      <webElementGuid>4fd9c4d5-bd17-44d6-ac5a-41978686c1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
										關閉 
								</value>
      <webElementGuid>1ed3d542-51a8-4954-a916-229897eb9a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_0_0&quot;)</value>
      <webElementGuid>f9312977-60db-4603-8fae-fd0ea14f22c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_0_0']</value>
      <webElementGuid>5de2d79c-703f-4382-be69-3ab0a4ed6b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='If_5']/div/table/tbody/tr/td/table/tbody/tr/td[2]/a</value>
      <webElementGuid>7bf3842b-d08e-4cf6-93af-1ff5f9f0b1a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'關閉')]</value>
      <webElementGuid>e2d00d19-2453-4cf5-8caa-d031dd15b4f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='報表狀態'])[2]/following::a[2]</value>
      <webElementGuid>21393457-c6b3-4e7a-ae33-a84f4f436a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='執行時間'])[1]/preceding::a[1]</value>
      <webElementGuid>c3c67d4b-622a-417a-a161-c2f58f1af3ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/LocationExchangeTransferring,ReportsStatus.$DirectLink_0.sdirect?updateParts=ReportStatus')]</value>
      <webElementGuid>e2548042-2b72-424c-b5e3-6dff19bdccc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td[2]/a</value>
      <webElementGuid>872e47fa-ee8e-4b4a-9682-cc19425e6fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_0_0' and @href = '/inspireapp/LocationExchangeTransferring,ReportsStatus.$DirectLink_0.sdirect?updateParts=ReportStatus' and (text() = ' 
										關閉 
								' or . = ' 
										關閉 
								')]</value>
      <webElementGuid>95257e04-e6f2-4615-9a8b-d03c9d130831</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
