<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_DatePicker</name>
   <tag></tag>
   <elementGuidId>28a558fd-f4d7-4cba-8148-2278b6915f13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DatePicker']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DatePicker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a57efb33-25ad-48d1-b176-3fa7a55c9624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>859259bb-33ae-43f0-9a8f-a1441f21cccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DatePicker</value>
      <webElementGuid>e3e7a672-7ed0-4664-8144-4390a35d6efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>yyyy/MM/dd</value>
      <webElementGuid>46844851-a082-4846-a2ea-8febd39a6524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DatePicker</value>
      <webElementGuid>78ad4b5d-3b8b-4428-9939-27af2d931800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DatePicker&quot;)</value>
      <webElementGuid>d456f098-426e-4e48-9226-a0419e9f3f3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DatePicker']</value>
      <webElementGuid>62412df5-06a8-428c-b58e-09353f315a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>0fde5e62-bbed-4bc3-9f4d-7400d70eb646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>acbba41a-163d-4de9-8b3f-869af1b0ba11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'DatePicker' and @title = 'yyyy/MM/dd' and @id = 'DatePicker']</value>
      <webElementGuid>b8a875bb-72cc-418b-8392-8fad55e5cd39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
