<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>10a31a4c-3332-46e4-a1cc-51c3166dce70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu2']/ul[12]/li[3]/ul/li[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.current > ul.ssub_nav_ul > li:nth-of-type(7) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>69b6e2c7-6a55-49dc-b197-b7756879d70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/DelayList.page?init=1</value>
      <webElementGuid>38959cef-cdb3-4059-99f5-c1aff01e2d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>借閱逾期清單</value>
      <webElementGuid>e8f5cb9d-59e4-4050-94fd-8adb48b38a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2&quot;)/ul[@class=&quot;sub_nav_ul&quot;]/li[@class=&quot;current&quot;]/ul[@class=&quot;ssub_nav_ul&quot;]/li[7]/a[1]</value>
      <webElementGuid>c5817a62-26c0-4463-bb4a-357e629924ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2']/ul[12]/li[3]/ul/li[7]/a</value>
      <webElementGuid>3abab573-c96e-4dc4-a156-bef4a12d2d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'借閱逾期清單')]</value>
      <webElementGuid>52150e5e-ce06-4846-90c3-c2bb4541932b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='讀者欠款清單'])[1]/following::a[1]</value>
      <webElementGuid>98c8f6c6-40ac-4d12-b8e0-8041c4a59ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='新書清單'])[1]/following::a[2]</value>
      <webElementGuid>9b586455-b4a1-4397-857a-7964d3247189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='罰款收款清單'])[1]/preceding::a[1]</value>
      <webElementGuid>c2337746-b122-428d-98b9-80686fb05c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='預約撤架清單'])[1]/preceding::a[2]</value>
      <webElementGuid>307e4f02-5f56-4956-ae60-65a219cc95ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='借閱逾期清單']/parent::*</value>
      <webElementGuid>448cbfd6-a7fc-492c-82d6-6aa5f02d3938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/DelayList.page?init=1')]</value>
      <webElementGuid>e383f043-0961-4ea9-81ad-38a5afe4377a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[12]/li[3]/ul/li[7]/a</value>
      <webElementGuid>8c0f1c9e-039c-43ba-9e4d-153f8e750d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/DelayList.page?init=1' and (text() = '借閱逾期清單' or . = '借閱逾期清單')]</value>
      <webElementGuid>6eca29f8-8dc7-4863-97ce-afd7aacbbeb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
