<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b__1</name>
   <tag></tag>
   <elementGuidId>54c6e3a5-24ab-4ddd-94ad-263a071aa278</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='If_31']/nobr/font/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nobr > font > b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>14890a2a-ac3c-4a32-bc16-5f9d0f2f4c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>瀏覽條件:</value>
      <webElementGuid>870fc4e7-fa48-4244-bfa1-650c19ab7702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;If_31&quot;)/nobr[1]/font[1]/b[1]</value>
      <webElementGuid>132b595c-6487-476e-8471-abc8d4b23da6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='If_31']/nobr/font/b</value>
      <webElementGuid>d413ed43-7eab-459d-b819-2b2280d7703b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='限制條件'])[1]/following::b[1]</value>
      <webElementGuid>5b5dc76a-400b-4b35-bfcc-7769498313a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='查詢條件'])[1]/following::b[1]</value>
      <webElementGuid>9a7e9601-196d-4b4a-8aea-921e90045746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='限制條件'])[2]/preceding::b[2]</value>
      <webElementGuid>39f8a670-b191-4ff2-a73a-749ad6735971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='瀏覽條件:']/parent::*</value>
      <webElementGuid>7c062e46-8ff0-4196-8371-bb676a95b0a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nobr/font/b</value>
      <webElementGuid>093898a5-f33e-4cdd-99ae-c5f35321a98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = '瀏覽條件:' or . = '瀏覽條件:')]</value>
      <webElementGuid>c5f762c1-27bf-4b71-aae2-4c63f854d85b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
