<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>6521140b-79d7-45f8-91bd-bb8883233cfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.current > ul.ssub_nav_ul > li:nth-of-type(15) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu2']/ul[11]/li[3]/ul/li[15]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fa7ae4b3-f5c2-44b2-9d25-84506afa0ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/MaterialTypeRangeStatistic.page?init=1</value>
      <webElementGuid>0f7e3e49-8c99-4bce-b8c4-d4e89bd8c2ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>資料類型範圍館藏統計表</value>
      <webElementGuid>328f3fc3-37be-4f49-b262-02c058d85c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2&quot;)/ul[@class=&quot;sub_nav_ul&quot;]/li[@class=&quot;current&quot;]/ul[@class=&quot;ssub_nav_ul&quot;]/li[15]/a[1]</value>
      <webElementGuid>3a0e0ba2-ccbc-431f-b655-cc7ccbbe94ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2']/ul[11]/li[3]/ul/li[15]/a</value>
      <webElementGuid>b7a5649d-7693-4f81-ac04-e9db415b5088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'資料類型範圍館藏統計表')]</value>
      <webElementGuid>910eb44c-b167-45a5-8080-4b3ac89ad05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='非書資料數量金額統計'])[1]/following::a[1]</value>
      <webElementGuid>75745fcb-7053-45c7-b24e-d1915059b5b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='圖書冊數金額分類統計'])[1]/following::a[2]</value>
      <webElementGuid>00a1665c-cc33-41c2-9efb-d0e7b39d11d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='編目工作量統計(個人)'])[1]/preceding::a[1]</value>
      <webElementGuid>4e1fbbba-feac-495e-aecd-1fbdbdff4e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='編目工作量統計(各館)'])[1]/preceding::a[2]</value>
      <webElementGuid>85432826-dfd4-44e2-8d3b-e04f2e42e667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='資料類型範圍館藏統計表']/parent::*</value>
      <webElementGuid>911bd275-4f72-4607-a342-96d82f69c353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/MaterialTypeRangeStatistic.page?init=1')]</value>
      <webElementGuid>015c0ff2-b75a-45e1-8e81-bd17681a7f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[11]/li[3]/ul/li[15]/a</value>
      <webElementGuid>77cdb37b-8af5-402e-b7c4-95d444c3c71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/MaterialTypeRangeStatistic.page?init=1' and (text() = '資料類型範圍館藏統計表' or . = '資料類型範圍館藏統計表')]</value>
      <webElementGuid>aa27c1eb-6a51-4af4-9ccf-e301cab1e358</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
