<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_-</name>
   <tag></tag>
   <elementGuidId>4fa2a35b-73fb-4b7c-bfc7-f1d15ee4a061</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu2']/ul[3]/li[9]/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.current > ul.ssub_nav_ul > li:nth-of-type(3) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a1fc6187-6d58-4cf5-b6a8-be5845b1d438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/circulation/exttransit/transit_items_to_be_received?init=1</value>
      <webElementGuid>416f81a2-6dc2-4672-bd3e-903fbdda7b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>移轉-收到項目</value>
      <webElementGuid>98923644-6cba-47c0-a2ca-d0bf92b2f0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2&quot;)/ul[@class=&quot;sub_nav_ul&quot;]/li[@class=&quot;current&quot;]/ul[@class=&quot;ssub_nav_ul&quot;]/li[3]/a[1]</value>
      <webElementGuid>5d3df2c0-0aef-48b6-90d3-d882a4bd8db5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2']/ul[3]/li[9]/ul/li[3]/a</value>
      <webElementGuid>114c262b-a8cb-4c67-b703-70390dde5545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'移轉-收到項目')]</value>
      <webElementGuid>e46d2b38-341c-4f1a-937a-90b81d3d3023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='移轉-寄送項目'])[1]/following::a[1]</value>
      <webElementGuid>8cc75ccb-1761-4e99-9e94-cfc338e608d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='跨館預約/調閱需求'])[1]/following::a[2]</value>
      <webElementGuid>e2f659b0-76c3-4b41-be71-ed05cfa98cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='盤點比對'])[1]/preceding::a[1]</value>
      <webElementGuid>2bbb53e4-a640-439c-a6a3-1251bb36b8b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='選擇報廢'])[1]/preceding::a[3]</value>
      <webElementGuid>68c0faf3-237d-4c15-a161-53c53686bfc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='移轉-收到項目']/parent::*</value>
      <webElementGuid>3f70dbaa-d221-428d-b261-c77288cccac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/circulation/exttransit/transit_items_to_be_received?init=1')]</value>
      <webElementGuid>04d15afc-c304-4325-9b57-4c5799a48325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/ul/li[3]/a</value>
      <webElementGuid>4053ca25-8c0d-4a9d-99b5-1bb851d7d32b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/circulation/exttransit/transit_items_to_be_received?init=1' and (text() = '移轉-收到項目' or . = '移轉-收到項目')]</value>
      <webElementGuid>45f34853-dfd6-4976-9c78-aed3684ed18b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
