<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_DatePicker</name>
   <tag></tag>
   <elementGuidId>81789964-4761-45bd-838e-ed075dc13092</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DatePicker']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DatePicker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac07ed0e-7827-44d4-a480-96e21041ec92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1385a815-9dca-41a5-a5a4-50d25a3cff65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DatePicker</value>
      <webElementGuid>9c9afb3f-f9e2-4dfd-b9e3-d2eef70e0fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2024/03/17</value>
      <webElementGuid>d61495df-5b2a-4ef4-9d4e-490487ee8ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>yyyy/MM/dd</value>
      <webElementGuid>9a2b4f62-2b0f-4819-9b78-d7c07ce03620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DatePicker</value>
      <webElementGuid>013478e5-6c60-4cd9-9214-bdce8c47767d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DatePicker&quot;)</value>
      <webElementGuid>81a14175-5fe0-4eb3-a55c-380d8009890e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DatePicker']</value>
      <webElementGuid>9870faa9-2ffa-44e6-bfd4-53b21753f337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showSearch']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>f8546252-36e3-4fd2-b3f8-2a8ce9b48805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>e0f5eb5a-0da2-48ee-afbe-fb93314c8880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'DatePicker' and @title = 'yyyy/MM/dd' and @id = 'DatePicker']</value>
      <webElementGuid>3cc4ed89-0198-427c-8d8e-ed29c0c60747</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
