<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b__1</name>
   <tag></tag>
   <elementGuidId>59d79c0e-7f90-490c-996d-e4a8c1b24227</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nobr > font > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='If_41']/nobr/font/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>99d20f97-baf7-4cf1-9911-03121f00fe7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>瀏覽條件:</value>
      <webElementGuid>52a80ea4-0f98-4ddd-99a1-4fcc13e7d7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;If_41&quot;)/nobr[1]/font[1]/b[1]</value>
      <webElementGuid>f0ae8ad3-9d59-49c4-9015-07207af6a780</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='If_41']/nobr/font/b</value>
      <webElementGuid>bd056fb2-f22a-4b7f-a059-73630becd8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='限制條件'])[2]/preceding::b[2]</value>
      <webElementGuid>594f86fc-eaa8-46e9-9092-6232fd6fd7aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='瀏覽條件:']/parent::*</value>
      <webElementGuid>63f5eb43-fa17-4801-9eff-e80476e576fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nobr/font/b</value>
      <webElementGuid>9320a9f3-a90d-4567-8919-975181f71b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = '瀏覽條件:' or . = '瀏覽條件:')]</value>
      <webElementGuid>be6934b5-e6a1-4a27-9fa9-8f6d2659fe63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
