<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>b12a7fd2-e360-4cc8-8a4a-e5e44162a885</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='jumpPage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jumpPage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>77e53207-ee04-4bf8-a0b9-8de1228c366d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jumpPage</value>
      <webElementGuid>702717f9-7eb5-4414-b177-ae65b6a4a047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/DeleteReserveList,jumpPage.sdirect?sp=2&amp;updateParts=results&amp;updateParts=nrResults</value>
      <webElementGuid>bb4a3da1-9003-49e2-acd3-406ef87ecbc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return tapestry.linkOnClick(this.href,'jumpPage', false)</value>
      <webElementGuid>b3033ec3-6001-437a-8483-ea852555e757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e0a88d5c-2bb4-4956-b54c-2ae8c6a296f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jumpPage&quot;)</value>
      <webElementGuid>f5ce24aa-ca67-4e72-b7cb-611ce50759d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='jumpPage']</value>
      <webElementGuid>28239b8b-114c-48d7-a1a3-c4b4e7d5ad8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='For_10']/li/a</value>
      <webElementGuid>71f045a0-b24a-4272-bead-14412209ca2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'2')])[10]</value>
      <webElementGuid>eeb1eaaa-f362-4db1-94fe-6840ff9128f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='狀態'])[1]/following::a[5]</value>
      <webElementGuid>0ec0f3a0-7906-4464-90e9-f9b0afeac1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='序號'])[1]/preceding::a[6]</value>
      <webElementGuid>090bbd7c-dc8e-438d-a5bf-8f7d4491fc8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='分館'])[3]/preceding::a[6]</value>
      <webElementGuid>d4e404fe-2fe1-4a54-8f9a-512deba9c1a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2']/parent::*</value>
      <webElementGuid>f842053d-5594-45a3-8096-b2602b977a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/DeleteReserveList,jumpPage.sdirect?sp=2&amp;updateParts=results&amp;updateParts=nrResults')]</value>
      <webElementGuid>ff6450d2-8a99-49c6-9272-6865ea80e31d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/li/a</value>
      <webElementGuid>c787f53b-43f0-46a9-9f79-825dfe2c28a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'jumpPage' and @href = '/inspireapp/DeleteReserveList,jumpPage.sdirect?sp=2&amp;updateParts=results&amp;updateParts=nrResults' and (text() = '2' or . = '2')]</value>
      <webElementGuid>d82515f8-9e3a-45e5-8c8e-c6a510a729c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
