<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>3545038d-1a51-4f3d-935a-424930ce2778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu2']/ul[10]/li[3]/ul/li[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3fa2abb5-57ee-4d0e-bc4c-10655f207744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/weekly_schedule?init=1</value>
      <webElementGuid>7dc092ea-2135-44a6-8215-e5d1e2c76f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>每周開閉館設定</value>
      <webElementGuid>eaa5ce11-ed79-4714-8901-8f00ea78dafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2&quot;)/ul[@class=&quot;sub_nav_ul&quot;]/li[@class=&quot;current&quot;]/ul[@class=&quot;ssub_nav_ul&quot;]/li[6]/a[1]</value>
      <webElementGuid>fb0481da-288e-4515-9d8c-610ec9f07a98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2']/ul[10]/li[3]/ul/li[6]/a</value>
      <webElementGuid>35f45032-7a5c-4d79-befc-66ad192f2124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'每周開閉館設定')]</value>
      <webElementGuid>b6745b9e-2bb9-4512-adee-8cb6f98c096c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='一般'])[1]/following::a[1]</value>
      <webElementGuid>e05fd88d-e3ca-43c9-8a48-2238edcf1670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='日常作業排程'])[1]/following::a[2]</value>
      <webElementGuid>e95266c1-7f20-4721-92b7-0e1097803dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='閉館日期維護'])[1]/preceding::a[1]</value>
      <webElementGuid>343085c4-eaa7-438b-85e8-2e3dede68a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='交易紀錄類型'])[1]/preceding::a[2]</value>
      <webElementGuid>a1459d7d-6c19-493a-a7ba-230d7ef6137b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='每周開閉館設定']/parent::*</value>
      <webElementGuid>7bca7d6c-4665-47bd-9a5c-fe0c6853a429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/weekly_schedule?init=1')]</value>
      <webElementGuid>2f97b6f1-b23f-4b9a-8bbf-e571934dbdcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[6]/a</value>
      <webElementGuid>1758ec61-871a-402e-81eb-38c9b1494cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/weekly_schedule?init=1' and (text() = '每周開閉館設定' or . = '每周開閉館設定')]</value>
      <webElementGuid>a7c9a53c-2178-4ad1-9b60-8303ed3afe0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
