<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>529be639-3deb-4811-86ca-b5dc89437a82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_0_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_0_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eb8a2e41-c575-41aa-9ef0-0927d545d0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_0_0</value>
      <webElementGuid>72b472c3-a603-4b6e-bd84-ea6a412b8d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>butonsub</value>
      <webElementGuid>3cabdbdd-9007-41b1-a06c-abac5156e22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/LongTermLendBookList,ReportsStatus.$DirectLink_0.sdirect?updateParts=ReportStatus</value>
      <webElementGuid>daba93c1-8abd-4638-bf98-4879a4dae898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return tapestry.linkOnClick(this.href,'DirectLink_0_0', false)</value>
      <webElementGuid>530b308f-9d55-4c6c-bdf0-f46fabcb3e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
										關閉 
								</value>
      <webElementGuid>d2d62bc8-0d55-4092-997b-cef363e5ec36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_0_0&quot;)</value>
      <webElementGuid>b9c39a9f-bcd4-4cf5-94f5-fabdd5a60e45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_0_0']</value>
      <webElementGuid>6c7603fe-8bf9-4545-ba1e-7050cf5a53c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='If_7']/div/table/tbody/tr/td/table/tbody/tr/td[2]/a</value>
      <webElementGuid>d2c0f96a-aaaa-4a69-95ca-447d0c66aaaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'關閉')]</value>
      <webElementGuid>3ba3ec4f-721b-4dba-ad40-bcef66b4c771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='報表狀態'])[2]/following::a[2]</value>
      <webElementGuid>a230c620-de28-468b-b4bb-fb660ae12e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='執行時間'])[1]/preceding::a[1]</value>
      <webElementGuid>6b62aab6-8eca-479f-beaa-09a80e45dadf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/LongTermLendBookList,ReportsStatus.$DirectLink_0.sdirect?updateParts=ReportStatus')]</value>
      <webElementGuid>9174ee95-c053-4a59-8850-54819d798183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td[2]/a</value>
      <webElementGuid>c8b4d899-a32e-4f73-9c21-87c00afd62c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_0_0' and @href = '/inspireapp/LongTermLendBookList,ReportsStatus.$DirectLink_0.sdirect?updateParts=ReportStatus' and (text() = ' 
										關閉 
								' or . = ' 
										關閉 
								')]</value>
      <webElementGuid>86178e98-2947-41d0-add2-c730ef001c09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
