<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3</name>
   <tag></tag>
   <elementGuidId>dc33653c-5664-464d-8aa9-9b38b1851f72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='swindow.ddepartment3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b4da4238-e0c6-40c5-aabc-30140b59b282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swindow.ddepartment3</value>
      <webElementGuid>5f455e73-10bc-4581-b14d-0947d7cd5d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>node</value>
      <webElementGuid>954dc705-9e54-4f9f-a854-30f81ab844ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:window.ddepartment.selectElement('\u795E\u8CC7\u5716\u66F8\u9928', 121, true)</value>
      <webElementGuid>17afacb3-c43e-4c92-8659-c5b6a93881f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript: window.ddepartment.s(3);</value>
      <webElementGuid>7f27fd84-2c76-475d-b1d7-89fd12de2a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>神資圖書館</value>
      <webElementGuid>f8047bdc-ea7b-45dd-9c97-7480dd16d18e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swindow.ddepartment3&quot;)</value>
      <webElementGuid>83dda9cc-8dea-47df-9a4f-6ba7241c5da9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='swindow.ddepartment3']</value>
      <webElementGuid>fa1c15b5-a003-4aeb-a2f0-b129c96ec951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dwindow.ddepartment0']/div[3]/a[2]</value>
      <webElementGuid>6043850e-e2be-434f-8a57-0d4e2d49da55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'神資圖書館')]</value>
      <webElementGuid>68ec085e-40ec-47b5-867e-a695ebd0537e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='_New Item1234'])[1]/following::a[2]</value>
      <webElementGuid>b6686056-369e-40eb-b6ce-c79c9d6d2e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='_New Item'])[1]/following::a[3]</value>
      <webElementGuid>3a22074b-6c14-4aa8-b315-320ce950721f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='行政單位其他其他其他'])[1]/preceding::a[2]</value>
      <webElementGuid>8e97490e-b5c1-47e3-83c5-1f9c47af17fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='學校行政'])[1]/preceding::a[4]</value>
      <webElementGuid>61a1a765-7442-4088-93a5-f71fd6835f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='神資圖書館']/parent::*</value>
      <webElementGuid>fd03aa12-fa6b-490e-8fc8-4dcbd0f7d32f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:window.ddepartment.selectElement('\u795E\u8CC7\u5716\u66F8\u9928', 121, true)&quot;)]</value>
      <webElementGuid>9741c4a7-0386-4b89-934f-da846fa384df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a[2]</value>
      <webElementGuid>c47f2ac8-20c4-47ef-b6cd-73ee8dcfd41a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'swindow.ddepartment3' and @href = concat(&quot;javascript:window.ddepartment.selectElement(&quot; , &quot;'&quot; , &quot;\u795E\u8CC7\u5716\u66F8\u9928&quot; , &quot;'&quot; , &quot;, 121, true)&quot;) and (text() = '神資圖書館' or . = '神資圖書館')]</value>
      <webElementGuid>aa827838-8f15-4d73-bcfe-ba7868b5ab41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
