<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>c39ddbee-dc73-4003-ac6c-7153763ff90b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.current > ul.ssub_nav_ul > li:nth-of-type(9) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu2']/ul[11]/li[6]/ul/li[9]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>69187b0f-a46d-46d0-b1a0-459e81eebafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/SerialCostCenterOrder.page?init=1</value>
      <webElementGuid>cf1647d1-cc45-4f0a-89ca-2ef23ff1025f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>期刊經費訂購統計報表</value>
      <webElementGuid>140ea770-c800-413e-888c-d0b2a2e16f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2&quot;)/ul[@class=&quot;sub_nav_ul&quot;]/li[@class=&quot;current&quot;]/ul[@class=&quot;ssub_nav_ul&quot;]/li[9]/a[1]</value>
      <webElementGuid>50fc5cce-fbff-4ddc-a91e-855e739cf74a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2']/ul[11]/li[6]/ul/li[9]/a</value>
      <webElementGuid>92309a88-0397-4186-be4c-6f015a390f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'期刊經費訂購統計報表')]</value>
      <webElementGuid>10eafaf9-e6e4-4dad-93ad-7e8825409661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='逾期違約金統計'])[1]/following::a[1]</value>
      <webElementGuid>70ffd048-2189-44de-8808-70877f1f7c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='期刊訂費漲幅統計'])[1]/following::a[2]</value>
      <webElementGuid>5de7f5b6-476e-4899-b8bf-d6c8ea5f06a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='場地設備使用統計表'])[1]/preceding::a[2]</value>
      <webElementGuid>675cd042-3182-4d01-a3b6-c02b0894f60b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='報表模組範本維護'])[1]/preceding::a[3]</value>
      <webElementGuid>c0163080-68b3-40fe-81f9-ae537f839bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='期刊經費訂購統計報表']/parent::*</value>
      <webElementGuid>20519aad-9eb1-4022-894f-77d0762b43db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/SerialCostCenterOrder.page?init=1')]</value>
      <webElementGuid>725939dc-ae15-40b2-9591-fa2003060d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li[9]/a</value>
      <webElementGuid>ce2cdd6b-da4c-4a1f-8ebb-5c3db063a15c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/SerialCostCenterOrder.page?init=1' and (text() = '期刊經費訂購統計報表' or . = '期刊經費訂購統計報表')]</value>
      <webElementGuid>e27c20cb-35af-40e1-a6d0-f6cc0457fd06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
