<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3_4</name>
   <tag></tag>
   <elementGuidId>45c3143e-5e17-4680-b0e1-e16fa1759498</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b317c53d-2a80-48f5-be71-5cf7cc932e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_3</value>
      <webElementGuid>531d0896-31ac-45a4-acbb-4f5efea43e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>butonsub</value>
      <webElementGuid>e0aa4a96-f1b0-4001-8a27-a8dc69bb0b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/circulation/inventory/InventorySearchDefinition,crsAreaAuthority.$DirectLink_1.sdirect</value>
      <webElementGuid>0f4891d5-c4a0-4b6c-813e-4fcb322b10ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return tapestry.linkOnClick(this.href,'DirectLink_3', false)</value>
      <webElementGuid>f014bfd0-837b-40bf-b571-2ba3f2b6b56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				  儲存條碼號定義  
			</value>
      <webElementGuid>c44d51d0-affd-4ba8-826a-9baf5cf93a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_3&quot;)</value>
      <webElementGuid>cbd0a42e-ee68-4463-ac9c-a7f8806f7914</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_3']</value>
      <webElementGuid>9e44189d-156e-4a3f-b75f-b33e8025b402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='If_211']/div[2]/div/a</value>
      <webElementGuid>a20119a6-187e-447e-942c-cc495591d284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'儲存條碼號定義')]</value>
      <webElementGuid>39788bba-0d9a-4393-8c63-2f59207329ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GO'])[2]/following::a[1]</value>
      <webElementGuid>e7f8ee5f-ead6-47cb-9f78-c88060ded50d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go To Page'])[1]/preceding::a[4]</value>
      <webElementGuid>80be751e-32a5-4c2f-85c6-2a168e770dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inentory Definition'])[1]/preceding::a[4]</value>
      <webElementGuid>369b4c4f-f8d8-418d-9af6-13affc68abf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/circulation/inventory/InventorySearchDefinition,crsAreaAuthority.$DirectLink_1.sdirect')]</value>
      <webElementGuid>7f4945d4-c47f-46eb-bf59-1476da3bf134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>f1b0455e-78dd-4b54-b43e-d8d3cc3f103d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_3' and @href = '/inspireapp/circulation/inventory/InventorySearchDefinition,crsAreaAuthority.$DirectLink_1.sdirect' and (text() = '
				  儲存條碼號定義  
			' or . = '
				  儲存條碼號定義  
			')]</value>
      <webElementGuid>336e2e5a-3ce0-47f7-b4c5-aeef2d8f1f01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
