<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Task 22</name>
   <tag></tag>
   <elementGuidId>3a3325ce-2117-4d8c-aabd-4c1525bdf8c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='PageLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PageLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>65f48446-132a-4ad5-a866-98f9775bebae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PageLink</value>
      <webElementGuid>256fbe09-8a95-4118-97bc-3de1d5b2a382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>simple</value>
      <webElementGuid>441cc00d-a71d-4844-baf3-0e7e04a5c51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/admin/task_manager_page</value>
      <webElementGuid>0b7eb7ce-1ce8-4f48-969a-caafda2ab220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Task #22</value>
      <webElementGuid>93fc98df-b443-45ac-95ec-4d5e493790cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PageLink&quot;)</value>
      <webElementGuid>1cd77ff6-b6bc-4f2a-b9d1-0704296dc330</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='PageLink']</value>
      <webElementGuid>c571392f-0544-4527-9277-125ffe57eb67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='If_5']/pre/a</value>
      <webElementGuid>fdbf8d77-db39-43c8-865f-87d1cd89f519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Task #22')]</value>
      <webElementGuid>54d1fa14-cdcb-4ad0-a9fc-b5dc8a7fd45e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='測試盤點_202403130145'])[1]/following::a[8]</value>
      <webElementGuid>88e26a01-5f56-4fd8-b20f-03898f171007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='盤點母樣本數:'])[1]/preceding::a[1]</value>
      <webElementGuid>55dd0c1c-2eb4-41b6-af28-09d80d4c45c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='盤點上傳數:'])[1]/preceding::a[1]</value>
      <webElementGuid>ef79f405-8db7-4439-8913-ef40e5b1de9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Task #22']/parent::*</value>
      <webElementGuid>5d47204b-a015-4c85-8c63-7334027d2b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/inspireapp/admin/task_manager_page')])[2]</value>
      <webElementGuid>91df5bb2-2d6e-46a4-8fca-83743fd7ad64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//pre/a</value>
      <webElementGuid>97ae9159-0da4-417f-86b1-642d981d98dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'PageLink' and @href = '/inspireapp/admin/task_manager_page' and (text() = 'Task #22' or . = 'Task #22')]</value>
      <webElementGuid>c07c4774-fc9f-4f2c-8b71-a0e2051f8008</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
