<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>df482425-be0a-4751-b3d7-0aec5f2a3d6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='veilInventoryDialog']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#veilInventoryDialog</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6e001746-fe77-40b3-858c-c7f038c358e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>veilInventoryDialog</value>
      <webElementGuid>fdba9058-a564-482e-9168-9b60212d276e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>ad54dccc-22c9-45c3-988a-231b199aa32c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;veilInventoryDialog&quot;)</value>
      <webElementGuid>0b1956c8-1e9c-490e-b15b-95a6d34df2ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='veilInventoryDialog']</value>
      <webElementGuid>e525f6bf-f498-4df7-8055-80bf41eeff63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='Body']/div/div/div[2]/div[7]</value>
      <webElementGuid>286ea76f-655d-462a-8db0-984f17e1508f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go To Page'])[1]/following::div[5]</value>
      <webElementGuid>69798e94-547a-4a38-be69-78d5f2048ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inentory Definition'])[1]/preceding::div[1]</value>
      <webElementGuid>c4f45769-b8cf-4009-bcd6-482ea7a50e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='盤點名稱'])[1]/preceding::div[3]</value>
      <webElementGuid>16422507-87f1-411c-a105-caf82355c52b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]</value>
      <webElementGuid>3ff8aa45-3e3d-4b1b-b94a-9a81158dc30f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'veilInventoryDialog' and (text() = ' ' or . = ' ')]</value>
      <webElementGuid>7ab4c31c-a889-4b2a-83bb-2ef6c1342fb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
