<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>b4e920d2-b2fe-4d1f-bc94-16f2c425d936</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu2']/ul[6]/li/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.current > ul.ssub_nav_ul > li:nth-of-type(2) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>200ebaea-7adb-4d61-b2e4-b2a20d351618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/manager_borrow_query?init=1</value>
      <webElementGuid>085245af-5862-4243-b575-69c4e9983689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>借用記錄</value>
      <webElementGuid>cd986c45-ba08-410d-9e4b-8cead090e39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2&quot;)/ul[@class=&quot;sub_nav_ul&quot;]/li[@class=&quot;current&quot;]/ul[@class=&quot;ssub_nav_ul&quot;]/li[2]/a[1]</value>
      <webElementGuid>2f184a3e-f133-44c7-a358-d1b9671015e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2']/ul[6]/li/ul/li[2]/a</value>
      <webElementGuid>22bc4fcb-175c-4502-9f5a-44e44e5521a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'借用記錄')]</value>
      <webElementGuid>fc1533e6-dbb9-4fb6-9e4d-f25a21a59a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='預約記錄'])[1]/following::a[1]</value>
      <webElementGuid>dbb45c75-8d62-4ffe-a9bf-f50500240f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='催缺記錄'])[2]/following::a[3]</value>
      <webElementGuid>14b8907c-4b8c-4d1a-9341-5b6658692ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='分類維護'])[1]/preceding::a[2]</value>
      <webElementGuid>0a418b1f-ab95-40b6-a4b0-83d983d8cdb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='單項維護'])[1]/preceding::a[3]</value>
      <webElementGuid>c8f7d7f4-e5c4-4d1c-b7dd-93c70b67cb68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='借用記錄']/parent::*</value>
      <webElementGuid>9653540c-25db-4f5d-9ff6-c654b3ba472c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/manager_borrow_query?init=1')]</value>
      <webElementGuid>9f82d92e-5ecc-42f3-a8f3-a53fdf512087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[6]/li/ul/li[2]/a</value>
      <webElementGuid>13d97f2c-9cf9-4d53-8ad6-cb7eecc1a3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/manager_borrow_query?init=1' and (text() = '借用記錄' or . = '借用記錄')]</value>
      <webElementGuid>7e94b63d-8cfc-4b20-9d27-7803e7160e19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
