<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>728547e5-5a87-4186-b7c9-526dec354b06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3eefa7be-9e0b-4b78-afa7-ed5a5abb9563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_0</value>
      <webElementGuid>f242bd29-7862-44ca-87e4-c7e073f94772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico_5</value>
      <webElementGuid>aca85209-c5da-4796-9987-d2fb0c8b8999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>登出</value>
      <webElementGuid>f13937cb-a03e-4d35-bf0b-92fadd2b234c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/Blacklist,$Border.$DirectLink_0.sdirect</value>
      <webElementGuid>a206a27d-df86-44f3-aeff-302558779fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>登 出</value>
      <webElementGuid>5770c27d-b4e9-415a-a447-91eccddb153d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_0&quot;)</value>
      <webElementGuid>ac5bf22e-ae46-4b7f-9348-9f0a15c56856</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_0']</value>
      <webElementGuid>9028501c-6ee5-4c48-8aea-de5dabbd6056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='LanguageForm']/div[2]/div/ul/li[10]/a</value>
      <webElementGuid>87899916-8b64-46d5-9c73-3aa23c75049c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'登 出')]</value>
      <webElementGuid>897ccde6-1750-4990-bd99-fca85b5daf47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='繁體中文'])[2]/following::a[2]</value>
      <webElementGuid>852f5b28-06e7-4355-afe7-ec50cab73d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::a[3]</value>
      <webElementGuid>a7cb39cd-da1e-4e86-a010-3eb30b2b42d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='神資圖書館(15trunk機)'])[1]/preceding::a[1]</value>
      <webElementGuid>fd57e790-1d45-43ee-8ad7-a01d4328dbca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='查詢'])[1]/preceding::a[1]</value>
      <webElementGuid>4b486dec-b25e-408d-ad49-da7c893390cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='登 出']/parent::*</value>
      <webElementGuid>0cea13b2-abcc-4134-a28c-6fb48b69ba75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/Blacklist,$Border.$DirectLink_0.sdirect')]</value>
      <webElementGuid>09429bb2-0ab2-45cf-8323-19223393e196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a</value>
      <webElementGuid>b5738536-e476-4553-9399-6ba182a5f012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_0' and @title = '登出' and @href = '/inspireapp/Blacklist,$Border.$DirectLink_0.sdirect' and (text() = '登 出' or . = '登 出')]</value>
      <webElementGuid>cfc12275-ea12-477f-96d9-eb483d249e00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
