<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(15trunk)_Submit</name>
   <tag></tag>
   <elementGuidId>d78bcd07-1829-436d-8f6d-f5ac0ac6f542</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06c3c980-95cb-43b1-93aa-bfa13aca49db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5e524d36-e5ec-413d-859a-9bc7920becd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>cb198abb-b40e-4595-836f-64fffa23a3a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>1dfd8385-293f-48f6-a2fa-5d7894fe7a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>login(dojo.byId('logon'))</value>
      <webElementGuid>5fa17574-c370-4d44-963b-c4bb8b70dac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>登入</value>
      <webElementGuid>03e67707-eca8-4381-9251-9c09bb0e783f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login_btn</value>
      <webElementGuid>49699314-27cb-4625-9336-7b1ba8109d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Submit&quot;)</value>
      <webElementGuid>4652e770-188c-483f-a78f-f0a89ae2949f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Submit']</value>
      <webElementGuid>3c06003a-a216-4dfc-b20d-bc2750821eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='logon']/table/tbody/tr[3]/td/button/input</value>
      <webElementGuid>898a947d-31c8-4711-9b48-07d7abbe094b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/input</value>
      <webElementGuid>88da6546-5f0f-4b5c-bc05-fbae4a8f32b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'Submit' and @id = 'Submit']</value>
      <webElementGuid>78b5f189-2429-4c3d-8230-8c0306266b1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
