<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3</name>
   <tag></tag>
   <elementGuidId>cb8c8244-358d-4175-8d96-6938b3a4d7a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Template_Search_Expand_Options']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Template_Search_Expand_Options</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5ea5be97-3e59-4344-a12c-03a50c1c8a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:ExpandOptions()</value>
      <webElementGuid>a5002e87-2eee-4a92-a3bb-6e99771c3440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Template_Search_Expand_Options</value>
      <webElementGuid>9c7af1b8-46a7-4297-8a06-569e86f4c626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NoVisitNoUnder</value>
      <webElementGuid>c0b2b3f7-c213-4c52-9630-09c12e817d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		                    		限制條件
		                    	</value>
      <webElementGuid>6f69dd27-aed7-474a-ad15-33038d1b5ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Template_Search_Expand_Options&quot;)</value>
      <webElementGuid>6f94fe01-948d-4e65-bc19-f94fd85f2e9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='Template_Search_Expand_Options']</value>
      <webElementGuid>bf449c93-a55e-4fd1-a58d-206a37bfc2e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Any_5_0']/div[5]/a</value>
      <webElementGuid>15da98b8-a51f-4c8c-b4a9-40afef27bc14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'限制條件')]</value>
      <webElementGuid>b52704af-41f7-420e-a0fb-996982ffbd3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='查詢條件'])[1]/following::a[1]</value>
      <webElementGuid>2564ea01-1db9-43f4-ae38-df519aac6410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='上傳條碼號'])[1]/following::a[3]</value>
      <webElementGuid>7948f2f8-a848-4b0f-8090-4aba49899e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='限制條件'])[2]/preceding::a[3]</value>
      <webElementGuid>2af1c70d-be56-4f0e-8114-d9376a9e27ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='書目性質:'])[1]/preceding::a[4]</value>
      <webElementGuid>4b282354-f75d-4094-a394-27067093a81a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='限制條件']/parent::*</value>
      <webElementGuid>ae16df4f-f068-4ff4-9006-a6e5fe2fec91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:ExpandOptions()')]</value>
      <webElementGuid>997ee97a-c3f4-4176-b039-b60a49ecf316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>0bab7cdc-9c90-43b6-a254-474a30491bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:ExpandOptions()' and @id = 'Template_Search_Expand_Options' and (text() = '
		                    		限制條件
		                    	' or . = '
		                    		限制條件
		                    	')]</value>
      <webElementGuid>7a48969c-d0a9-481c-afc7-074f4e17ab7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
