<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__RadioGroup_2</name>
   <tag></tag>
   <elementGuidId>c164c5c7-8068-4876-b51d-f9131f6ccadb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RadioGroup_21</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RadioGroup_21']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4fe11351-f31a-45d1-ba0e-6534dd28b89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7d2ec233-4ff8-452e-af4b-9f2699929141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RadioGroup_2</value>
      <webElementGuid>d3aca8fe-50f3-4f2f-9041-f4572ebdff46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RadioGroup_21</value>
      <webElementGuid>d184df10-fb82-4098-8fd2-7452beb5d640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>428da3b0-f9d7-47b8-82b8-27ef626c6305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>tapestry.byId('RadioGroup_2').onChange(1);</value>
      <webElementGuid>ab59cd7c-cdc3-4d9f-a81d-1f170e8a5dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RadioGroup_21&quot;)</value>
      <webElementGuid>e4aaa8a6-a471-49ee-9077-0891f2e89ff4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RadioGroup_21']</value>
      <webElementGuid>e82d8f16-fda9-4d5f-8332-6a0c8062b68c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='RadioGroup_2']/input[2]</value>
      <webElementGuid>ad9becd5-f798-4081-b476-2a7a2712d207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[20]/td[2]/span/input[2]</value>
      <webElementGuid>0a5d67d9-2866-4851-9f14-2d9b27fd3906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'RadioGroup_2' and @id = 'RadioGroup_21']</value>
      <webElementGuid>5bb1d2a0-8fe6-4af1-b048-126289ba4360</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
