<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_</name>
   <tag></tag>
   <elementGuidId>6be0a7b4-dbfd-4930-bd30-c6a99e121193</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PropertySelection_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PropertySelection_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a237dea5-8ffb-4568-b0cd-626785ce2e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PropertySelection_1</value>
      <webElementGuid>2b26f3a9-63e1-495d-ae49-6211e24f239f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PropertySelection_1</value>
      <webElementGuid>e9b1404e-8988-465d-9d6c-1c90e9069015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>syncSelect1</value>
      <webElementGuid>42fa27b9-eb6e-4b84-9389-7ef62decd38f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
停權
罰款
</value>
      <webElementGuid>ba7796cd-34b8-40c3-af5f-aa2d3f21006c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PropertySelection_1&quot;)</value>
      <webElementGuid>2681e294-bce0-4403-8bfc-58fbe4318fa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PropertySelection_1']</value>
      <webElementGuid>b897a990-a661-48fa-baf5-8268e4b1fc79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EquPolicyEditor_0']/table/tbody/tr[13]/td[2]/select</value>
      <webElementGuid>3bc60f49-6278-44b8-9c83-0df5549b6412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='預設違規政策:'])[1]/following::select[1]</value>
      <webElementGuid>6f028865-2e6f-48ca-a96e-2cf225547ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='借用罰則設定'])[1]/following::select[1]</value>
      <webElementGuid>06164782-05f4-46ce-8c54-c227f3a16325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='每交易單位處罰計點數:'])[1]/preceding::select[1]</value>
      <webElementGuid>32d4a5ee-0e84-4046-9107-ca3464d0f014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='點數轉換金額:'])[1]/preceding::select[1]</value>
      <webElementGuid>08b8aa51-4623-400e-b310-48b71aba3571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td[2]/select</value>
      <webElementGuid>c224a9c6-b539-4d64-979c-84cf56203c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'PropertySelection_1' and @id = 'PropertySelection_1' and (text() = '
停權
罰款
' or . = '
停權
罰款
')]</value>
      <webElementGuid>b669c899-437b-4b1a-b9d5-fd232031d56f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
