<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ (1)</name>
   <tag></tag>
   <elementGuidId>1cb5b193-4c74-48ee-bba6-911d758ff66e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b752da28-54f5-4f33-8fe3-b2dd8e7e16ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_1</value>
      <webElementGuid>75e76558-de86-4359-8b7c-1ae75f98ad7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>butonsub</value>
      <webElementGuid>c44939ba-441e-4789-a3d7-c0c7c90756d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/ImportPreview,$PopupBorder.$DirectLink_1.sdirect</value>
      <webElementGuid>85cd1c9c-35da-4bf6-839f-939392ead5ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				  是  
			</value>
      <webElementGuid>c9c1f940-ee8a-4cd8-90d4-0f57f1911411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_1&quot;)</value>
      <webElementGuid>c06def65-18f2-4880-8568-c2c7b0297757</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_1']</value>
      <webElementGuid>c149b189-49f9-4738-9a21-858d80d4c2c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CloseReminderDialog_content']/table/tbody/tr/td[2]/a</value>
      <webElementGuid>7dbc92e7-6ae3-414f-9c47-f7a37d6afad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'是')]</value>
      <webElementGuid>1d545848-ec7e-42a1-9f42-aec8815c2a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='提示'])[1]/following::a[1]</value>
      <webElementGuid>7a4b7d67-41c1-4b20-a12c-275943aefff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ISO 預覽'])[1]/following::a[2]</value>
      <webElementGuid>2b3174aa-d1eb-4065-8200-aa2ce2ed7c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/ImportPreview,$PopupBorder.$DirectLink_1.sdirect')]</value>
      <webElementGuid>e2ec6a26-fbad-4b4a-b102-8c88b70368e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>394286d9-3652-4411-8cd4-d4e4cf67778c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_1' and @href = '/inspireapp/ImportPreview,$PopupBorder.$DirectLink_1.sdirect' and (text() = '
				  是  
			' or . = '
				  是  
			')]</value>
      <webElementGuid>9a1841de-e6a0-43f6-8c3f-df5ea82b8576</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
