<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>319e5d10-0b26-40e8-b41f-30ea03f18e46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#content-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d2a45531-4439-46b1-8dc2-ef22a787f44d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content-button</value>
      <webElementGuid>4519b18e-951a-41db-b6b3-6d6de7c5f371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>f557c3c0-ed6d-43e6-b37b-dfd5d584419e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	        	請輸入查詢語
	        </value>
      <webElementGuid>433e9f6b-9a15-454a-9547-9fbeb56cadd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-button&quot;)</value>
      <webElementGuid>ff23ed73-877e-4da7-a411-3145b53bcd4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='content-button']</value>
      <webElementGuid>8fdd07bc-f402-4cba-846d-4cf6b3ce432e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TinreadMessageDialog_content']/div</value>
      <webElementGuid>5feab9d3-dd85-4e6f-9ddd-65513fbfade9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='提示'])[1]/following::div[2]</value>
      <webElementGuid>cfb520ba-15f4-4f01-93d7-6b6eb0728af3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='確定'])[1]/preceding::div[1]</value>
      <webElementGuid>b3212b87-6f1d-4f93-adfa-6a69a21d7f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright© 2016 iNspire 4.4.0-SNAPSHOT by Claridy Solutions, Inc. All rights reserved.'])[1]/preceding::div[3]</value>
      <webElementGuid>050a41b4-fa07-470b-83b4-03d98d129ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='請輸入查詢語']/parent::*</value>
      <webElementGuid>dc376888-1005-4d36-a5d7-421e04557065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div</value>
      <webElementGuid>623c5f8a-d666-41a9-a098-eccd4ca9b028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'content-button' and (text() = '
	        	請輸入查詢語
	        ' or . = '
	        	請輸入查詢語
	        ')]</value>
      <webElementGuid>7fe2b252-4821-466d-9c65-fa0e42fb1054</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
