<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__datePickerImg</name>
   <tag></tag>
   <elementGuidId>af414b11-93e4-4cad-b56a-faf72021f3b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='reportParamForm']/table/tbody/tr/td[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.datePickerImg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>12570dcb-545c-40d6-94e6-f837cbc4947b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/inspireapp/assets/static/org/apache/tapestry/form/DatePickerIcon.png</value>
      <webElementGuid>ee5d6f4f-1bfa-42ee-a22a-75d3585cc2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Click on icon to choose a date/time value.</value>
      <webElementGuid>957ad0db-8399-4603-b43d-8f62972f8aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e22ea42d-6099-4468-a298-8bf9604b2a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datePickerImg</value>
      <webElementGuid>14b26c9a-9d3a-45be-a4a9-a964d13fd29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reportParamForm&quot;)/table[@class=&quot;table1&quot;]/tbody[1]/tr[1]/td[2]/a[1]/img[@class=&quot;datePickerImg&quot;]</value>
      <webElementGuid>5978586b-ffc7-4f23-89c4-cbeb19cd90ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='reportParamForm']/table/tbody/tr/td[2]/a/img</value>
      <webElementGuid>d4f6ed9e-e4d0-4bc5-b1ca-9b9811197d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Click on icon to choose a date/time value.']</value>
      <webElementGuid>cb6135bf-372a-460d-ba28-ffe8e681addb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>24431871-c7ae-46fb-aaf5-e34425d095ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/inspireapp/assets/static/org/apache/tapestry/form/DatePickerIcon.png' and @alt = 'Click on icon to choose a date/time value.']</value>
      <webElementGuid>205020f6-39b5-45ad-9633-93cc02c75033</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
