<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_DatePicker</name>
   <tag></tag>
   <elementGuidId>485fc898-187b-42be-b07e-385619a597f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DatePicker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DatePicker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c2bd8f3-d1f1-4ab9-b26c-1ef34d65127d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>716e281b-fe3e-4d59-8a26-e0ab31d01ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DatePicker</value>
      <webElementGuid>842e9a96-2a0f-4327-b464-68564918c4a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2024/03/16</value>
      <webElementGuid>6cf105a3-e109-48bc-b9aa-cd497de70701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>yyyy/MM/dd</value>
      <webElementGuid>fa311164-d256-49a6-8ab7-6a8ebfb2e955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DatePicker</value>
      <webElementGuid>ff87d497-27da-4d91-87a7-53089cb11dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DatePicker&quot;)</value>
      <webElementGuid>0b1675bd-6a70-4d1a-867f-8df08457e961</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DatePicker']</value>
      <webElementGuid>471a65d2-b567-4261-a29c-375998bf8767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showSearch']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>54d5d7e9-aa7c-4181-82d5-67121e9d65ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>7c73196a-5f2c-4041-afa9-7a509a6a486c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'DatePicker' and @title = 'yyyy/MM/dd' and @id = 'DatePicker']</value>
      <webElementGuid>9f600220-cf74-4af4-9a0d-d3962a70332c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
