<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(15trunk)_member_id</name>
   <tag></tag>
   <elementGuidId>9c09217e-8451-4908-acf0-9c8dc071c5f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#member_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='member_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c07bbad6-d01c-4b10-a8f7-578c6c32bc6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b87dd7b9-49de-40d8-9af2-f7485c01b961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>member_id</value>
      <webElementGuid>f00ffdd7-83e6-4fd9-b04c-d72bbe3a6926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>member_id</value>
      <webElementGuid>33f92216-52b9-46e9-8d34-3423618af18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>1e3d18c9-4b3f-43f5-8585-668471ad6444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.value='';</value>
      <webElementGuid>79755c5c-5ea3-40c0-a21c-7b7ca2f29a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>請輸入帳號</value>
      <webElementGuid>b9cfd8e4-7db6-4cd6-832e-994fa73ca1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;member_id&quot;)</value>
      <webElementGuid>5cd076ba-ceb9-4206-8075-266199d9ec7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='member_id']</value>
      <webElementGuid>a85c36a3-5324-482d-82ad-e5fd5e7cd58f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='logon']/table/tbody/tr/td/input</value>
      <webElementGuid>3f4605a7-ece5-4b2b-9d56-36d31188ebe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>62731a69-19c8-4f99-9257-156ab4fdef02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'member_id' and @id = 'member_id' and @placeholder = '請輸入帳號']</value>
      <webElementGuid>d31f7e62-d1c0-443c-97ce-068663275a13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
