<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__field1</name>
   <tag></tag>
   <elementGuidId>cbbd30af-162b-47ef-8104-b7dd16560838</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f965b351-5897-4d44-a399-571bae5849d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de17e092-8741-4ee8-8513-df0d0a10d317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c7dc238b-24f6-489f-80f0-fe1ead555214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field1</value>
      <webElementGuid>509fae4d-2246-49fa-8a57-1e746bf6f5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field1</value>
      <webElementGuid>edbb6cfe-0ea6-411f-b722-43dcd4183be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_mare</value>
      <webElementGuid>624b0b18-70ff-4729-84ca-ad3f7278b7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>VirtualKeyboard.attachInput(this); diacriticInsert(this);</value>
      <webElementGuid>7d0d8dfe-22c1-4014-b77b-c8fb3b3b0489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field1&quot;)</value>
      <webElementGuid>e6182def-6c31-4b1f-bebc-622e1fdcf1e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field1']</value>
      <webElementGuid>bba08461-cea8-4bf6-8093-131f1c64d9d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='inputField1']/nobr/input</value>
      <webElementGuid>e0ae09cd-2195-4e50-95ee-c777ced98857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nobr/input</value>
      <webElementGuid>c1387e78-a8ba-4508-be7b-4689def97002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field1' and @name = 'field1']</value>
      <webElementGuid>1837066f-b123-4100-adab-8c3d0178cf65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
