<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3</name>
   <tag></tag>
   <elementGuidId>e3407d9a-05a3-45cb-9127-18d283798d18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='LinkSubmit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LinkSubmit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3e30c82c-69c7-4f56-bb98-55a01531a007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/BespeakAuditing,searchComponent.searchForm.sdirect?updateParts=crsBespeakAuditing</value>
      <webElementGuid>fc6de2a4-4987-4811-948d-63e27644bea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>tapestry.form.submit('searchForm', 'LinkSubmit',{async:true,json:false,url:this.href}); return false;</value>
      <webElementGuid>d615ec38-43d8-4224-87cc-45518ca666d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LinkSubmit</value>
      <webElementGuid>e96002bf-c64d-4712-88ef-eb81def2242d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>butonsub</value>
      <webElementGuid>a8633910-9fe7-476e-b1b8-ff90b499e11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		批次駁回
	</value>
      <webElementGuid>609ff499-8529-4cba-8316-c5eeec40b96f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LinkSubmit&quot;)</value>
      <webElementGuid>bc211524-3a26-4862-9081-34e3615dd824</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='LinkSubmit']</value>
      <webElementGuid>30c347b9-bd7a-4de4-85a4-bbae61475bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='If_291']/div[2]/div/a</value>
      <webElementGuid>c34eb77b-1c51-4ea1-8cf0-ba917a826a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'批次駁回')]</value>
      <webElementGuid>0265d785-027b-4195-b89c-d9c36ddfcfb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GO'])[2]/following::a[1]</value>
      <webElementGuid>02d8b50b-b204-4d4a-84f6-650aaeecfa0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='批次核准'])[1]/preceding::a[1]</value>
      <webElementGuid>78cf107b-b9bd-474c-8dd6-3b5c9f046fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::a[2]</value>
      <webElementGuid>3c3d36fe-3618-4ba1-96ce-e82b5c426ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='批次駁回']/parent::*</value>
      <webElementGuid>e3ad1534-cd46-4657-a697-46c17bcf3bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/BespeakAuditing,searchComponent.searchForm.sdirect?updateParts=crsBespeakAuditing')]</value>
      <webElementGuid>af175659-d381-4a49-a80c-c332470ecf76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>c3fc0873-a990-4aa9-ab55-4e68cee91298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/BespeakAuditing,searchComponent.searchForm.sdirect?updateParts=crsBespeakAuditing' and @id = 'LinkSubmit' and (text() = '
		批次駁回
	' or . = '
		批次駁回
	')]</value>
      <webElementGuid>9ed75b3c-aef8-4476-bbd5-9f9954340795</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
