<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>6a83fcce-0f10-4f38-8f80-950832d767a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.current > ul.ssub_nav_ul > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu2']/ul[6]/li[2]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed762c05-1854-4e58-8031-20884d759d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/maintain_classify?init=1</value>
      <webElementGuid>ff513b62-ab02-40e5-92b1-21e54e5cdb26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>分類維護</value>
      <webElementGuid>24cdb89f-461d-4fe2-a3c0-0f9cd1ed1fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2&quot;)/ul[@class=&quot;sub_nav_ul&quot;]/li[@class=&quot;current&quot;]/ul[@class=&quot;ssub_nav_ul&quot;]/li[1]/a[1]</value>
      <webElementGuid>d2eac0ad-6b48-458f-a287-984c70ee41aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2']/ul[6]/li[2]/ul/li/a</value>
      <webElementGuid>795d441b-4816-4e94-838a-16f72f5b54e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'分類維護')]</value>
      <webElementGuid>085bac03-0fea-4b8f-800f-bbdff5874b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='借用記錄'])[1]/following::a[2]</value>
      <webElementGuid>b524a12e-a40d-4742-9eb7-9c2979d90453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='預約記錄'])[1]/following::a[3]</value>
      <webElementGuid>17c2cabb-4203-4ffb-b477-75b99c837fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='單項維護'])[1]/preceding::a[1]</value>
      <webElementGuid>1d9f8ec2-7db6-49c7-a8ee-f5a5f5e21789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='流通政策維護'])[1]/preceding::a[3]</value>
      <webElementGuid>b1a71ab4-a9f8-4000-b511-dc5529a18e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='分類維護']/parent::*</value>
      <webElementGuid>ffbdff31-5d91-4012-b811-15b2f6853f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/maintain_classify?init=1')]</value>
      <webElementGuid>72be82b4-cb58-45b0-87f8-811903ecdecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[6]/li[2]/ul/li/a</value>
      <webElementGuid>7294b10e-bb4e-4ef4-b806-fb27d74a8520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/maintain_classify?init=1' and (text() = '分類維護' or . = '分類維護')]</value>
      <webElementGuid>3035a663-d427-4864-a8c0-71ab5045bb3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
