<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__rootCheck</name>
   <tag></tag>
   <elementGuidId>0cfa7f1b-dd48-4dbb-8018-e6af32f9a762</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rootCheck</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rootCheck']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba8f9c8a-de41-46e9-8b2e-daae0459bc00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lable_list_input</value>
      <webElementGuid>e0b65cd0-a577-4735-8f88-613100e42143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8f8495d6-8054-4c99-946d-c0ba8f3f66fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rootCheck</value>
      <webElementGuid>45da898e-bb3f-47a6-a004-5a003ff9b1de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:selectMaterialTypeAllForTrac_1387('searchForm');</value>
      <webElementGuid>f8397194-fc49-4c11-853f-f9a34255cc9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>411dc5bd-6a03-4684-8e5c-6ae34dd082bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rootCheck&quot;)</value>
      <webElementGuid>68d44e69-e3d4-494e-a0ad-b43b9c7a1400</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rootCheck']</value>
      <webElementGuid>b4dc8b32-af9f-4dfb-ba73-bab472b474e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showSearch']/table/tbody/tr[6]/td[2]/ul/li/input</value>
      <webElementGuid>ecb5a52c-e647-4502-8d2b-3939db87621d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>003d7d98-5a3f-423b-94ab-4acd993608f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'rootCheck']</value>
      <webElementGuid>0a8eab31-da71-471f-a0b5-dff3e13e484b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
