<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3</name>
   <tag></tag>
   <elementGuidId>8f5a02c7-6e9a-4f98-ab98-4fbe0fe09add</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>027a6dea-fed0-4e1c-a09a-01f22d09c085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_1</value>
      <webElementGuid>89300138-b3c8-41f9-8fbf-a30066c9dbd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttons</value>
      <webElementGuid>9c504fe9-abd9-49df-8251-19759199ba17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/UseCountStatement,$DirectLink.sdirect?updateParts=ReportStatus</value>
      <webElementGuid>05815d03-6082-468b-bfcd-bfe382e70971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return tapestry.linkOnClick(this.href,'DirectLink_1', false)</value>
      <webElementGuid>97fe969e-ae68-4544-9c59-89aca2512c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					報表狀態 
				</value>
      <webElementGuid>b7de6d31-73f0-4b30-80b8-f878c15b0ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_1&quot;)</value>
      <webElementGuid>e7e2f4f6-f0eb-4024-af30-582c8be8eb14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_1']</value>
      <webElementGuid>e6a53a54-53cd-4e5a-82ca-2b2d3c680447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div[2]/div[2]/div/a[2]</value>
      <webElementGuid>2ea54833-3559-436c-81e1-1238f8ad1f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'報表狀態')]</value>
      <webElementGuid>5962fa6a-a48a-4c82-85f7-a90bd20c157a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='產生報表'])[1]/following::a[1]</value>
      <webElementGuid>79aa0e61-789c-470a-87cc-f98c657c0fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='報表輸出:'])[1]/following::a[2]</value>
      <webElementGuid>7abda794-59c8-44e7-a3fe-2e4561b412af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='報表狀態'])[2]/preceding::a[1]</value>
      <webElementGuid>fcec4bc0-11d7-404e-aae5-8ffed7f58557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='報表狀態']/parent::*</value>
      <webElementGuid>db51a103-fff8-431d-9dcb-d1c5558219a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/UseCountStatement,$DirectLink.sdirect?updateParts=ReportStatus')]</value>
      <webElementGuid>1e01620b-2a18-4679-9283-bfe5abc7727e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a[2]</value>
      <webElementGuid>d3ec5d58-e99d-45ce-8c0b-ba6b0e698c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_1' and @href = '/inspireapp/UseCountStatement,$DirectLink.sdirect?updateParts=ReportStatus' and (text() = '
					報表狀態 
				' or . = '
					報表狀態 
				')]</value>
      <webElementGuid>bf570b7f-35d0-4a5e-9d49-93697f5ef9e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
