<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__formSubmitSearch</name>
   <tag></tag>
   <elementGuidId>f0dbba1d-f8a4-49e7-a7cb-ff247d1848fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formSubmitSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formSubmitSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f17dc784-368e-4c79-9787-83aa05706b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ef286815-7f53-4241-818c-9d6dcb458d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formSubmitSearch</value>
      <webElementGuid>e115f3bf-c62a-4413-880e-6606b423ed3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formSubmitSearch</value>
      <webElementGuid>43ee3105-5ca2-44f5-b768-b63a6a9e6971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>查詢</value>
      <webElementGuid>7442f054-787d-4c48-ac30-718c91831424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttons buttons_work</value>
      <webElementGuid>c6834173-c1b2-43e3-8b35-57db4e7aaf27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>086f9b52-1206-4f0c-b13d-ec6775a66fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSubmitSearch&quot;)</value>
      <webElementGuid>f00a007c-509f-46de-a3a0-5104eb17aa09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formSubmitSearch']</value>
      <webElementGuid>0feafc0f-6323-4196-b465-a21cca99e59c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HiddenSearch']/div/div[2]/p/input</value>
      <webElementGuid>fbb4c3e2-ae97-419c-9068-cebe5b9a82f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>85cebe60-c078-4cd9-b366-9e0d736dcca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'formSubmitSearch' and @id = 'formSubmitSearch']</value>
      <webElementGuid>4c38cd32-5b27-4bc0-b3a5-b729c4bec1ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
