<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a</name>
   <tag></tag>
   <elementGuidId>725795dc-77ac-4615-89a6-5bf61a35240a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='editForm']/table/tbody/tr[6]/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b0afffae-4622-4b2f-9aab-def5617a6a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:calendar_dateEnd.toggle(tapestry.byId(&quot;dateEnd&quot;));</value>
      <webElementGuid>32e7fd7c-1e8d-4a76-976a-97da8639aac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editForm&quot;)/table[@class=&quot;table2&quot;]/tbody[1]/tr[6]/td[2]/a[1]</value>
      <webElementGuid>72b014f1-405b-413e-87ab-d85be55027e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='editForm']/table/tbody/tr[6]/td[2]/a</value>
      <webElementGuid>12aca463-fc97-42db-a6bb-83eeaad0976e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='下架日期'])[2]/following::a[1]</value>
      <webElementGuid>d90227b7-a6d5-4bb9-a316-e43ff6035053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='上架日期'])[2]/following::a[2]</value>
      <webElementGuid>6d4cc6db-81e1-489b-8ec0-52ac2def9069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='修改/存檔'])[1]/preceding::a[1]</value>
      <webElementGuid>7da8f010-53d3-46c0-acbb-c89147ff03d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='取消'])[1]/preceding::a[2]</value>
      <webElementGuid>6c2a7432-42cc-4549-bddc-71650a7c42ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:calendar_dateEnd.toggle(tapestry.byId(&quot;dateEnd&quot;));')]</value>
      <webElementGuid>ca197e1a-0ae9-4078-bd72-1a8db446aac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/a</value>
      <webElementGuid>281e1af1-80e4-4d1a-9fed-f9b6c329278f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:calendar_dateEnd.toggle(tapestry.byId(&quot;dateEnd&quot;));']</value>
      <webElementGuid>0cc71f88-6da7-49a8-b983-2378c848f894</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
