<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__jwindow.dlocations1</name>
   <tag></tag>
   <elementGuidId>47566b73-26a2-4355-9a96-ea53ec8b1436</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='jwindow.dlocations1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9d12604d-d904-4279-b658-e44022edf23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jwindow.dlocations1</value>
      <webElementGuid>f1c1c8e5-0251-4b61-ae5e-ead8716d90d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/inspireapp/images/plusbottom.gif</value>
      <webElementGuid>464c661e-5094-49bf-bffd-361361980d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jwindow.dlocations1&quot;)</value>
      <webElementGuid>51a5785d-9359-4a8b-9273-9c19f08fda27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='jwindow.dlocations1']</value>
      <webElementGuid>ade0634d-f86c-4cb1-a34f-150789eabc92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dwindow.dlocations0']/div/a/img</value>
      <webElementGuid>b60ef35e-7036-42cf-9330-e5fb64c043be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/img</value>
      <webElementGuid>e61e87ef-af95-4dad-9fb9-a18407aad15e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'jwindow.dlocations1' and @src = '/inspireapp/images/plusbottom.gif']</value>
      <webElementGuid>4578a088-d529-4e0d-a22a-d7e025775f3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
