<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3</name>
   <tag></tag>
   <elementGuidId>41bb8b28-89b8-4ee1-bcb0-a0727b620654</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>42abd8ad-c8eb-4fd1-91c4-4a8629dc8562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_1</value>
      <webElementGuid>eaf4f595-5a02-445a-8168-d6dcec21df0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttons</value>
      <webElementGuid>1e0969f2-987e-4b44-b0b8-eebfeed6f145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/ClaimStatsBySupplier,$DirectLink.sdirect?updateParts=ReportStatus</value>
      <webElementGuid>4591b82a-2360-4e58-9492-9e53fb8ae882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return tapestry.linkOnClick(this.href,'DirectLink_1', false)</value>
      <webElementGuid>66add808-29c9-473c-847a-4ad9667f5287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 報表狀態 </value>
      <webElementGuid>22dde375-d6ce-4cf4-94a1-1b81cfc7917a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_1&quot;)</value>
      <webElementGuid>5155a084-742c-4009-b634-093ca7d66ece</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_1']</value>
      <webElementGuid>4edaa6ee-83d5-4db2-8c2d-fac68783471b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div[2]/div[2]/div/a[2]</value>
      <webElementGuid>b9020600-6787-40ed-86ca-9832487ce9a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'報表狀態')]</value>
      <webElementGuid>0fc6a8e5-efb0-4abc-9182-4433df5166b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='產生報表'])[1]/following::a[1]</value>
      <webElementGuid>3bcda2aa-5e11-4f93-9443-88d302f4290b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='報表輸出:'])[1]/following::a[2]</value>
      <webElementGuid>dd37b99f-5afc-4f47-bf6c-794c8ad0e966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='報表狀態'])[2]/preceding::a[1]</value>
      <webElementGuid>6dbb0f12-7a30-45da-ae65-d2d945a7fbb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='報表狀態']/parent::*</value>
      <webElementGuid>f397ea6c-4fe3-449b-8363-a5563e748ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/ClaimStatsBySupplier,$DirectLink.sdirect?updateParts=ReportStatus')]</value>
      <webElementGuid>40de9de6-cd0e-4b38-99e4-bd89c6acba65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a[2]</value>
      <webElementGuid>31e30483-9cd7-4026-a81b-62c169f68424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_1' and @href = '/inspireapp/ClaimStatsBySupplier,$DirectLink.sdirect?updateParts=ReportStatus' and (text() = ' 報表狀態 ' or . = ' 報表狀態 ')]</value>
      <webElementGuid>684a7635-86c7-4df3-a1db-04cee4c780b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
