<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__FieldMode_0_selectImage</name>
   <tag></tag>
   <elementGuidId>8a637383-0800-4d6e-ac7c-0a194f8ecb27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;FieldMode_0_selectImage&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@name='FieldMode_0_selectImage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e4f5936f-846c-4fe2-a794-4f200a8815ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://10.11.20.15/inspireapp/assets/static/org/apache/tapestry/contrib/palette/select_right.gif</value>
      <webElementGuid>8769ced8-4772-4d22-9703-bdfba805e3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>4315b91f-d0f2-4022-a3bb-3e4af8d03f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FieldMode_0_selectImage</value>
      <webElementGuid>70a48560-31fe-4be4-ae8a-406a9ba89496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FieldForm&quot;)/fieldset[1]/table[1]/tbody[1]/tr[1]/td[2]/table[@id=&quot;Any_1&quot;]/tbody[1]/tr[1]/td[@class=&quot;controls&quot;]/a[@id=&quot;Any_0_0&quot;]/img[1]</value>
      <webElementGuid>c4052272-0377-4736-be0d-561ec62c6e25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='FieldMode_0_selectImage']</value>
      <webElementGuid>de577e5f-2f2c-4671-ada6-950fcfd41503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='Any_0_0']/img</value>
      <webElementGuid>50952e5d-7b56-4258-bcbc-335213a9437b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Select']</value>
      <webElementGuid>2b337fe0-8417-4a9a-ae8b-ed0e1c70b621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/a/img</value>
      <webElementGuid>41f6455d-c8da-4085-ad33-66fe904d2e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://10.11.20.15/inspireapp/assets/static/org/apache/tapestry/contrib/palette/select_right.gif' and @alt = 'Select' and @name = 'FieldMode_0_selectImage']</value>
      <webElementGuid>5b5c0759-9462-4741-8f1e-deea3d00f2f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
