<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1</name>
   <tag></tag>
   <elementGuidId>4234796f-97d0-438c-a502-ba854db48f2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.sub_nav_ul > li:nth-of-type(4) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu2']/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d1c649b-72fe-4dce-82d9-6dc68816f545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/cautari_recente?init=1</value>
      <webElementGuid>4415bed0-5526-48d8-b57f-121432f10ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>最近的查詢</value>
      <webElementGuid>327dcdb0-b5af-40b2-b1b9-4fb6741a6bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2&quot;)/ul[@class=&quot;sub_nav_ul&quot;]/li[4]/a[1]</value>
      <webElementGuid>6acf2a3d-3caa-4365-9e4c-679345485ea7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2']/ul/li[4]/a</value>
      <webElementGuid>89af57ef-752a-4382-b26a-b4e85f0e9625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'最近的查詢')]</value>
      <webElementGuid>e21ab1c5-8901-4702-883b-e767de115d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FRBR查詢'])[1]/following::a[1]</value>
      <webElementGuid>da3e6a6b-5654-4161-a148-29c58b2a98ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='進階查詢'])[1]/following::a[2]</value>
      <webElementGuid>7126e5a6-51be-4aa4-badc-eee61cf3adca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='已儲存的記錄'])[1]/preceding::a[1]</value>
      <webElementGuid>e093225d-fff7-4642-9983-8d7a6c38ad4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FRBR作品'])[1]/preceding::a[2]</value>
      <webElementGuid>fd9b8648-3b2e-4b7a-91c0-46bea6ddf5dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='最近的查詢']/parent::*</value>
      <webElementGuid>1b11215f-da39-4518-83b8-89bacf4b4554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/cautari_recente?init=1')]</value>
      <webElementGuid>dc5ee5dd-d875-475c-8c52-50b9bef61d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[4]/a</value>
      <webElementGuid>cdb181a3-2642-4c00-8c36-b4e9e41fe46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/cautari_recente?init=1' and (text() = '最近的查詢' or . = '最近的查詢')]</value>
      <webElementGuid>ae6a5e8d-2534-492b-8923-2619052bcc7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
