<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_DatePicker_0</name>
   <tag></tag>
   <elementGuidId>08989997-88d2-4212-af63-20fa2042868c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DatePicker_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DatePicker_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbbd0f16-d331-494d-8537-35cb0098dd9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8838efcd-4c70-48c6-9b8b-03c0eefb5a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DatePicker_0</value>
      <webElementGuid>272b89d6-ec79-4189-9621-ccf5ef57f848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>yyyy/MM/dd</value>
      <webElementGuid>7e0e3398-83d2-4edf-b958-aff0f1f83896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DatePicker_0</value>
      <webElementGuid>01538ba1-8732-4fe3-a415-3bff4646e62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DatePicker_0&quot;)</value>
      <webElementGuid>9ddfcf07-87ef-497c-b972-bcb4d3fcd084</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DatePicker_0']</value>
      <webElementGuid>d5727ec0-c513-4f9c-b427-b0040bba2ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/table/tbody/tr/td[2]/input[2]</value>
      <webElementGuid>c068a8ce-1b7e-49a4-a8a2-3d4e7b58200a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[2]</value>
      <webElementGuid>9301fa47-14ab-47ab-978e-c6c57dc27743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'DatePicker_0' and @title = 'yyyy/MM/dd' and @id = 'DatePicker_0']</value>
      <webElementGuid>9c6ba3f3-0c0b-4535-84bb-bb3a69433bfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
