<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(15trunk)_Submit</name>
   <tag></tag>
   <elementGuidId>38c48b0b-2834-4821-b38d-e4948383410b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b358f19-754d-4941-bbe3-eeefbce92a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>aa8392bd-0a89-4025-b281-5acea7e7ae86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>56f81088-47d4-450b-a254-358b5b440f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>501c17b1-3614-42cd-8b98-3e8a594eea98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>login(dojo.byId('logon'))</value>
      <webElementGuid>9ad82324-d2f0-4c0d-9e13-addccdf083d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>登入</value>
      <webElementGuid>3e311943-5f03-4d1a-8c64-0752c3426ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login_btn</value>
      <webElementGuid>e111c872-48a8-4f57-9505-457d6183e63f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Submit&quot;)</value>
      <webElementGuid>b648d479-a516-408e-95fd-063690d0e11a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Submit']</value>
      <webElementGuid>e8cea5bc-9de3-45bc-ab59-39f5e80afa7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='logon']/table/tbody/tr[3]/td/button/input</value>
      <webElementGuid>9789e499-1e00-471c-b4ce-29fc49abc1ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/input</value>
      <webElementGuid>794ef811-5281-4531-aac2-f9c21a525167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'Submit' and @id = 'Submit']</value>
      <webElementGuid>93501478-7855-499a-bfe9-c2f0ebd0b96d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
