<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>01099e80-aeb4-4fd7-a6bd-d6e51740716e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.current > ul.ssub_nav_ul > li:nth-of-type(6) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu2']/ul[11]/li[6]/ul/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e06be451-9ee7-44df-9c2d-b3cfc3e62a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/POStatsBySupplier.page?init=1</value>
      <webElementGuid>1dd99b8a-5459-4283-944d-748a431c665a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>書商累計訂購次數</value>
      <webElementGuid>64f0921a-3ff4-4737-b562-3afd4cd4ab5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2&quot;)/ul[@class=&quot;sub_nav_ul&quot;]/li[@class=&quot;current&quot;]/ul[@class=&quot;ssub_nav_ul&quot;]/li[6]/a[1]</value>
      <webElementGuid>e72bfe9d-fe3e-4473-b804-875d4b661922</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2']/ul[11]/li[6]/ul/li[6]/a</value>
      <webElementGuid>64fecd84-6bfe-49a5-ae76-1e7e2b33f6ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'書商累計訂購次數')]</value>
      <webElementGuid>704a8346-69e2-427d-96c4-07351f2253eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='書商催缺次數'])[1]/following::a[1]</value>
      <webElementGuid>d7ed909b-44d6-4740-9cb0-1aa8d47da0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='書商到書率'])[2]/following::a[2]</value>
      <webElementGuid>bc128e50-2488-440a-a2be-4df050634bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='期刊訂費漲幅統計'])[1]/preceding::a[1]</value>
      <webElementGuid>acb03b01-259e-409a-a3cb-4a772f53ccc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='逾期違約金統計'])[1]/preceding::a[2]</value>
      <webElementGuid>7c9301d8-ee9e-4c4a-ad3a-602a69dcbbea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='書商累計訂購次數']/parent::*</value>
      <webElementGuid>47e24015-44fd-4ae2-9741-425f377e862b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/POStatsBySupplier.page?init=1')]</value>
      <webElementGuid>8399640d-c10f-4c5e-9274-e8d9487e6334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[11]/li[6]/ul/li[6]/a</value>
      <webElementGuid>b6a55788-723b-4383-af8d-7b0f9a61e890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/POStatsBySupplier.page?init=1' and (text() = '書商累計訂購次數' or . = '書商累計訂購次數')]</value>
      <webElementGuid>ac20c40b-9459-4f00-a1de-fa31efa04b3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
