<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>b1da73d9-08b4-4c9b-b1fd-bedb2bfa6dc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_0_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_0_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3588e3d1-881f-4bfd-bb8f-2781e06b1d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_0_0</value>
      <webElementGuid>e5c1bd03-6195-4bd1-96dd-64574ea282c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>butonsub</value>
      <webElementGuid>3bb6c10b-37da-49da-a888-7764e92e9e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/HoldingsStatusListReport,ReportsStatus.$DirectLink_0.sdirect?updateParts=ReportStatus</value>
      <webElementGuid>663dd316-2b7a-44bb-b6aa-4a6c1911d31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return tapestry.linkOnClick(this.href,'DirectLink_0_0', false)</value>
      <webElementGuid>fa221371-0f00-4224-aaaf-db79e72178ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
										關閉 
								</value>
      <webElementGuid>e0ce4fef-e2cd-4aee-82fe-30f18b536336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_0_0&quot;)</value>
      <webElementGuid>afe9070d-4629-4841-9ebf-6dcf0b67d845</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_0_0']</value>
      <webElementGuid>f1ce888f-3bf1-4cfc-ba27-de8f6a3ea277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='If_11']/div/table/tbody/tr/td/table/tbody/tr/td[2]/a</value>
      <webElementGuid>0bd319ae-4738-4852-9bfe-2a762013de08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'關閉')]</value>
      <webElementGuid>f10b44af-8aca-4926-b43c-9227ffca266b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='報表狀態'])[2]/following::a[2]</value>
      <webElementGuid>8abaa84e-6348-4baf-8e20-a52f8cd84224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='執行時間'])[1]/preceding::a[1]</value>
      <webElementGuid>2fbcf3ed-ad93-4586-a0a8-5556fd5a34b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/HoldingsStatusListReport,ReportsStatus.$DirectLink_0.sdirect?updateParts=ReportStatus')]</value>
      <webElementGuid>01af6c5a-d536-4104-912b-d1f32cd3b8c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td[2]/a</value>
      <webElementGuid>068b57ea-a443-44b2-b0b7-c1a0297ef18a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_0_0' and @href = '/inspireapp/HoldingsStatusListReport,ReportsStatus.$DirectLink_0.sdirect?updateParts=ReportStatus' and (text() = ' 
										關閉 
								' or . = ' 
										關閉 
								')]</value>
      <webElementGuid>03f23167-d069-4664-9165-43510c6fade2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
