<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(15trunk)_member_id</name>
   <tag></tag>
   <elementGuidId>a49fd9f1-229f-480d-be12-fd1b14162aac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='member_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#member_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f389946-3ad0-427b-860e-da0c2535bea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7fd8dfd-b20e-48e5-873d-e3e454928c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>member_id</value>
      <webElementGuid>9ac537f7-f295-4a5e-8edc-91e5b47ca24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>member_id</value>
      <webElementGuid>9785355e-5ea8-4524-b44b-5fc933762899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>1c6e2545-2e2e-4d1b-9299-82934bf30e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.value='';</value>
      <webElementGuid>3b06a67d-15b0-44a1-b5cb-4062f183b31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>請輸入帳號</value>
      <webElementGuid>b2ce8b09-bc3f-4c58-a3e7-a5d6dc142077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;member_id&quot;)</value>
      <webElementGuid>41df24d3-c00b-40f1-b4bc-5972dc6553f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='member_id']</value>
      <webElementGuid>12fbf5c6-d03c-4816-9187-c503c7750f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='logon']/table/tbody/tr/td/input</value>
      <webElementGuid>d2a50281-f495-4194-bc0d-3e61d12103d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>558c35fd-3a45-4373-b70f-5a003bcdec1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'member_id' and @id = 'member_id' and @placeholder = '請輸入帳號']</value>
      <webElementGuid>dc20d881-534b-4088-b010-cb2a44fb8950</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
