<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_</name>
   <tag></tag>
   <elementGuidId>fd8e5417-20b3-47a9-b965-00ea9c242541</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='sCriteria2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sCriteria2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ecef5981-5c75-4b25-9b69-1fe5e3eea8aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sCriteria2</value>
      <webElementGuid>78bdf1c4-3e98-47c4-8f3b-b1fcb306d092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sCriteria2</value>
      <webElementGuid>c1dc8658-315c-4cef-934e-aa0075cb337b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
條碼號
正題名
書名
作廢日期
報廢文號
報廢批號
報廢備註
執行館員姓名
執行館員帳號
到館日期
館員註記
採購註記
期刊註記
財產編號
</value>
      <webElementGuid>0e93fa97-50e7-4f32-b245-e4282cc0020c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sCriteria2&quot;)</value>
      <webElementGuid>513d25ae-50f0-4ad6-b437-d1ce96547a02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='sCriteria2']</value>
      <webElementGuid>c88f96e8-7cb5-4f75-b3e7-28bcf707ffa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='If_15']/select[2]</value>
      <webElementGuid>243578ff-2004-40e6-8580-ad1eccbc8b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='查詢條件'])[1]/following::select[4]</value>
      <webElementGuid>9a7a846d-f197-426a-a110-741e4d069494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='瀏覽'])[1]/following::select[4]</value>
      <webElementGuid>1cff6344-16d1-4a34-9238-66738daea961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='限制條件'])[1]/preceding::select[8]</value>
      <webElementGuid>b1a14c74-d482-4d9a-a11a-0c76af4e655d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='瀏覽條件:'])[1]/preceding::select[8]</value>
      <webElementGuid>fada4bef-4c47-45a4-8509-5ca2477ba427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>40d1e5a3-858d-4cac-9b0d-c76245122810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'sCriteria2' and @id = 'sCriteria2' and (text() = '
條碼號
正題名
書名
作廢日期
報廢文號
報廢批號
報廢備註
執行館員姓名
執行館員帳號
到館日期
館員註記
採購註記
期刊註記
財產編號
' or . = '
條碼號
正題名
書名
作廢日期
報廢文號
報廢批號
報廢備註
執行館員姓名
執行館員帳號
到館日期
館員註記
採購註記
期刊註記
財產編號
')]</value>
      <webElementGuid>12fc72aa-ba00-4502-b961-e684c86f8b21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
