<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__resetbutton</name>
   <tag></tag>
   <elementGuidId>191215db-1bf1-45a8-86f1-bd48f4c46a7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#resetbutton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='resetbutton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de91d64a-18ef-4109-828d-6f0af9e24d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>清除</value>
      <webElementGuid>68c74379-d38a-4db5-bd3d-709089df1a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttons</value>
      <webElementGuid>4c53681c-12e0-4856-b5a9-972a680c0c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7338005a-363d-4e4c-b66d-a4611b04644d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>updatecomponents</name>
      <type>Main</type>
      <value>checkList</value>
      <webElementGuid>4b6e67de-0775-4e01-9d5f-314c909cf418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>resetbutton</value>
      <webElementGuid>433080a5-8bd7-4b1d-b9a8-ebdec4dbd33d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resetbutton&quot;)</value>
      <webElementGuid>2923e7b2-6c3e-4a33-87b0-553455820b9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='resetbutton']</value>
      <webElementGuid>32a80bfa-50c6-4201-85e4-343307ac8372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='buttonReset']/input</value>
      <webElementGuid>975bbf30-e137-4a03-bba2-3fcb75910ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/input</value>
      <webElementGuid>7353f86c-0264-4154-beb5-39261ea07a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'resetbutton']</value>
      <webElementGuid>3761654f-69c7-4952-b1a6-a8834861de6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
