<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__RadioGroup_1</name>
   <tag></tag>
   <elementGuidId>fd998fe4-17f4-4f5b-bd85-348e0f7cc663</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RadioGroup_11</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RadioGroup_11']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52f29381-3604-42d8-a111-e462ce73f5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d79d477b-3d58-4959-ab36-73e90651771b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RadioGroup_1</value>
      <webElementGuid>8e4f1d58-9777-48b6-b42d-f5b1fdedebe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RadioGroup_11</value>
      <webElementGuid>ecc22038-f59b-4bd3-a3a7-62a650c2b943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>eaa16a16-177b-49f7-8006-8f3319838567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>tapestry.byId('RadioGroup_1').onChange(1);</value>
      <webElementGuid>f9105595-66da-4fd6-b8c1-31bf5a590e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RadioGroup_11&quot;)</value>
      <webElementGuid>ca235052-5475-42e4-95d1-8019b6e81ad3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RadioGroup_11']</value>
      <webElementGuid>a59dd24c-9814-40db-9899-cf3caf993d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='RadioGroup_1']/input[2]</value>
      <webElementGuid>582230d2-5591-4d37-aa91-1ab7dbff4e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/span/input[2]</value>
      <webElementGuid>dc56cbb0-819e-4346-804d-8e6cb24f71b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'RadioGroup_1' and @id = 'RadioGroup_11']</value>
      <webElementGuid>dd4174d4-6c7c-4599-b08c-a2a7440d8ead</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
