<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__field6</name>
   <tag></tag>
   <elementGuidId>1553b100-bab4-47e4-bdfd-e39999fd5d6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17a67124-c959-45f3-a10b-20cda83ea32e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>72bc6b0c-8d6d-4b6d-af3f-31434ed65ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field6</value>
      <webElementGuid>e11b2e07-5e00-4cbe-acd6-61fbfa6f63cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field6</value>
      <webElementGuid>4c05baec-ff2a-4879-9415-40bd07ec18cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>0c3f23a7-8c71-4a39-9ecf-2775a75d87d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field6&quot;)</value>
      <webElementGuid>b5695615-791c-4501-a802-ff22fabf8f7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field6']</value>
      <webElementGuid>8b5c6fa0-842c-4541-88de-7daea7401cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='list_temp_searchForm']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>c4f82d60-c43d-487a-8485-bbd68fddb295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>5fba4e85-584b-4a27-9576-2c2872e915be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'field6' and @id = 'field6']</value>
      <webElementGuid>ac3832b1-17cc-4673-88dd-4a8705190e53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
