<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_01234567891011121314151617181920212223_1</name>
   <tag></tag>
   <elementGuidId>38be045b-9d7b-4f5c-a103-df85228921a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#groupCount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='groupCount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e23fcdc8-c084-49a7-933a-d5a12552d2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>groupCount</value>
      <webElementGuid>4371fdec-a3d5-4e2e-a686-335137667e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>groupCount</value>
      <webElementGuid>5d146b34-739c-42ce-ac0c-fe9228736b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
</value>
      <webElementGuid>77575942-a775-415b-9138-7c571a755f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;groupCount&quot;)</value>
      <webElementGuid>ebed7c3a-941c-4baf-bd82-8671094ae826</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='groupCount']</value>
      <webElementGuid>4d831d43-fd38-46f9-8725-d9693cde39a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='LbaleParameterFrom']/table/tbody/tr[13]/td[4]/select</value>
      <webElementGuid>9ae5aa9c-298d-47d2-a264-475a83f03898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='列數:'])[1]/following::select[1]</value>
      <webElementGuid>93869c46-4a29-4f1a-a134-98f3bf516e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='字型水平位置:'])[1]/following::select[2]</value>
      <webElementGuid>bd90d4b4-d60e-498b-90db-92d4bf34bc7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='書標欄位'])[1]/preceding::select[1]</value>
      <webElementGuid>1447f932-ba06-4a9c-861c-2161ef1ab7bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='不印欄位'])[1]/preceding::select[1]</value>
      <webElementGuid>799f2747-3be2-4d1f-a770-2f40b9bafad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td[4]/select</value>
      <webElementGuid>1c1f6c67-443f-48e4-8771-e44cdae3d042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'groupCount' and @id = 'groupCount' and (text() = '
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
' or . = '
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
')]</value>
      <webElementGuid>0fe5f72a-6b27-47fb-a573-c4cbd6c2de52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
