<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>2582039d-78d0-4655-8baf-0e69b8c7f317</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>e</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4b548fdc-59c3-42ef-89ed-11ba84381b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>e3ad8c2c-aa20-482e-8599-5ca666bb4c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main_nav_ico15 </value>
      <webElementGuid>a33b353f-b863-4c4a-bbe9-903f856f9cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 管理 </value>
      <webElementGuid>a60d6fcf-ea36-4e3a-8357-03da78f939c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/ul[1]/li[10]/a[@class=&quot;main_nav_ico15&quot;]</value>
      <webElementGuid>72786994-fb20-4649-bdfa-d329bd137a9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/ul/li[10]/a</value>
      <webElementGuid>fdda3a70-c44f-408f-845a-12ebcf0dae64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'管理')]</value>
      <webElementGuid>27a36390-1906-4933-930e-fbdf5fe0ae7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='學科服務'])[1]/following::a[1]</value>
      <webElementGuid>d40951ea-231f-4b4d-833c-606a5e84b4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='我的帳戶'])[1]/following::a[2]</value>
      <webElementGuid>8a7a229c-bf15-49d0-9c91-32ee6e5b28c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='統計'])[1]/preceding::a[1]</value>
      <webElementGuid>ea04e705-9a47-4886-8e4d-425d85351ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='清單'])[1]/preceding::a[2]</value>
      <webElementGuid>a4f516bd-72ba-408c-b5c4-7f7ae01d085b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='管理']/parent::*</value>
      <webElementGuid>ae7ac81b-0b49-4008-86de-c8b32ebe84b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[12]</value>
      <webElementGuid>31b30f53-7e79-4725-8764-3dd6a95aea86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[10]/a</value>
      <webElementGuid>322bf0eb-c1c4-49a8-be3b-b5d1c4c6f64a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = ' 管理 ' or . = ' 管理 ')]</value>
      <webElementGuid>8aae3097-e62b-4f1c-8ed0-dbdfba8d47d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
