<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__field2</name>
   <tag></tag>
   <elementGuidId>1dd3bee4-2f1d-40cc-8148-e45d0b4b3a11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a98f955-519b-4c82-911f-7369053aabdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>18c1de5d-93b5-46ca-be4a-5947d65d9b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f46cc6df-e4d8-46a8-acbb-90d0752c1d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field2</value>
      <webElementGuid>b80018d4-1153-4880-93d4-d694ae43e440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field2</value>
      <webElementGuid>62c4fb4b-8f50-483d-b1f1-f2e84a1f24b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_mare</value>
      <webElementGuid>d71bac06-9939-4aac-880c-fc9b99eeb8c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>setFocus(2); VirtualKeyboard.attachInput(this);</value>
      <webElementGuid>41778815-f34d-4a19-808e-7e8fc49449fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field2&quot;)</value>
      <webElementGuid>e1ee760f-ad63-4831-aaad-54e88d1498a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field2']</value>
      <webElementGuid>6c314ed3-80ef-4288-933d-5fe557c71506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='inputField2']/nobr/input</value>
      <webElementGuid>59e5d47f-84ed-4fce-ba3f-7d089d4f9554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/span/nobr/input</value>
      <webElementGuid>88d34c2a-0a0c-4655-8a4e-b857ebe37b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field2' and @name = 'field2']</value>
      <webElementGuid>fe2732da-6c95-4bd5-b909-de928e43c0be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
