<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_1 - 1 - 20 10 (2.282 sec)_nextPage</name>
   <tag></tag>
   <elementGuidId>82338531-422f-41be-8d37-9f185eb1ab32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nextPage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nextPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1332e3f7-0e26-42e2-8a49-f3baa4c04c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nextPage</value>
      <webElementGuid>879d6253-1b99-4ae6-9a15-bb52001b2a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>next</value>
      <webElementGuid>2831e78d-2c77-44b7-a1f6-e1850bbdab4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/TopLoanList,nextPage.sdirect?updateParts=results&amp;updateParts=nrResults</value>
      <webElementGuid>241120a8-bc34-4624-a7f9-59339c55c217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return tapestry.linkOnClick(this.href,'nextPage', false)</value>
      <webElementGuid>37c078d0-5d66-489c-a211-1b505957f62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nextPage&quot;)</value>
      <webElementGuid>ab2d52f4-7e22-422a-ba92-f3aacaa81a0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nextPage']</value>
      <webElementGuid>3d11f684-59a2-4eb2-b7e6-b731f5a3b715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='If_6']/ul/li[6]/a</value>
      <webElementGuid>84649634-819c-4d3f-a012-05afe0588350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/TopLoanList,nextPage.sdirect?updateParts=results&amp;updateParts=nrResults')]</value>
      <webElementGuid>d0b3037b-1970-4a50-aac1-548625769ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/ul/li[6]/a</value>
      <webElementGuid>16f21b42-dbb8-42b0-bdd4-34636951083c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nextPage' and @href = '/inspireapp/TopLoanList,nextPage.sdirect?updateParts=results&amp;updateParts=nrResults']</value>
      <webElementGuid>bb0e31c5-de63-4913-ba54-f56e49a4e505</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
