<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td__1_2_3</name>
   <tag></tag>
   <elementGuidId>1674100d-63ef-43ec-838c-e587301654c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#If_42 > td.limit_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='If_42']/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>bfae93ff-0e90-497e-a6b6-09a85f94e95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>limit_title</value>
      <webElementGuid>cc044ca0-df75-4ef8-a597-c52e186837d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				        取書館別:</value>
      <webElementGuid>bffd2c37-c12b-4a72-9999-9177aca962b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;If_42&quot;)/td[@class=&quot;limit_title&quot;]</value>
      <webElementGuid>aba4116f-aeaa-4b98-97e0-22c1aae6159e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='If_42']/td</value>
      <webElementGuid>e052a3a0-ffcc-468d-bf86-30a9daff928c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='資料類型:'])[1]/following::td[2]</value>
      <webElementGuid>e9c30eda-f06e-45d1-948a-8fe21218407d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='館藏地:'])[1]/following::td[4]</value>
      <webElementGuid>28ac813e-bd0a-476e-a135-3d4c4bb99d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='瀏覽條件:'])[1]/preceding::td[2]</value>
      <webElementGuid>18a42f62-6020-4ad1-9253-86840f6387b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='起始以:'])[1]/preceding::td[4]</value>
      <webElementGuid>58c53cdc-c2d9-4f36-b60b-266249d84628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='取書館別:']/parent::*</value>
      <webElementGuid>5ab8ab3c-258a-4814-872e-169d952e38d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td</value>
      <webElementGuid>bd474aa9-3ef5-4c56-9078-9758879fc59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
				        取書館別:' or . = '
				        取書館別:')]</value>
      <webElementGuid>8fe27633-ee90-424c-ae34-06d143572272</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
