<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3</name>
   <tag></tag>
   <elementGuidId>bcad7db9-7e9a-4245-ae99-9c188caac50f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>afdd92be-2fc3-47d5-b77f-3a3118c9a750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_4</value>
      <webElementGuid>d5f32c0a-1471-42b6-ae43-373e8073d159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/TransactionsToUsageClass,$DirectLink.sdirect?sp=4&amp;updateParts=continut</value>
      <webElementGuid>1209f3cb-ff14-4e8f-a98b-31f3b2fc4c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return tapestry.linkOnClick(this.href,'DirectLink_4', false)</value>
      <webElementGuid>e10ad899-b129-4802-b5ee-7fd4eb50ef9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					測試 </value>
      <webElementGuid>0ea170bf-ecb4-4ae0-bfd0-203c5f21a182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_4&quot;)</value>
      <webElementGuid>b4cb62fc-1516-4940-af9a-9d766d2ccc6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_4']</value>
      <webElementGuid>61b05ff8-2248-44a1-b2b6-2aeb5cce8646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='For_4']/li/a</value>
      <webElementGuid>b0708661-72fc-400f-af3d-0e740342c747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'測試')]</value>
      <webElementGuid>5f83aba6-5fad-4bee-bb4b-adbd29f12194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='一般(Normal)'])[1]/following::a[1]</value>
      <webElementGuid>8237718b-4c69-4451-8228-95547829fb5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='新書(New Book)'])[1]/following::a[2]</value>
      <webElementGuid>4db987a3-e2c7-4cd5-ab21-32d8670f7ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testerer'])[1]/preceding::a[1]</value>
      <webElementGuid>989ee60c-2c17-4dad-a245-7031dcdd43be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eeewww'])[1]/preceding::a[2]</value>
      <webElementGuid>030ff27f-23a0-4cb8-a4c0-fcd0015cb5b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='測試']/parent::*</value>
      <webElementGuid>c3cfa707-179c-41a7-8470-8dd88b7b4c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/TransactionsToUsageClass,$DirectLink.sdirect?sp=4&amp;updateParts=continut')]</value>
      <webElementGuid>ab1c95da-7323-43fe-93ee-c847b92a2219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul[5]/li/a</value>
      <webElementGuid>c2333ba1-dc36-441c-a8c7-df11dd43d578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_4' and @href = '/inspireapp/TransactionsToUsageClass,$DirectLink.sdirect?sp=4&amp;updateParts=continut' and (text() = '
					測試 ' or . = '
					測試 ')]</value>
      <webElementGuid>b81d31e5-aa26-4a2d-80c8-916f037846ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
