<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_q</name>
   <tag></tag>
   <elementGuidId>94bc2a0f-ad67-445d-bef8-5fdfaf0367a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#q</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='q']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1c06e7e-ca0d-474c-9828-2b0e0ba15b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e4f3abb9-00d6-459c-a619-5a355a2dcc04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>65ed56b6-c61f-42c6-8375-9e204257d806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>4c00b9a4-fb4d-49f0-871a-b9e52b95d08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>VirtualKeyboard.attachInput(this);diacriticInsert(this);</value>
      <webElementGuid>a1abd8e0-5be6-46e0-bb84-d406edb74178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2048</value>
      <webElementGuid>3c5a0ec9-a61d-43db-b5bd-0f9d16fb489d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>41</value>
      <webElementGuid>dfa47f7a-8e1a-43f6-8ecf-ff3861d76a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;q&quot;)</value>
      <webElementGuid>8f449fd8-b9c9-48f6-9125-1ea4455e52a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='q']</value>
      <webElementGuid>0bf89186-335f-41cc-af89-b7c23fcd5759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='quickSearchForm']/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>93d1a876-780e-4a79-8e63-abf224e810c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>d4aa2920-7f04-4b59-8fee-6004660fcba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'q' and @id = 'q']</value>
      <webElementGuid>34753fe1-8cef-44e5-9293-e4865b6cf9e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
