<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__TextField_1</name>
   <tag></tag>
   <elementGuidId>ca656bb2-5723-4835-81bb-d7ddadb135cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextField_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TextField_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5040cdd-ec1c-49c2-b231-325dd46b3d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a6450b1e-eb7e-46ea-9493-b447c5469705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TextField_1</value>
      <webElementGuid>d1c7c376-5f5d-440a-8bad-a22038c9b166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextField_1</value>
      <webElementGuid>dc0a06f4-4c0d-40a8-9457-af80de37ecd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextField_1&quot;)</value>
      <webElementGuid>af207ac8-86f9-4728-ae9f-cabb81af55db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TextField_1']</value>
      <webElementGuid>e3c16050-606e-4225-9e09-230c53568168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showSearch']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>3629cf0a-2738-4b07-896b-b35ce6ff9a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>e150f12b-d697-41d0-997b-67f762617962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'TextField_1' and @id = 'TextField_1']</value>
      <webElementGuid>97012e86-20fe-4ded-8a5e-76be50346106</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
