<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__ImageSearch</name>
   <tag></tag>
   <elementGuidId>3aff87fa-b1c2-42d6-b1c0-fbb1669f3d5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ImageSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ImageSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cebfa843-3850-497d-9dae-7fb2b3193132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ImageSearch</value>
      <webElementGuid>9fd3bf54-1dbd-4138-9c94-5e2258f3a7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/inspireapp/images/arrow_unchecked.gif</value>
      <webElementGuid>490d5a52-7bfc-4a0c-a395-8596ed426c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c4aaf088-c5ab-4bdd-bcb0-304cd4c41ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ImageSearch&quot;)</value>
      <webElementGuid>580ec0ef-c2ac-4122-a4db-7a38b0ab0233</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ImageSearch']</value>
      <webElementGuid>1850ae23-a74a-45b5-b857-bb6356805d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='Body']/div/div/div[2]/div[2]/a[2]/font/b/img</value>
      <webElementGuid>21446c99-8492-4da6-9567-cd45e0624fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/font/b/img</value>
      <webElementGuid>b0b38f86-b268-4f92-993f-d720458a1872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'ImageSearch' and @src = '/inspireapp/images/arrow_unchecked.gif']</value>
      <webElementGuid>6b1025e8-373e-4563-a0b1-0496eeb357f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
