<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__TextField</name>
   <tag></tag>
   <elementGuidId>1a118a2c-fa07-49b9-a4ab-23da9dcc9cbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TextField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>406fa871-bacd-4643-99eb-5fb16ccf4f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c9751947-e048-42d5-ae97-dcc16074ae1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TextField</value>
      <webElementGuid>3a17d7cc-f67c-435e-babb-6fb22f66c2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextField</value>
      <webElementGuid>153910fd-89c3-41f2-b174-1cec0ac3f96f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>verifyStringLimit(this);</value>
      <webElementGuid>65e8ced7-e5fc-4d42-8b9e-e47b2615d407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>57</value>
      <webElementGuid>34a43c3e-2485-4ec8-9cc4-3878c67949fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextField&quot;)</value>
      <webElementGuid>434c1810-4fb7-44b1-a933-7860f087d532</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TextField']</value>
      <webElementGuid>73a099e8-d669-4ef7-9712-4debf171f984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PickListEdit']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>95d65330-9623-4b03-bb3d-528e71e1749a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>09a5e17c-0a68-4edd-b6f6-87a9ebb4adee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'TextField' and @id = 'TextField']</value>
      <webElementGuid>a3aba468-9367-4231-9164-62129eed6288</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
