<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_andornot_1_2</name>
   <tag></tag>
   <elementGuidId>91ed69a7-3ec7-40f2-a08a-b6045e253a59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='boolean4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boolean4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d7273e03-2e2d-4cb6-a277-e65a41af749a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>boolean4</value>
      <webElementGuid>6d1e35cd-f11f-47ec-8a0a-266c799a295f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boolean4</value>
      <webElementGuid>366b7805-db90-4b05-a715-bf17b493b4f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
and
or
not
</value>
      <webElementGuid>f1a48ae4-93d0-47f3-857c-4a02b2c8a1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boolean4&quot;)</value>
      <webElementGuid>b3ee0393-1d8c-44b7-801c-1901a7e70801</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='boolean4']</value>
      <webElementGuid>d2138ceb-d750-4e7d-b781-36b0dde61b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='If_21']/select</value>
      <webElementGuid>1b8220d3-8b33-4ec6-9ca3-d4838201c77c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='王丁熒'])[1]/following::select[1]</value>
      <webElementGuid>109db7ca-c68e-4194-8cab-a14031f569bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='王一芳'])[1]/following::select[1]</value>
      <webElementGuid>431bb4a7-42e6-4f44-a20c-2ea5f9147c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='限制條件'])[1]/preceding::select[3]</value>
      <webElementGuid>664fd647-a31f-4fc1-ae74-425b3a0fc864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='限制條件'])[2]/preceding::select[3]</value>
      <webElementGuid>a45d8c56-46fd-43e3-92ba-bdf800109300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[7]/select</value>
      <webElementGuid>8461ecc9-09c5-4875-b03e-c6ef3040e27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'boolean4' and @id = 'boolean4' and (text() = '
and
or
not
' or . = '
and
or
not
')]</value>
      <webElementGuid>658a2f7d-cae4-4dff-b75c-83c343c7a5b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
