<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>c1b5c352-85d1-4e5d-8917-c413ef5b3b6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#content-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3d9ba145-873f-4ed4-9fd6-8665b28c581e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content-button</value>
      <webElementGuid>4d249ff9-a32c-4cf7-8a07-5f7f90ede237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>594b0a4e-374a-4d12-9466-250aa6d8ae50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	        	到期日必須大於借閱日期
	        </value>
      <webElementGuid>62ca145b-d03e-49ac-9a5b-935dea952150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-button&quot;)</value>
      <webElementGuid>ffd40f37-bd95-4bc4-84e9-b8df05f40721</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='content-button']</value>
      <webElementGuid>c28ef655-805b-4588-89bf-6c68947b2bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TinreadMessageDialog_content']/div</value>
      <webElementGuid>08b3e6a2-0d6f-4813-a6bc-56665d2ac96c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='提示'])[2]/following::div[2]</value>
      <webElementGuid>057ce5c0-7502-4df0-ab3f-369d85562fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='確定'])[1]/preceding::div[1]</value>
      <webElementGuid>2856f5e8-5e47-4e3b-a968-f451f44fa9dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;&lt;'])[1]/preceding::div[5]</value>
      <webElementGuid>ab3eb883-991b-4d8f-8d77-0e0dd7613fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='到期日必須大於借閱日期']/parent::*</value>
      <webElementGuid>f4c73114-fb06-4219-83dc-e874245c3ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div</value>
      <webElementGuid>580661a0-5722-4fcb-a2c1-cf06cd7d0df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'content-button' and (text() = '
	        	到期日必須大於借閱日期
	        ' or . = '
	        	到期日必須大於借閱日期
	        ')]</value>
      <webElementGuid>fe25dc3b-0d1f-4a4f-ae18-48cfa3e6434d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
