<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3_4</name>
   <tag></tag>
   <elementGuidId>863985b8-30e1-4298-af8f-b6e0038238b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_0_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_0_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3edb107a-3ed5-472b-9dc2-6c4e0af4c60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_0_0</value>
      <webElementGuid>b4a3f8e7-fd67-4584-a113-634ac113a7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>butonsub</value>
      <webElementGuid>0320ae49-2004-4cf9-bd2e-cdb4a732bf6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/NotLoanHoldingsList,ReportsStatus.$DirectLink_0.sdirect?updateParts=ReportStatus</value>
      <webElementGuid>03da4a2e-bf8b-4c99-97cf-a1485194837b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return tapestry.linkOnClick(this.href,'DirectLink_0_0', false)</value>
      <webElementGuid>b41418eb-ded2-4fa2-8a2d-e6da158b53a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
										關閉 
								</value>
      <webElementGuid>a8fdd1dd-6e8c-4f55-bc89-9ce29ad67e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_0_0&quot;)</value>
      <webElementGuid>847a328b-7ad4-4999-bc02-1026335521e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_0_0']</value>
      <webElementGuid>dffce254-b5c5-496b-9692-5e35dca9e037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='If_7']/div/table/tbody/tr/td/table/tbody/tr/td[2]/a</value>
      <webElementGuid>f491c6f4-dff0-4644-a6d1-cf00a2295476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'關閉')]</value>
      <webElementGuid>a124a931-c51a-4f19-bf91-df337d9913a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='報表狀態'])[2]/following::a[2]</value>
      <webElementGuid>1238ae82-110c-451d-a224-5267d8e037a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='執行時間'])[1]/preceding::a[1]</value>
      <webElementGuid>bf8941c3-213e-4dce-a8e6-69a9d90bb3c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/NotLoanHoldingsList,ReportsStatus.$DirectLink_0.sdirect?updateParts=ReportStatus')]</value>
      <webElementGuid>309debd4-0585-4909-8d5c-fe44a2a43f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td[2]/a</value>
      <webElementGuid>7fccc432-1582-490e-bb96-d1eda8de6c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_0_0' and @href = '/inspireapp/NotLoanHoldingsList,ReportsStatus.$DirectLink_0.sdirect?updateParts=ReportStatus' and (text() = ' 
										關閉 
								' or . = ' 
										關閉 
								')]</value>
      <webElementGuid>d4b943df-8d91-4075-a469-59ec4af55d59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
