<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__browse</name>
   <tag></tag>
   <elementGuidId>f8ae37a8-19fb-4ad8-a730-60438ae10205</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='browse']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#browse</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c1048fd-b8f5-45b0-aced-fd0640ac0d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0f941e4e-e7f6-4785-8174-652ffad831e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>browse</value>
      <webElementGuid>33d74614-b439-489f-a912-6d2e1e2e2f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>browse</value>
      <webElementGuid>bb58f5b0-14a3-4a96-aae0-f6d33162b4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>瀏覽</value>
      <webElementGuid>9d76cec7-29e1-4a88-a3bf-a10b51922255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buton</value>
      <webElementGuid>68890ee3-fdd5-4643-b816-de41ca0ffe06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;browse&quot;)</value>
      <webElementGuid>e215f721-09a5-4348-aa65-2c620801b278</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='browse']</value>
      <webElementGuid>a7b79663-40a3-4696-abe1-3e44f85e2a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HiddenBrowse']/table/tbody/tr/td[6]/input</value>
      <webElementGuid>89de5040-8910-4393-a8e0-534b87952c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/input</value>
      <webElementGuid>7aaf06e7-9ed1-4896-a91d-62516ba7fe8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'browse' and @id = 'browse']</value>
      <webElementGuid>17e91562-96b8-4bef-9d35-35e70073fb00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
