<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b__1</name>
   <tag></tag>
   <elementGuidId>88f44bcb-eed0-49c2-8d52-ef6d085cb0b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nobr > font > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='If_62']/nobr/font/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>ffe40e00-8cb6-4e09-8019-f4ab87b91f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>瀏覽條件:</value>
      <webElementGuid>5aec2d63-1ae8-432e-a125-0bcfbf625f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;If_62&quot;)/nobr[1]/font[1]/b[1]</value>
      <webElementGuid>29e4ead9-1e8d-44b9-a37e-d425a8c88307</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='If_62']/nobr/font/b</value>
      <webElementGuid>b802e4af-2554-4562-a98a-f3b35dfddba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='館藏使用類型:'])[1]/following::b[1]</value>
      <webElementGuid>a62ffbd6-fa3b-4cfb-8466-8d7d50592b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='讀者身份類別:'])[1]/following::b[1]</value>
      <webElementGuid>6a9741f0-bd45-4a53-a7ec-1f465a3c63aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='起始以:'])[1]/preceding::b[1]</value>
      <webElementGuid>c7ea37c6-3209-4f17-af45-e2ce964cb0de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='排序條件:'])[1]/preceding::b[2]</value>
      <webElementGuid>388fadae-0a58-45f6-9aa1-5d4991fb8df7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='瀏覽條件:']/parent::*</value>
      <webElementGuid>de9cbbc4-13d4-45c7-946c-826f04043c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nobr/font/b</value>
      <webElementGuid>4325b508-6593-43ae-a4bb-8bf4baa2b01b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = '瀏覽條件:' or . = '瀏覽條件:')]</value>
      <webElementGuid>693320e9-a8d0-4ff0-8d9a-1b6481cb3ac9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
