<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>34832442-0242-4208-8116-1be25a95b80b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cf5878af-28a2-4dc9-99ae-cb40cad353e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_0</value>
      <webElementGuid>d9243455-d933-4428-bd4a-130e20d94203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico_5</value>
      <webElementGuid>62409992-c62c-4301-b43e-b9045a170124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>登出</value>
      <webElementGuid>839d03f5-5eb1-4aa6-b709-e323d3839cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/reports/circulation/CirculationReaderCrossAnalysisReport,$Border.$DirectLink_0.sdirect</value>
      <webElementGuid>5cbf76be-3436-4758-98a0-45c5649963e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>登 出</value>
      <webElementGuid>91cd156e-2609-43b8-80c0-9d3edfee8efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_0&quot;)</value>
      <webElementGuid>adc862d0-64e6-4d7a-a6b7-61fbaf0f8d25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_0']</value>
      <webElementGuid>f8ab0a69-55ed-4999-9624-09c971f85ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='LanguageForm']/div[2]/div/ul/li[10]/a</value>
      <webElementGuid>9f0bd631-e1ac-4fc4-b019-20a0a3f34250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'登 出')]</value>
      <webElementGuid>7c764b32-a6ed-4445-8104-5e197b090dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='繁體中文'])[2]/following::a[2]</value>
      <webElementGuid>65e4f5f1-81c5-419d-ab4d-f00bb9eb8272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::a[3]</value>
      <webElementGuid>4773ca1a-c2a1-4937-b68c-e95c32e255b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='神資圖書館(15trunk機)'])[1]/preceding::a[1]</value>
      <webElementGuid>0f5637df-f448-444b-a3ec-fbabd1f80f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='查詢'])[1]/preceding::a[1]</value>
      <webElementGuid>38042b77-cfa5-48cf-81cb-a39380d6ce95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='登 出']/parent::*</value>
      <webElementGuid>e0cbfec8-4a1b-4033-bd9d-8713f07da181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/reports/circulation/CirculationReaderCrossAnalysisReport,$Border.$DirectLink_0.sdirect')]</value>
      <webElementGuid>c6377193-bed7-46c8-ac4e-712da028a85c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a</value>
      <webElementGuid>9cac1ac2-e738-4173-a554-8e7c65579a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_0' and @title = '登出' and @href = '/inspireapp/reports/circulation/CirculationReaderCrossAnalysisReport,$Border.$DirectLink_0.sdirect' and (text() = '登 出' or . = '登 出')]</value>
      <webElementGuid>729ae201-7df5-4142-becc-08b0c6b31fff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
