<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3_4</name>
   <tag></tag>
   <elementGuidId>e3cc7060-9cdc-4fe5-ad7d-fc3b062f6bd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a1172f59-6974-4b17-9960-5b1edcc374b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_2</value>
      <webElementGuid>654be705-01e2-4241-90f5-4dc854f4caa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setstytle()</value>
      <webElementGuid>94ae51b0-c925-4775-a4ae-a64e1e08c9c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>butonsub</value>
      <webElementGuid>1a0666d7-22d9-4fa8-9308-6be9967a5df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/reports/circulation/CirculationReaderCrossAnalysisReport,ReportsStatus.$DirectLink.sdirect?updateParts=ReportStatus</value>
      <webElementGuid>dd4ed84c-cc68-4e17-b198-b2e4a336e5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 目前執行的報表</value>
      <webElementGuid>34655271-2a1b-497e-bb61-a027d247ee97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_2&quot;)</value>
      <webElementGuid>c54b936c-f433-4643-87c7-a0e5f44b2445</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_2']</value>
      <webElementGuid>63fd80e3-0c94-4ca7-83ed-ad439ce5505e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='If_7']/div/table/tbody/tr/td/table/tbody/tr/td/a</value>
      <webElementGuid>e75601cf-e3f9-4993-8941-b2af1f827a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'目前執行的報表')]</value>
      <webElementGuid>3fc44fb0-a3fb-460d-a5d9-77e7fcb6390d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='報表狀態'])[2]/following::a[1]</value>
      <webElementGuid>430bece8-0358-43a2-8169-b53802985b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='報表狀態'])[1]/following::a[1]</value>
      <webElementGuid>3601c3b5-b6f3-4d44-a5f3-76a48b27644d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/reports/circulation/CirculationReaderCrossAnalysisReport,ReportsStatus.$DirectLink.sdirect?updateParts=ReportStatus')]</value>
      <webElementGuid>4dffa09e-a5e6-4749-8048-a787b7b8d97e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td/a</value>
      <webElementGuid>fc2165da-ea21-488e-a384-7fe5a540dbac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_2' and @href = '/inspireapp/reports/circulation/CirculationReaderCrossAnalysisReport,ReportsStatus.$DirectLink.sdirect?updateParts=ReportStatus' and (text() = ' 目前執行的報表' or . = ' 目前執行的報表')]</value>
      <webElementGuid>fe54c152-d6f5-4770-ae47-698596599f93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
