<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3_4</name>
   <tag></tag>
   <elementGuidId>9c5b80cd-ac19-4f36-a75c-10b91d805514</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>60cdd62d-0a75-4bbb-b9b8-cc58306a9bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_2</value>
      <webElementGuid>9be23216-8128-4958-8ac4-085b11b507a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setstytle()</value>
      <webElementGuid>0e1a56b8-7d12-42a9-b13e-b5a61b75beca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>butonsub</value>
      <webElementGuid>d00b694e-67ce-470d-a699-9072692dea1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/SubscribeFullList,ReportsStatus.$DirectLink.sdirect?updateParts=ReportStatus</value>
      <webElementGuid>8f75158e-89fa-46be-83cd-f12673c8d7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 目前執行的報表</value>
      <webElementGuid>5af75dc4-66d5-4397-af58-7927f2deaeea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_2&quot;)</value>
      <webElementGuid>5811d2d2-e6f8-4967-b558-8487131ed305</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_2']</value>
      <webElementGuid>9252bb64-e541-4fc4-856c-6b8383866115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='If_11']/div/table/tbody/tr/td/table/tbody/tr/td/a</value>
      <webElementGuid>92174098-24ec-45fd-b503-80d8c53e7237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'目前執行的報表')]</value>
      <webElementGuid>1cfb4209-14d1-4bbb-ba6d-f0475ced9d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='報表狀態'])[2]/following::a[1]</value>
      <webElementGuid>a9989a37-b8bd-432c-8898-66af89b2f477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='報表狀態'])[1]/following::a[1]</value>
      <webElementGuid>fc22035c-244d-455d-9330-b68f0f538d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/SubscribeFullList,ReportsStatus.$DirectLink.sdirect?updateParts=ReportStatus')]</value>
      <webElementGuid>84f3fb28-6d8f-4572-84df-9374f76850c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td/a</value>
      <webElementGuid>d04ff4b2-b323-49d8-a35e-75d83d0ef0a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_2' and @href = '/inspireapp/SubscribeFullList,ReportsStatus.$DirectLink.sdirect?updateParts=ReportStatus' and (text() = ' 目前執行的報表' or . = ' 目前執行的報表')]</value>
      <webElementGuid>dfbcaea7-145b-48c5-994a-47507ed73f64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
