<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_by</name>
   <tag></tag>
   <elementGuidId>d8168260-58fb-4d5f-9f90-a804d37032e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(contains(text(), '崔明德') or contains(., '崔明德'))]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#If_16</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div[2]/div[2]/span/div/div/ol/li[1]/table/tbody/tr/td[2]/div/div[1]/text()</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>389d0460-e2fb-4b69-ae12-0df906bf087a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>If_16</value>
      <webElementGuid>afb1ec86-08c3-4318-ac90-e601361b19dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>崔明德</value>
      <webElementGuid>35fe102b-53c1-4318-bef5-be792702be8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;If_16&quot;)</value>
      <webElementGuid>9385dcd0-5538-41fe-8f67-b4439f589bd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='If_16']</value>
      <webElementGuid>75d7b243-eb3f-450b-81c4-cff0bfbaf92e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='For_2']/table/tbody/tr/td[2]/div/div</value>
      <webElementGuid>c54c53c8-6e63-47a8-b91d-9df0dc97a950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div</value>
      <webElementGuid>53303f36-f1d0-4d12-a967-c4ce6d7e1dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'If_16' and (text() = '
                    by: 
                    崔明德著
                  ' or . = '
                    by: 
                    崔明德著
                  ')]</value>
      <webElementGuid>1bf15e0f-9657-402c-8599-b3cb1bf67a38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
