<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3</name>
   <tag></tag>
   <elementGuidId>861d0e50-5434-45bc-9273-54a3d7982169</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0e1abab4-b4c6-4002-8d20-25305f0b0d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_0</value>
      <webElementGuid>462ed9a7-2f01-4912-8d32-2082566f6d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico_5</value>
      <webElementGuid>29b99ec5-a763-47ed-b48c-dd8822717267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>登出</value>
      <webElementGuid>ec20126a-5c07-45e6-9656-5b32477909bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/internaltranzit/ManageInBatch,$Border.$DirectLink_0.sdirect</value>
      <webElementGuid>6254233b-4fca-4a48-a896-f0cf9aafab45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>登 出</value>
      <webElementGuid>3841f1d5-e7d1-4642-8c6e-431376e6b0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_0&quot;)</value>
      <webElementGuid>cf10c9c7-bdd1-4eb5-a479-4a2b641eb12a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_0']</value>
      <webElementGuid>96225e9f-f344-40d0-bea1-7514511e6087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='LanguageForm']/div[2]/div/ul/li[10]/a</value>
      <webElementGuid>be8a68b3-09b1-4ae9-86bf-43d5016954bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'登 出')]</value>
      <webElementGuid>9b21883b-e38f-4c85-8a73-912b36fea20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='繁體中文'])[2]/following::a[2]</value>
      <webElementGuid>d1adadc4-b0eb-4fd4-8a57-2c40bf0d0083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::a[3]</value>
      <webElementGuid>c123834a-8989-4d1e-838f-c36a8bfb8a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='神資圖書館(15trunk機)'])[1]/preceding::a[1]</value>
      <webElementGuid>88efd14c-7c3a-436d-8d9e-edc756f6276d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='查詢'])[1]/preceding::a[1]</value>
      <webElementGuid>7600cbbe-ab2b-4595-a9d3-2d58e68dd8da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='登 出']/parent::*</value>
      <webElementGuid>f1e69da7-89d6-4ac9-b2ea-9bd0bce200b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/internaltranzit/ManageInBatch,$Border.$DirectLink_0.sdirect')]</value>
      <webElementGuid>9ba28aeb-0e4a-4177-8fc0-475a2210ec09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a</value>
      <webElementGuid>f5daa525-100d-4bd5-aa3c-cf28efb6d0ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_0' and @title = '登出' and @href = '/inspireapp/internaltranzit/ManageInBatch,$Border.$DirectLink_0.sdirect' and (text() = '登 出' or . = '登 出')]</value>
      <webElementGuid>28202bb2-e61f-4002-a84d-cc531ddaa4c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
