<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_MATLAB1PHP</name>
   <tag></tag>
   <elementGuidId>9ca4beb6-d9f4-471e-9f81-f47430319ea8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PropertySelection_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PropertySelection_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cb62a770-5734-415c-9639-544f1b5a7cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PropertySelection_0</value>
      <webElementGuid>9df139fa-3492-4e1c-8552-a7418d720656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PropertySelection_0</value>
      <webElementGuid>4354dd23-da95-436b-a322-451996a6c5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>

有效讀者
微波通訊
MATLAB程式設計
無線行動網路架構
電力電子學
硬體描述語言設計
電路板設計實務
通訊實習
手持式裝置設計與應用
進階數學
半導體元件及量測實務
科技英文
創意與專利1
PHP程式設計
離職離校
</value>
      <webElementGuid>1c0ebdb9-4d0f-48f5-8d6f-c5d1d73b1ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PropertySelection_0&quot;)</value>
      <webElementGuid>39b8789e-1b5c-458b-a155-542fbfc71bec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PropertySelection_0']</value>
      <webElementGuid>e3a3117f-a716-4d31-b12c-07b44145c25b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div[2]/table/tbody/tr[5]/td[2]/select</value>
      <webElementGuid>6f738447-a848-41d8-a45d-d49694f264ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='讀者狀態'])[1]/following::select[1]</value>
      <webElementGuid>370f3b39-b14e-4a09-80c0-5ec90f2cbdd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='一般讀者或有欠書欠款'])[1]/following::select[2]</value>
      <webElementGuid>65fde904-487b-4f2e-98c8-99436461bb76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='讀者身分類別'])[1]/preceding::select[1]</value>
      <webElementGuid>fab82096-0ca2-4e22-a3f2-5e6a3c04f068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='動態報表欄位'])[1]/preceding::select[2]</value>
      <webElementGuid>989b0408-504b-4860-9cec-a2f445a138bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/select</value>
      <webElementGuid>d5448d05-4189-4f96-beae-4bb29c9c7ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'PropertySelection_0' and @id = 'PropertySelection_0' and (text() = '

有效讀者
微波通訊
MATLAB程式設計
無線行動網路架構
電力電子學
硬體描述語言設計
電路板設計實務
通訊實習
手持式裝置設計與應用
進階數學
半導體元件及量測實務
科技英文
創意與專利1
PHP程式設計
離職離校
' or . = '

有效讀者
微波通訊
MATLAB程式設計
無線行動網路架構
電力電子學
硬體描述語言設計
電路板設計實務
通訊實習
手持式裝置設計與應用
進階數學
半導體元件及量測實務
科技英文
創意與專利1
PHP程式設計
離職離校
')]</value>
      <webElementGuid>fa0c94ba-934e-40e9-8cc6-fbcdc172cf4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
