<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>409da5a8-3db2-48c2-a13b-bb541d5be2b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.current > ul.ssub_nav_ul > li:nth-of-type(4) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu2']/ul[11]/li[6]/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>af2e85ed-558d-4654-b0f4-703f7ed27641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/FullfillRateBySupplier.page?init=1</value>
      <webElementGuid>8344ce11-5073-485b-9aaf-bb7ddecbfd6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>書商到書率</value>
      <webElementGuid>6ebe33e2-d8bb-48c5-8f8b-c80b2afabcd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2&quot;)/ul[@class=&quot;sub_nav_ul&quot;]/li[@class=&quot;current&quot;]/ul[@class=&quot;ssub_nav_ul&quot;]/li[4]/a[1]</value>
      <webElementGuid>43f9b675-f1ce-437d-823a-948061b30ab7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2']/ul[11]/li[6]/ul/li[4]/a</value>
      <webElementGuid>0fc07ffe-7ee1-4b41-8c75-c065817817ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'書商到書率')])[2]</value>
      <webElementGuid>d02c64dd-e1f0-439e-8b31-abc7be9e91db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='歷年期刊借閱統計'])[1]/following::a[1]</value>
      <webElementGuid>78c01dd6-5b60-4199-b5b5-82f84120d370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='平均收刊日統計報表'])[1]/following::a[2]</value>
      <webElementGuid>c66eb7be-9d03-4c98-ab6e-8889cbbc21d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='書商催缺次數'])[1]/preceding::a[1]</value>
      <webElementGuid>6708dc9a-9ea8-4187-a942-ad0f5c2312fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='書商累計訂購次數'])[1]/preceding::a[2]</value>
      <webElementGuid>82abd547-8ed3-4396-aecf-8856a08e6015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/FullfillRateBySupplier.page?init=1')]</value>
      <webElementGuid>b397f6cb-1d2c-4a45-abe9-183eec3d817e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[11]/li[6]/ul/li[4]/a</value>
      <webElementGuid>d0a28931-b874-4791-a0b6-d13c15814784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/FullfillRateBySupplier.page?init=1' and (text() = '書商到書率' or . = '書商到書率')]</value>
      <webElementGuid>7b9945c3-3d12-450d-bd72-bd69ae56fe91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2']/ul[11]/li[5]/ul/li[4]/a</value>
      <webElementGuid>f07b310f-8b6f-4d49-bb0f-9953c4cd5ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'書商到書率')]</value>
      <webElementGuid>0e164ad3-17fc-43b5-b777-fe5d97f75a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='特藏訂購方式金額統計'])[1]/following::a[1]</value>
      <webElementGuid>ce72679f-6780-4a13-8177-956e13142440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='年度經費採購統計'])[1]/following::a[2]</value>
      <webElementGuid>31adeae1-8cf0-4e31-8404-4b5fe6f15a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='書商績效統計'])[1]/preceding::a[1]</value>
      <webElementGuid>ef8cb113-84a6-478a-a8e5-4a19888d793c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='期刊到刊率統計報表'])[1]/preceding::a[3]</value>
      <webElementGuid>1fd220b9-d06e-44c7-be5b-46ed73753e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='書商到書率']/parent::*</value>
      <webElementGuid>52543009-849c-4f4c-918a-5e725fd70ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/PurchaseFullfillRateBySupplier.page?init=1')]</value>
      <webElementGuid>689a7511-88ba-4f74-9177-fa93131ebf43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[11]/li[5]/ul/li[4]/a</value>
      <webElementGuid>53f5b578-de85-4a91-a737-2e103ea1c4b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/PurchaseFullfillRateBySupplier.page?init=1' and (text() = '書商到書率' or . = '書商到書率')]</value>
      <webElementGuid>098d0729-cf9e-4d27-b923-7436ab536555</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
