<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1</name>
   <tag></tag>
   <elementGuidId>cc44ec85-78fb-406f-b490-9cae2a44f0ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a3b5bf8b-b9c6-4791-ac2d-165847752fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_1</value>
      <webElementGuid>c0535c7a-72f7-4ae6-bef4-32bf6ca1e092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>butonsub</value>
      <webElementGuid>69773eac-a5ea-4ab0-8084-2c6046e44afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/AddOrEditClassify,$PopupBorder.$DirectLink_1.sdirect</value>
      <webElementGuid>db99c55c-8341-48a0-9191-75d4397517e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				  是  
			</value>
      <webElementGuid>b1e58f9c-9b47-4774-8a3f-153420e16ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_1&quot;)</value>
      <webElementGuid>cd7665c1-b368-4a6e-b187-3dd25b4f15cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_1']</value>
      <webElementGuid>371ff74d-ac88-4b7d-819a-023653c4379c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CloseReminderDialog_content']/table/tbody/tr/td[2]/a</value>
      <webElementGuid>2f16962c-fd9b-4f34-ab70-1fd63430d5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'是')]</value>
      <webElementGuid>11222836-2d0d-4c7a-a3f1-4fcd23d88dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='提示'])[1]/following::a[1]</value>
      <webElementGuid>8dbc1a6b-726c-41d8-81a0-b97ee083643f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='修改/存檔'])[1]/following::a[2]</value>
      <webElementGuid>9e711d43-da8f-4031-9bcf-c33eaafa47d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/AddOrEditClassify,$PopupBorder.$DirectLink_1.sdirect')]</value>
      <webElementGuid>0081ff6b-e01f-4eb6-b10e-38ee0a4ea86b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>c38ca516-41ee-4dc5-bb4a-7cb707fcb65c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_1' and @href = '/inspireapp/AddOrEditClassify,$PopupBorder.$DirectLink_1.sdirect' and (text() = '
				  是  
			' or . = '
				  是  
			')]</value>
      <webElementGuid>ad537e61-ff1f-4eac-a30c-4494d9d48520</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
