<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1</name>
   <tag></tag>
   <elementGuidId>e25cf7d9-d5d1-4a02-8b69-ba76d3f666a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu2']/ul[3]/li[12]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.sub_nav_ul > li:nth-of-type(12) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ec400b79-825d-4154-80c6-e018bfb19dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/BorrowBox.page?init=1</value>
      <webElementGuid>dfa57d9b-769b-4b9b-a07f-9a2f9e599d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>書箱作業</value>
      <webElementGuid>2d16a461-c605-4725-8b67-6fd7ddeb3fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2&quot;)/ul[@class=&quot;sub_nav_ul&quot;]/li[12]/a[1]</value>
      <webElementGuid>5adaabbb-39e7-415d-91b3-f890d894f443</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2']/ul[3]/li[12]/a</value>
      <webElementGuid>dbe2cce5-21c1-4fee-aeba-2eaea5ebecf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'書箱作業')]</value>
      <webElementGuid>766e6227-0392-4475-a5f6-acdae96542b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='已報廢歷史查詢'])[1]/following::a[1]</value>
      <webElementGuid>aa337250-edb2-4dd1-bc9b-d2bd3d92dcdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='執行報廢'])[1]/following::a[2]</value>
      <webElementGuid>cd22b50c-17f6-4cdc-9678-2b0b74cb4fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='條碼號空號清單(條碼機印製)'])[1]/preceding::a[1]</value>
      <webElementGuid>496b8ecf-2dd8-4df8-9949-a0d4c312f3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='檢查薦購'])[1]/preceding::a[3]</value>
      <webElementGuid>3d18cb6a-304b-4d9c-8e21-c104d514e167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='書箱作業']/parent::*</value>
      <webElementGuid>ef3d2f22-7627-44fb-ab03-2d638e150304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/BorrowBox.page?init=1')]</value>
      <webElementGuid>dd457d1f-b7c4-4c39-a68c-8c6e9bee05a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[3]/li[12]/a</value>
      <webElementGuid>c91896d3-7d3b-4ad8-a8e3-43fc636cbbe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inspireapp/BorrowBox.page?init=1' and (text() = '書箱作業' or . = '書箱作業')]</value>
      <webElementGuid>4e461018-38f0-439f-aace-fd1448e42ee3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
