<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ABC_sd2</name>
   <tag></tag>
   <elementGuidId>a66d0132-5607-4b31-bf20-71873fb3f884</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sd2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sd2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c6cf463-1bd2-4f22-8462-f7790f246d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ffcd22c-348f-4b0b-b6af-de5003086e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sd2</value>
      <webElementGuid>a5ea5e17-b0b4-411f-982b-1600201a952f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>yyyy/MM/dd</value>
      <webElementGuid>772c2c91-a5fb-467a-9628-d2bce4a0789d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sd2</value>
      <webElementGuid>37186613-6a27-4dd3-8022-e2184b2b733d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>format</name>
      <type>Main</type>
      <value>java.text.SimpleDateFormat@f9e3bac0</value>
      <webElementGuid>c6503b95-3b99-461e-a7ff-e3c44c5c70d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>3dd3db10-71bd-4b19-8086-35eda7552fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sd2&quot;)</value>
      <webElementGuid>1d23f1fa-6021-4725-a0e1-110b17e03702</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sd2']</value>
      <webElementGuid>23524227-bf5a-4b88-a53a-209c0368ccca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='inputField2']/nobr/input</value>
      <webElementGuid>60a69ec8-15aa-4ec7-b80e-cd8fe6aa8ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/span[2]/nobr/input</value>
      <webElementGuid>e26b2990-e46b-4ca1-8c0e-cdb8ef776ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'sd2' and @title = 'yyyy/MM/dd' and @id = 'sd2']</value>
      <webElementGuid>71eb27c6-5abc-4e1b-831c-9fb07cbb024f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
