<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_open</name>
   <tag></tag>
   <elementGuidId>0b6d3adf-72cd-4c43-92df-7b82b18f5d86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nobr > div.tree-options-input-box > img.open</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='If_59']/td[2]/nobr/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6ff2e2c9-6393-440b-8e35-ae6646c1dbe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>f10869ad-b297-4a4d-9b0b-384356e5b4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/inspireapp/images/ico_add.gif</value>
      <webElementGuid>da5a66d2-95c1-4a69-8148-2fafd97298bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;If_59&quot;)/td[2]/nobr[1]/div[@class=&quot;tree-options-input-box&quot;]/img[@class=&quot;open&quot;]</value>
      <webElementGuid>c564af37-6ed6-48e2-bef2-41a1366a92ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='If_59']/td[2]/nobr/div/img</value>
      <webElementGuid>65c6f3ea-fafe-4c42-b072-8fb480de0e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nobr/div/img</value>
      <webElementGuid>d2f1e8e8-3f1d-4e52-8582-647b156c7b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/inspireapp/images/ico_add.gif']</value>
      <webElementGuid>33eead55-20a0-4e6b-b477-d7e66c9c8ff1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
