<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3_4_5_6_7_8_9_10_11_12_13_14_15</name>
   <tag></tag>
   <elementGuidId>af4f72ff-5493-4338-90a4-bf2842728f52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectLink_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2a825456-1f6d-45b1-a214-f2a5959077a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectLink_0</value>
      <webElementGuid>ba2df263-838a-4484-bcfe-e7b52f852567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico_5</value>
      <webElementGuid>f462387a-cc00-472c-a89e-7353a12e7634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>登出</value>
      <webElementGuid>c1814c24-8dde-4484-afc1-1eacb295bdaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inspireapp/PolicyMaintain,$Border.$DirectLink_0.sdirect</value>
      <webElementGuid>ef244ec4-4f93-425f-8843-0e3267597ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>登 出</value>
      <webElementGuid>6cd35bce-f9b2-49e9-8468-ab25628a377d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_0&quot;)</value>
      <webElementGuid>985245c2-9f5c-44ad-bc72-f8f0ed7e180c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_0']</value>
      <webElementGuid>abd4a79a-bc13-4f0e-b2a1-379d9c204701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='LanguageForm']/div[2]/div/ul/li[10]/a</value>
      <webElementGuid>61cdae19-f47a-4b30-8b88-f67bbb46f35c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'登 出')]</value>
      <webElementGuid>3d7e7037-64a7-41c8-8095-65ec87ba627c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='繁體中文'])[2]/following::a[2]</value>
      <webElementGuid>7fc8a49e-5cd7-4ae3-9fd6-0b1cd9fba217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::a[3]</value>
      <webElementGuid>7ffb1d68-495d-44f4-a281-ebf6eec62e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='神資圖書館(15trunk機)'])[1]/preceding::a[1]</value>
      <webElementGuid>2bbfc9a7-045d-45c0-8db2-546b2bf65d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='查詢'])[1]/preceding::a[1]</value>
      <webElementGuid>0994c583-d2c6-4907-a31d-1295e3ce045e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='登 出']/parent::*</value>
      <webElementGuid>03013bbd-fc25-4f03-8070-5901ad15af83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inspireapp/PolicyMaintain,$Border.$DirectLink_0.sdirect')]</value>
      <webElementGuid>a1a4a836-7060-4b7a-92df-0a6c95a65365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a</value>
      <webElementGuid>880b69be-527a-4f84-909a-87a7c2af5876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectLink_0' and @title = '登出' and @href = '/inspireapp/PolicyMaintain,$Border.$DirectLink_0.sdirect' and (text() = '登 出' or . = '登 出')]</value>
      <webElementGuid>5b20e5c8-697d-4aac-b6ce-999e5c3e78c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
