<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__Any_2</name>
   <tag></tag>
   <elementGuidId>d2828c3e-3135-4f08-90a9-c38e27d859f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='Any_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DirectLink_2 > #Any_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>36c3f6aa-b850-4a69-8333-4d85de5ed5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/inspireapp/images/edit.gif</value>
      <webElementGuid>63e4530c-4340-4a0c-bad0-03d0b01a9c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>567d3ea0-1535-4b9f-80da-6090442d3e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9c740693-1db2-4c19-9b48-e920d3947ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>551f77da-b8ce-4301-9a15-780a9d50ccf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Any_2</value>
      <webElementGuid>2bd40fc9-becb-4ee2-9e5b-ca29ee830834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectLink_2&quot;)/img[@id=&quot;Any_2&quot;]</value>
      <webElementGuid>6d1d80b2-ef95-4caf-99a2-e2a7eb67efe0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='Any_2']</value>
      <webElementGuid>b5ac0da0-f554-4b34-be34-f927bceb6eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='DirectLink_2']/img</value>
      <webElementGuid>1b44d78f-38f3-4b94-8c08-95add4395cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a/img</value>
      <webElementGuid>f5634aee-2468-4089-b501-6a0fcdb12133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/inspireapp/images/edit.gif' and @id = 'Any_2']</value>
      <webElementGuid>252949fc-c1c0-49cb-9c27-72bdc49511b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
